export const SYNONYMS = {
  // Induction of labour
  "iol": ["induction of labour","induction","induce","propess","crb","prostin","oxytocin","bishop score"],
  "induction": ["induction of labour","iol","propess","crb","dinoprostone","oxytocin","arm","bishop score"],
  "induce": ["induction of labour","iol","propess","crb","bishop score"],
  "post dates": ["post-maturity","induction","40+7","overdue","iol"],
  "post-dates": ["post-maturity","induction","40+7","overdue","iol"],
  "overdue": ["post-dates","post-maturity","40+7","induction of labour"],
  "propess": ["dinoprostone","prostaglandin","induction of labour","iol","cervical ripening","second line"],
  "dinoprostone": ["propess","prostaglandin","induction of labour","iol"],
  "crb": ["cervical ripening balloon","balloon","induction of labour","iol","first line"],
  "balloon": ["crb","cervical ripening balloon","induction of labour","iol"],
  "cervical ripening": ["crb","balloon","propess","induction","bishop score"],
  "bishop score": ["cervix","induction of labour","iol","crb","propess","amniotomy","arm"],
  "bishop": ["bishop score","cervix","induction","iol"],
  "arm": ["amniotomy","artificial rupture of membranes","induction","iol","oxytocin"],
  "amniotomy": ["arm","artificial rupture of membranes","induction","oxytocin","iol"],
  "oxytocin": ["syntocinon","augmentation","induction of labour","arm","amniotomy"],
  "syntocinon": ["oxytocin","augmentation","induction of labour"],
  "augmentation": ["oxytocin","syntocinon","arm","induction of labour"],
  "prostin": ["dinoprostone","gel","induction","iol","prom","second line"],
  "prom": ["pre-labour rupture of membranes","plrom","srom","waters breaking","term prom"],
  "plrom": ["prom","term prom","srom","rupture of membranes","induction of labour"],
  "srom": ["prom","plrom","rupture of membranes","waters broken","term prom","liquor"],
  "waters broken": ["srom","prom","plrom","rupture of membranes","liquor"],
  "water breaking": ["srom","prom","plrom","rupture of membranes"],
  "rupture of membranes": ["srom","prom","plrom","amnisure","liquor","term prom"],
  "hyperstimulation": ["propess","dinoprostone","terbutaline","induction","contractions","fhr"],
  "tachysystole": ["propess","contractions","induction","ctg"],
  "terbutaline": ["hyperstimulation","propess","tocolysis","uterine contractions"],
  // Skin & wound
  "cellulitis": ["wound","skin infection","soft tissue","cellulitis","redness","erythema","infected wound","co-amoxiclav","flucloxacillin"],
  "skin infection": ["cellulitis","wound","soft tissue","erythema","infected wound"],
  "wound infection": ["cellulitis","cs wound","wound","surgical site","co-amoxiclav"],
  "infected wound": ["cellulitis","wound infection","cs wound","co-amoxiclav"],
  "red wound": ["cellulitis","wound infection","erythema"],
  "perineal infection": ["perineal","episiotomy","wound","cellulitis","soft tissue"],
  // Seizure
  "fitting": ["eclampsia","seizure","convulsion","mgso4"],
  "fit": ["eclampsia","seizure","mgso4"],
  "seizure": ["eclampsia","fitting","convulsion","mgso4"],
  "convulsion": ["eclampsia","seizure","fitting","mgso4"],
  // Discharge
  "how long": ["length of stay","discharge","stay","duration"],
  "go home": ["discharge","criteria","length of stay"],
  "when can she leave": ["discharge criteria","discharge","length of stay"],
  // PET / hypertension
  "pe":  ["pre-eclampsia","preeclampsia","eclampsia","pet","hypertension in pregnancy"],
  "pet": ["pre-eclampsia","preeclampsia","hypertension in pregnancy","eclampsia"],
  // BP / medication
  "bp meds": ["antihypertensive","labetalol","nifedipine","medication"],
  "blood pressure tablets": ["antihypertensive","labetalol","nifedipine"],
  "high bp": ["hypertension","blood pressure","antihypertensive"],
  // UTI
  "urine infection": ["uti","urinary tract infection","cystitis"],
  "water infection": ["uti","urinary tract infection","cystitis"],
  "wee infection": ["uti","cystitis"],
  "kidney infection": ["pyelonephritis","uti","renal"],
  // CS / section
  "section antibiotics": ["caesarean","lscs","prophylaxis","co-amoxiclav"],
  "cs antibiotics": ["caesarean","lscs","prophylaxis"],
  // GBS
  "gbs": ["group b strep","streptococcus","iap","benzylpenicillin"],
  "strep b": ["gbs","group b strep","iap"],
  // Sepsis / infection
  "bug": ["infection","sepsis","antibiotics"],
  "womb infection": ["endometritis","uterus"],
  "infection after birth": ["endometritis","sepsis","postnatal","puerperal"],
  // Allergy
  "allergy": ["penicillin allergy","teicoplanin","clindamycin","alternative"],
  "pen allergy": ["penicillin allergy","teicoplanin","clindamycin"],
  // Breast
  "sore breast": ["mastitis","breast abscess","breast"],
  "breast infection": ["mastitis","breast abscess","cellulitis","flucloxacillin"],
  // Breastfeeding
  "breastfeed": ["breastfeeding","lactation","safe"],
  // Miscarriage — general
  "mc": ["miscarriage","early pregnancy loss","first trimester"],
  "miscarriage": ["missed miscarriage","incomplete miscarriage","complete miscarriage","threatened","early pregnancy loss"],
  "early pregnancy loss": ["miscarriage","first trimester","epagu"],
  "erpc": ["smm","surgical management of miscarriage","evacuation","surgical"],
  "evacuation": ["smm","erpc","surgical management of miscarriage","theatre"],
  "pregnancy loss": ["miscarriage","missed miscarriage","incomplete","complete"],
  "retained products": ["incomplete miscarriage","erpc","smm","poc","retained"],
  "poc": ["products of conception","retained products","histology","smm"],
  "products of conception": ["poc","retained products","smm","histology"],
  // Miscarriage — types
  "missed mc": ["missed miscarriage","no heartbeat","anembryonic"],
  "silent miscarriage": ["missed miscarriage","no heartbeat","anembryonic"],
  "blighted ovum": ["anembryonic","missed miscarriage","gestation sac"],
  "no heartbeat": ["missed miscarriage","fetal loss","anembryonic"],
  "incomplete mc": ["incomplete miscarriage","retained products","open os"],
  "threatened mc": ["threatened","viable","bleeding in pregnancy"],
  "threatened miscarriage": ["viable","threatened","bleeding","progesterone"],
  // Medical management of miscarriage
  "mifepristone": ["mifepristone","misoprostol","medical management","200mg"],
  "misoprostol": ["misoprostol","mifepristone","medical management","800mcg"],
  "medical miscarriage": ["mifepristone","misoprostol","medical management","cg621"],
  "pills for miscarriage": ["mifepristone","misoprostol","medical management"],
  // Ectopic
  "ectopic": ["ectopic pregnancy","methotrexate","mtx","bhcg","tubal","unruptured"],
  "ectopic pregnancy": ["methotrexate","mtx","bhcg","tubal","unruptured","ectopic"],
  "tube": ["ectopic pregnancy","tubal","fallopian","bhcg"],
  "mtx": ["methotrexate","ectopic","bhcg","day 4","day 7"],
  "methotrexate": ["mtx","ectopic","bhcg","day 4","day 7","cytotoxic"],
  "bhcg": ["beta hcg","ectopic","bhcg monitoring","day 4","day 7"],
  "beta hcg": ["bhcg","ectopic","monitoring"],
  "tubal": ["ectopic","tubal pregnancy","fallopian","mtx"],
  "shoulder tip pain": ["ectopic","haemorrhage","rupture","attend ed"],
  // PPRoM
  "pprom": ["pprom","preterm","rupture of membranes","amoxicillin","azithromycin","liquor","amni-sure"],
  "waters broken": ["pprom","rupture of membranes","liquor","amni-sure"],
  "membranes": ["pprom","rupture","liquor","preterm"],
  "liquor": ["pprom","amniotic fluid","amni-sure","rupture of membranes"],
  "amni-sure": ["pprom","liquor","rupture of membranes"],
  "preterm rupture": ["pprom","premature rupture","membranes","amoxicillin"],
  "chorioamnionitis": ["pprom","infection","antibiotics","delivery","sepsis"],
  // PUV / uncertain viability
  "uncertain viability": ["puv","pregnancy of uncertain viability","rescan","7-14 days"],
  "puv": ["uncertain viability","rescan","gestation sac","fetal pole"],
  "pul": ["pregnancy of unknown location","ectopic","bhcg","complete miscarriage"],
  "pregnancy of unknown location": ["pul","ectopic","bhcg","complete miscarriage"],
  // Iron deficiency anaemia
  "anaemia": ["iron deficiency","haemoglobin","ferritin","hb","oral iron","ferinject","iv iron","ida"],
  "anemia": ["iron deficiency","haemoglobin","ferritin","hb","oral iron","ferinject","iv iron","ida"],
  "ida": ["iron deficiency anaemia","ferritin","haemoglobin","ferinject","oral iron","enoxaparin"],
  "iron": ["iron deficiency","anaemia","ferritin","ferinject","oral iron","ferrous fumarate","ferrous sulphate"],
  "ferinject": ["iv iron","intravenous iron","ferric carboxymaltose","ganzoni","anaemia","ida"],
  "iv iron": ["ferinject","intravenous iron","ferric carboxymaltose","ganzoni","ida"],
  "ferritin": ["iron deficiency","anaemia","ida","ferrous fumarate","ferinject"],
  "ferrous fumarate": ["oral iron","iron","anaemia","ida","ferrous sulphate"],
  "ferrous sulphate": ["oral iron","iron","anaemia","ida","ferrous fumarate"],
  "low haemoglobin": ["anaemia","iron deficiency","hb","ida","ferinject"],
  "low hb": ["anaemia","iron deficiency","haemoglobin","ida","ferinject"],
  "ganzoni": ["ferinject","iv iron","iron deficit","dose calculation"],
  // ICP / obstetric cholestasis
  "icp": ["intrahepatic cholestasis","obstetric cholestasis","bile acids","pruritus","itch","udca"],
  "cholestasis": ["icp","intrahepatic cholestasis","bile acids","pruritus","itch","obstetric cholestasis"],
  "obstetric cholestasis": ["icp","intrahepatic cholestasis","bile acids","pruritus","itch"],
  "itching": ["icp","pruritus","bile acids","obstetric cholestasis","antihistamine"],
  "itch": ["icp","pruritus","bile acids","cholestasis","antihistamine","aqueous cream"],
  "pruritus": ["icp","itching","bile acids","cholestasis","antihistamine"],
  "bile acids": ["icp","cholestasis","udca","intrahepatic cholestasis","pruritus"],
  "udca": ["ursodeoxycholic acid","icp","cholestasis","bile acids"],
  "ursodeoxycholic": ["udca","icp","cholestasis","bile acids"],
  // VTE / DVT / PE
  "vte": ["venous thromboembolism","dvt","pe","pulmonary embolism","deep vein thrombosis","lmwh","enoxaparin","thromboprophylaxis"],
  "dvt": ["deep vein thrombosis","vte","lmwh","enoxaparin","thrombosis","thromboembolism"],
  "pulmonary embolism": ["pe","vte","lmwh","enoxaparin","thromboembolism","dvt"],
  "deep vein thrombosis": ["dvt","vte","lmwh","enoxaparin","thrombosis"],
  "clot": ["dvt","pe","vte","thrombosis","lmwh","enoxaparin"],
  "blood clot": ["dvt","pe","vte","thrombosis","lmwh","enoxaparin"],
  "enoxaparin": ["lmwh","heparin","vte","thromboprophylaxis","anti-xa","inhixa"],
  "lmwh": ["enoxaparin","heparin","vte","thromboprophylaxis","inhixa","low molecular weight"],
  "thromboprophylaxis": ["vte","lmwh","enoxaparin","dvt","pe","thromboembolism"],
  "anticoagulation": ["lmwh","enoxaparin","vte","heparin","therapeutic","prophylactic"],
  "heparin": ["lmwh","enoxaparin","vte","thromboprophylaxis","anti-xa"],
  "anti-xa": ["enoxaparin","lmwh","therapeutic","monitoring","anti xa"],
  "thrombophilia": ["antithrombin","protein c","protein s","antiphospholipid","aps","vte","lmwh"],
  // Diabetes
  "diabetes": ["gdm","gestational diabetes","type 1","type 2","insulin","dka","hba1c","glucose","vrii"],
  "gdm": ["gestational diabetes","ogtt","glucose","insulin","diabetes in pregnancy","hba1c"],
  "gestational diabetes": ["gdm","ogtt","glucose","insulin","diabetes in pregnancy","hba1c"],
  "dka": ["diabetic ketoacidosis","ketones","insulin","vrii","frii","acidosis","emergency"],
  "diabetic ketoacidosis": ["dka","ketones","insulin","vrii","frii","acidosis"],
  "insulin": ["diabetes","type 1","dka","vrii","frii","gdm","glucose","hba1c"],
  "vrii": ["variable rate insulin infusion","insulin","diabetes","sliding scale","glucose","dka"],
  "sliding scale": ["vrii","variable rate insulin infusion","insulin","diabetes"],
  "hba1c": ["diabetes","gdm","glucose","insulin","type 1","type 2"],
  "ketones": ["dka","diabetic ketoacidosis","diabetes","insulin","vrii","acidosis"],
  "ogtt": ["oral glucose tolerance test","gdm","gestational diabetes","glucose"],
  "glucose": ["diabetes","gdm","dka","insulin","vrii","blood sugar","cbg"],
  "blood sugar": ["glucose","diabetes","gdm","dka","insulin","cbg"],
  "type 1 diabetes": ["type 1","diabetes","insulin","dka","vrii","cgm","hba1c"],
  "type 2 diabetes": ["type 2","diabetes","metformin","insulin","gdm","hba1c"],
  // Multiple pregnancy / twins / triplets
  "twins": ["twin pregnancy","multiple pregnancy","monochorionic","dichorionic","mcda","dcda","mcma"],
  "twin": ["twin pregnancy","multiple pregnancy","monochorionic","dichorionic"],
  "triplets": ["triplet pregnancy","multiple pregnancy","trichorionic","monochorionic"],
  "triplet": ["triplet pregnancy","multiple pregnancy","trichorionic"],
  "multiple pregnancy": ["twins","triplets","twin pregnancy","triplet pregnancy","monochorionic","dichorionic"],
  "chorionicity": ["monochorionic","dichorionic","trichorionic","shared placenta","lambda sign","t-sign","chorionicity"],
  "amnionicity": ["monoamniotic","diamniotic","triamniotic","amniotic sac"],
  "monochorionic": ["mc","mcda","mcma","shared placenta","twin to twin transfusion","ttts","ffts"],
  "dichorionic": ["dc","dcda","dcta","twin pregnancy","triplet"],
  "mcda": ["monochorionic diamniotic","monochorionic","twins","ttts","ffts","fetal monitoring"],
  "mcma": ["monochorionic monoamniotic","monochorionic","twins","higher risk","tertiary referral"],
  "dcda": ["dichorionic diamniotic","dichorionic","twins"],
  "ttts": ["twin to twin transfusion","twin-to-twin transfusion","feto-fetal transfusion","ffts","monochorionic","laser ablation"],
  "ffts": ["feto-fetal transfusion syndrome","twin to twin transfusion","ttts","monochorionic"],
  "twin to twin transfusion": ["ttts","ffts","feto-fetal transfusion","monochorionic","laser ablation","tertiary referral"],
  "taps": ["twin anaemia polycythaemia sequence","twin anemia polycythemia","monochorionic","tertiary referral"],
  "trap": ["twin reverse arterial perfusion","acardiac twin","monochorionic","tertiary referral"],
  "fetal weight discordance": ["weight discordance","growth discordance","fgr","iugr","25%","fetal growth restriction"],
  "weight discordance": ["fetal weight discordance","fgr","iugr","biometry","ultrasound"],
  "laser ablation": ["fetoscopic laser","ttts","ffts","monochorionic","tertiary referral","fetal medicine"],
  "fetal medicine": ["fmc","tertiary referral","fetal medicine centre","ttts","laser ablation"],
  "birth plan": ["delivery plan","mode of delivery","mode of birth","caesarean","vaginal birth","twins","28 weeks"],
  "twin clinic": ["multiple pregnancy","mdt","specialist obstetrician","specialist midwife"],
  // Antenatal care / QS22
  "booking": ["booking appointment","antenatal booking","10 weeks","first appointment","antenatal care"],
  "booking appointment": ["booking","antenatal booking","10 weeks","first antenatal","risk assessment"],
  "antenatal care": ["booking","appointments","antenatal","midwife","risk assessment","qs22"],
  "antenatal appointments": ["appointment schedule","booking","nulliparous","multiparous","antenatal care"],
  "nulliparous": ["first pregnancy","primiparous","10 appointments","nulliparous schedule","primigravida"],
  "multiparous": ["previous birth","multipara","7 appointments","multiparous schedule","multigravida"],
  "continuity of carer": ["named midwife","small team","midwife team","continuity of care","caseload midwifery"],
  "named midwife": ["continuity of carer","midwife team","small team","antenatal care"],
  "flu vaccine": ["influenza vaccine","flu jab","flu in pregnancy","vaccines pregnancy"],
  "whooping cough": ["pertussis","pertussis vaccine","tdap","whooping cough vaccine","vaccines pregnancy"],
  "pertussis": ["whooping cough","pertussis vaccine","tdap","whooping cough vaccine"],
  "carbon monoxide": ["co test","co testing","smoking","4 ppm","opt-out referral","stop smoking"],
  "co test": ["carbon monoxide","co monitor","smoking","4 ppm","stop smoking service","opt-out"],
  "smoking": ["carbon monoxide","co test","stop smoking","opt-out referral","tobacco","cigarette"],
  "stop smoking": ["smoking cessation","carbon monoxide","co test","opt-out referral","sss"],
  "opt-out referral": ["stop smoking","carbon monoxide","co test","smoking referral","sss"],
  "foods to avoid": ["food safety","listeria","raw meat","liver","soft cheese","sushi","shellfish","food in pregnancy"],
  "food safety pregnancy": ["foods to avoid","listeria","raw meat","liver","soft cheese","food safety","nutrition"],
  "listeria": ["listeriosis","soft cheese","pate","deli meat","foods to avoid","food safety pregnancy"],
  "soft cheese": ["listeria","brie","camembert","stilton","foods to avoid","food safety"],
  "folic acid": ["folate","supplements pregnancy","neural tube defect","400 micrograms","5mg folic acid"],
  "vitamin d": ["supplements pregnancy","vitamin d in pregnancy","10 micrograms","folic acid"],
  "complex social factors": ["substance misuse","domestic abuse","homelessness","immigration","booking","vulnerable"],
  "domestic abuse": ["intimate partner violence","safeguarding","complex social factors","booking","domestic violence"],
  "late booking": ["late presenter","booking","10 weeks","self-referral","antenatal care"],
  "self referral": ["self-referral","late booking","booking","antenatal care","maternity services"],
  "sfh": ["symphysis fundal height","fundal height","growth","fgr","small for dates"],
  "symphysis fundal height": ["sfh","fundal height","growth","fgr","small for dates"],
  "membrane sweep": ["sweep","40 weeks","41 weeks","induction of labour","overdue"],
  // Reduced fetal movements / GTG57
  "rfm": ["reduced fetal movements","decreased fetal movements","fetal movements","baby not moving","baby moving less"],
  "reduced fetal movements": ["rfm","decreased fetal movements","baby not moving","fetal movement","stillbirth risk"],
  "decreased fetal movements": ["rfm","reduced fetal movements","baby not moving","fetal activity"],
  "baby not moving": ["rfm","reduced fetal movements","decreased fetal movements","fetal death"],
  "baby moving less": ["rfm","reduced fetal movements","fetal movements","fetal wellbeing"],
  "fetal movements": ["rfm","reduced fetal movements","fetal activity","fetal wellbeing","movement pattern"],
  "kick counting": ["fetal movement counting","rfm","fetal movements","10 movements","count to ten"],
  "fetal movement counting": ["kick counting","rfm","reduced fetal movements","fetal wellbeing"],
  "iufd": ["intrauterine fetal death","stillbirth","rfm","fetal death","baby died"],
  "stillbirth": ["iufd","fetal death","rfm","reduced fetal movements","stillbirth risk"],
  "fetal death": ["iufd","stillbirth","rfm","reduced fetal movements"],
  "fetal compromise": ["rfm","ctg","fetal distress","fetal wellbeing","acute compromise"],
  "ctg rfm": ["cardiotocograph","fetal monitoring","reactive ctg","rfm","fetal wellbeing"],
  "reactive ctg": ["normal ctg","fhr accelerations","fetal wellbeing","ctg rfm"],
  "sinusoidal ctg": ["sinusoidal trace","fmh","fetomaternal haemorrhage","fetal anaemia","rfm"],
  "fetal anaemia": ["fmh","fetomaternal haemorrhage","mca doppler","kleihauer","sinusoidal ctg"],
  "fetomaternal haemorrhage": ["fmh","kleihauer","mca doppler","fetal anaemia","sinusoidal"],
  "kleihauer": ["kleihauer betke","fmh","fetomaternal haemorrhage","fetal anaemia"],
  "oligohydramnios": ["reduced liquor","amniotic fluid","rfm","fgr","sga","uss rfm"],
  "liquor": ["amniotic fluid","oligohydramnios","deepest vertical pocket","uss rfm"],
  "sga": ["small for gestational age","fgr","iugr","rfm","efw below 10th centile","growth restriction"],
  "small for gestational age": ["sga","fgr","iugr","rfm","growth restriction","efw"],
  "fgr": ["fetal growth restriction","sga","iugr","rfm","placental insufficiency","small for dates"],
  "fetal growth restriction": ["fgr","sga","iugr","rfm","placental insufficiency","umbilical artery doppler"],
  "placental insufficiency": ["fgr","sga","rfm","stillbirth","umbilical artery doppler","placental dysfunction"],
  "umbilical artery doppler": ["uad","doppler rfm","fgr","sga","rfm","absent end diastolic flow","aedf"],
  "absent end diastolic flow": ["aedf","reversed flow","umbilical artery doppler","fgr","severe fgr"],
  "cpr": ["cerebroplacental ratio","rfm","mca doppler","umbilical artery doppler","fetal wellbeing"],
  "cerebroplacental ratio": ["cpr","mca pi","umbilical artery doppler","rfm","fetal wellbeing"],
  "mca doppler": ["middle cerebral artery","cpr","fetal anaemia","rfm","fmh"],
  "recurrent rfm": ["recurrent reduced fetal movements","repeated rfm","multiple rfm","rfm twice"],
  "excessive fetal movements": ["increased fetal movements","frantic movements","violent movements","rfm","stillbirth"],
  "anterior placenta rfm": ["anterior placenta","reduced movements","perception","rfm"],
  "biophysical profile": ["bpp","fetal wellbeing","rfm","amniotic fluid","fetal tone"],
};
