export const BASHH_PID_SECTIONS = [
  {
    id: "bashh-pid-overview",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Overview & Aetiology",
    title: "PID — Overview & Aetiology",
    tags: ["pelvic inflammatory disease", "PID", "chlamydia", "gonorrhoea", "mycoplasma genitalium", "anaerobes", "STI", "salpingitis", "endometritis", "oophoritis"],
    content: [
      { type: "subheading", value: "Definition" },
      { type: "text", value: "Pelvic inflammatory disease (PID) is an infection of the upper female genital tract — the uterus, fallopian tubes, and ovaries. It is a clinical diagnosis. PID encompasses endometritis, salpingitis, oophoritis, and tubo-ovarian abscess." },
      { type: "subheading", value: "Causative Organisms" },
      { type: "list", items: [
        "Chlamydia trachomatis — most commonly isolated organism in UK",
        "Neisseria gonorrhoeae — associated with more severe disease; must always be covered empirically",
        "Mycoplasma genitalium — increasingly recognised; poor coverage with standard regimens",
        "Anaerobes and BV-associated organisms (Gardnerella, Prevotella spp.) — particularly important in severe disease and TOA",
        "No causative organism is identified in approximately 50% of cases",
      ]},
      { type: "subheading", value: "Epidemiology" },
      { type: "list", items: [
        "Predominantly affects sexually active women under 25 years of age",
        "Risk factors: multiple sexual partners, recent new partner, previous STI, IUD insertion within the past 6 weeks",
        "IUD does NOT increase long-term risk — risk is limited to the first 6 weeks after insertion",
        "Incidence is highest in low-income and urban populations",
      ]},
      { type: "alert", value: "A low threshold for empirical treatment is recommended — the consequences of untreated PID (infertility, ectopic pregnancy, chronic pelvic pain) are severe and risk increases with delayed treatment." },
    ],
  },
  {
    id: "bashh-pid-diagnosis",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Diagnosis",
    title: "PID — Diagnosis & Clinical Criteria",
    tags: ["diagnosis", "minimum criteria", "lower abdominal pain", "pelvic tenderness", "cervical motion tenderness", "adnexal tenderness", "uterine tenderness", "clinical diagnosis", "empirical treatment"],
    flowchartId: "BASHH_PID_TRIAGE",
    content: [
      { type: "subheading", value: "Minimum Criteria for Empirical Treatment" },
      { type: "text", value: "PID is a clinical diagnosis. Empirical treatment is recommended when ALL of the following are present:" },
      { type: "list", items: [
        "Lower abdominal or pelvic pain",
        "Pelvic tenderness on bimanual examination: uterine tenderness AND/OR adnexal tenderness AND/OR cervical motion tenderness",
        "No other cause for the symptoms has been identified",
      ]},
      { type: "alert", value: "Do not delay treatment awaiting laboratory results — start antibiotics once minimum criteria are met and ectopic pregnancy has been excluded." },
      { type: "subheading", value: "Additional Features Supporting Diagnosis" },
      { type: "list", items: [
        "Temperature >38°C",
        "Elevated CRP, ESR, or white cell count",
        "Mucopurulent cervicitis or abnormal vaginal discharge",
        "Positive NAAT for Chlamydia trachomatis, Neisseria gonorrhoeae, or Mycoplasma genitalium",
        "Endometrial biopsy showing plasma cell endometritis (histological diagnosis)",
        "Laparoscopic evidence: inflamed, oedematous fallopian tubes ± peritoneal exudate",
      ]},
      { type: "subheading", value: "Important Differential Diagnoses to Exclude" },
      { type: "list", items: [
        "Ectopic pregnancy — exclude with urine pregnancy test in ALL women; if positive, manage as potentially ectopic",
        "Appendicitis — if right iliac fossa tenderness predominates; low threshold for surgical review",
        "Ovarian cyst complication (torsion, rupture, haemorrhage)",
        "Urinary tract infection — dipstick urine",
        "Irritable bowel syndrome / functional pain",
      ]},
    ],
  },
  {
    id: "bashh-pid-investigations",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Investigations",
    title: "PID — Investigations",
    tags: ["investigations", "NAAT", "swab", "chlamydia", "gonorrhoea", "mycoplasma genitalium", "HVS", "pregnancy test", "CRP", "FBC", "pelvic ultrasound", "endocervical"],
    content: [
      { type: "subheading", value: "Essential Investigations" },
      { type: "list", items: [
        "Urine or blood pregnancy test — MUST be performed before treatment to exclude ectopic pregnancy",
        "Endocervical or vulvovaginal NAAT for Chlamydia trachomatis and Neisseria gonorrhoeae",
        "Endocervical or vulvovaginal NAAT for Mycoplasma genitalium — send alongside CT/NG swab",
        "High vaginal swab (HVS) for microscopy, culture, and sensitivity — identify BV and candida",
      ]},
      { type: "subheading", value: "Blood Tests" },
      { type: "list", items: [
        "FBC — leukocytosis supports diagnosis",
        "CRP and/or ESR — elevated in most PID cases",
        "LFTs and U&Es if admission or IV antibiotics anticipated",
        "Blood cultures if systemically unwell or pyrexia >38.5°C",
      ]},
      { type: "subheading", value: "Imaging" },
      { type: "list", items: [
        "Pelvic ultrasound (transvaginal or transabdominal): indicated if TOA suspected, pelvic mass palpated, or symptoms severe",
        "CT pelvis: if USS inconclusive or TOA drainage being considered",
        "USS is normal in many women with PID — a normal scan does NOT exclude the diagnosis",
      ]},
      { type: "subheading", value: "Routine Offer" },
      { type: "list", items: [
        "HIV test — offer to all as per standard sexual health screen",
        "Syphilis serology",
        "Hepatitis B and C testing (if not previously tested)",
      ]},
      { type: "alert", value: "Send NAAT for Mycoplasma genitalium before starting antibiotics — fluoroquinolone resistance testing (macrolide resistance-associated mutations) should be requested where available, as it guides whether moxifloxacin is appropriate." },
    ],
  },
  {
    id: "bashh-pid-severity",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Severity Assessment",
    title: "PID — Severity Assessment",
    tags: ["severity", "mild", "moderate", "severe", "outpatient", "inpatient", "admission criteria", "tubo-ovarian abscess", "peritonism", "fever"],
    flowchartId: "BASHH_PID_TRIAGE",
    content: [
      { type: "subheading", value: "Severity Grading" },
      { type: "table", headers: ["Severity", "Features", "Management Setting"], rows: [
        ["Mild", "Pelvic tenderness only; no systemic features; no peritonism; no TOA", "Outpatient oral antibiotics"],
        ["Moderate", "Systemic features (fever >38°C, elevated CRP/WBC); no peritonism or TOA", "Outpatient oral antibiotics with 72-hour review; consider admission"],
        ["Severe", "Signs of pelvic peritonitis, TOA, systemically very unwell, failure of oral therapy, unable to exclude surgical emergency", "Admit for IV antibiotics"],
      ]},
      { type: "subheading", value: "Indications for Admission and IV Antibiotics" },
      { type: "list", items: [
        "Severe PID with peritonism or systemic sepsis",
        "Tubo-ovarian abscess confirmed or suspected on examination or imaging",
        "Surgical emergency (appendicitis, ectopic) cannot be excluded",
        "Pregnancy",
        "Failure to respond to oral antibiotic therapy (no improvement at 72-hour review)",
        "Inability to tolerate oral medication (severe nausea, vomiting)",
        "Patient unable to adhere to or access outpatient treatment",
      ]},
      { type: "alert", value: "Outpatient treatment is as effective as inpatient treatment for mild to moderate PID (Grade 1A). However, the clinical threshold for admission should be low — when in doubt, admit." },
    ],
  },
  {
    id: "bashh-pid-outpatient",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Outpatient Treatment",
    title: "PID — Outpatient Antibiotic Regimens (Mild–Moderate)",
    tags: ["outpatient", "antibiotics", "ceftriaxone", "doxycycline", "metronidazole", "ofloxacin", "moxifloxacin", "14 days", "oral", "IM", "mild", "moderate"],
    flowchartId: "BASHH_PID_ANTIBIOTICS",
    content: [
      { type: "subheading", value: "Regimen A — Preferred (covers gonorrhoea)" },
      { type: "list", items: [
        "IM ceftriaxone 1g — single dose STAT",
        "PLUS oral doxycycline 100mg twice daily for 14 days",
        "PLUS oral metronidazole 400mg twice daily for 14 days",
        "Metronidazole may be omitted in mild disease if not tolerated (anaerobes less critical in mild PID)",
      ]},
      { type: "subheading", value: "Regimen B — Alternative (if gonorrhoea risk low)" },
      { type: "list", items: [
        "Oral ofloxacin 400mg twice daily for 14 days",
        "PLUS oral metronidazole 400mg twice daily for 14 days",
        "AVOID if high gonorrhoea risk: partner known to have gonorrhoea, sexual contact abroad, clinically severe disease",
      ]},
      { type: "subheading", value: "Regimen C — Mycoplasma genitalium positive or suspected" },
      { type: "list", items: [
        "Oral moxifloxacin 400mg once daily for 14 days",
        "Moxifloxacin provides the best M. genitalium coverage of all three regimens",
        "AVOID if high gonorrhoea risk — fluoroquinolone resistance in gonorrhoea is high",
        "MHRA 2019: fluoroquinolones are associated with disabling and potentially permanent side effects (tendinitis, peripheral neuropathy) — prescribe only when benefit outweighs risk",
      ]},
      { type: "alert", value: "Gonorrhoea risk is HIGH if: the patient's partner is known to have gonorrhoea, recent sexual contact abroad, or this is a clinically severe presentation. In these cases use Regimen A (ceftriaxone-based) only." },
      { type: "subheading", value: "Fluoroquinolone Safety (MHRA 2019 Update)" },
      { type: "list", items: [
        "Ofloxacin and moxifloxacin are fluoroquinolones — subject to MHRA 2019 restriction",
        "Associated with disabling, potentially permanent adverse effects: tendinitis, tendon rupture, peripheral neuropathy, CNS effects",
        "Avoid in patients >60 years, renal impairment, concurrent corticosteroid use, or previous fluoroquinolone adverse reaction",
        "Prescribe only when no suitable alternative is available",
      ]},
    ],
  },
  {
    id: "bashh-pid-inpatient",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Inpatient Treatment",
    title: "PID — Inpatient IV Antibiotic Regimens (Severe / TOA)",
    tags: ["inpatient", "IV", "cefoxitin", "clindamycin", "gentamicin", "doxycycline", "metronidazole", "ofloxacin", "IV to oral", "step down", "severe", "TOA", "admission"],
    flowchartId: "BASHH_PID_ANTIBIOTICS",
    content: [
      { type: "alert", value: "Continue IV antibiotics until 24 hours after clinical improvement (fever resolved, pain improving), then switch to oral step-down to complete 14 days total." },
      { type: "subheading", value: "Regimen A — Preferred" },
      { type: "list", items: [
        "IV cefoxitin 2g every 6 hours",
        "PLUS IV or oral doxycycline 100mg twice daily",
        "Step-down (oral, to complete 14 days): oral doxycycline 100mg BD + oral metronidazole 400mg BD",
        "Note: cefoxitin may not be available in all UK centres — discuss with microbiology if unavailable",
      ]},
      { type: "subheading", value: "Regimen B — Alternative" },
      { type: "list", items: [
        "IV clindamycin 900mg every 8 hours",
        "PLUS IV gentamicin: loading dose 2mg/kg, then 1.5mg/kg every 8 hours (or 3–5mg/kg once daily)",
        "Step-down option 1 (to complete 14 days): oral clindamycin 450mg four times daily",
        "Step-down option 2 (to complete 14 days): oral doxycycline 100mg BD + oral metronidazole 400mg BD",
      ]},
      { type: "subheading", value: "Alternative IV Regimen (if above not available)" },
      { type: "list", items: [
        "IV ofloxacin 400mg twice daily",
        "PLUS IV metronidazole 500mg three times daily",
        "AVOID if high gonorrhoea risk — fluoroquinolone resistance",
        "MHRA 2019 fluoroquinolone restrictions apply — see outpatient section",
      ]},
      { type: "subheading", value: "Monitoring During IV Therapy" },
      { type: "list", items: [
        "Observations every 4 hours: temperature, pulse, BP, RR",
        "If using gentamicin: check renal function before each dose; trough level <1 mg/L before next dose in prolonged courses",
        "Reassess at 24 hours — if no improvement, USS to exclude TOA or change in diagnosis",
        "Blood cultures if not already taken in febrile patients",
      ]},
    ],
  },
  {
    id: "bashh-pid-toa",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Tubo-ovarian Abscess",
    title: "PID — Tubo-ovarian Abscess (TOA)",
    tags: ["tubo-ovarian abscess", "TOA", "abscess", "ultrasound", "drainage", "surgical", "laparoscopy", "aspiration", "pelvic mass", "failed antibiotics"],
    content: [
      { type: "subheading", value: "Recognition" },
      { type: "list", items: [
        "TOA: collection of pus in the tube, ovary, or surrounding tissue",
        "Suspect if: pelvic mass on bimanual examination, USS demonstrating complex adnexal mass, failure to respond to outpatient antibiotics",
        "All TOA patients should be admitted for IV antibiotics",
        "Always confirm with pelvic USS (transvaginal preferable)",
      ]},
      { type: "subheading", value: "Management" },
      { type: "list", items: [
        "Admit and start IV antibiotics (Inpatient Regimen A or B — see above)",
        "USS or CT imaging to characterise the collection",
        "Reassess after 48–72 hours of IV antibiotics",
      ]},
      { type: "subheading", value: "If No Response to IV Antibiotics at 48–72 hours" },
      { type: "list", items: [
        "Consider image-guided (ultrasound or CT-guided) aspiration or drainage — first-line intervention",
        "Percutaneous or transvaginal drainage is associated with high success rates and better fertility preservation than surgery",
        "Continue IV antibiotics alongside drainage",
      ]},
      { type: "subheading", value: "Surgical Indications" },
      { type: "list", items: [
        "Suspected rupture of TOA — surgical emergency (laparotomy)",
        "Clinical deterioration or septic shock despite IV antibiotics and drainage",
        "Failure of image-guided drainage",
        "Laparoscopy is preferred over laparotomy where feasible",
      ]},
      { type: "alert", value: "Ruptured TOA is a surgical emergency. Signs: acute deterioration, guarding, rigidity, haemodynamic instability — urgent surgical review is required." },
    ],
  },
  {
    id: "bashh-pid-iud",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "IUD Management",
    title: "PID — IUD Management",
    tags: ["IUD", "intrauterine device", "coil", "removal", "contraception", "levonorgestrel", "copper", "IUCD"],
    content: [
      { type: "subheading", value: "Evidence on IUD Removal" },
      { type: "text", value: "Current evidence does not support routine removal of an IUD in women who develop PID. In clinical trials, removal of the IUD did not significantly improve clinical outcomes in most women." },
      { type: "subheading", value: "Recommended Approach" },
      { type: "list", items: [
        "Do NOT routinely remove the IUD at presentation of PID",
        "Start antibiotics as normal and assess clinical response",
        "Review at 72 hours — if no clinical improvement, consider IUD removal",
        "IUD removal may be considered earlier in severe PID with TOA",
        "Discuss the decision with the patient including the risk of unintended pregnancy if removed",
      ]},
      { type: "subheading", value: "Contraception After IUD Removal" },
      { type: "list", items: [
        "If IUD is removed: advise on alternative contraception immediately",
        "If sexual intercourse in the past 5 days: consider emergency contraception",
        "Discuss long-acting reversible contraception (LARC) at follow-up once treatment complete",
      ]},
      { type: "alert", value: "Always discuss with the patient before removing the IUD — removal removes protection against pregnancy and requires immediate alternative contraception." },
    ],
  },
  {
    id: "bashh-pid-contacts",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Sexual Contacts",
    title: "PID — Sexual Contact Management",
    tags: ["sexual contacts", "partner notification", "partner testing", "partner treatment", "expedited partner therapy", "EPT", "GUM", "contact tracing", "6 months"],
    content: [
      { type: "subheading", value: "Who Should Be Contacted?" },
      { type: "list", items: [
        "All sexual partners within the previous 6 months should be offered testing and treatment",
        "If the patient has had no sexual contact in the past 6 months: the most recent partner should be contacted",
        "The index patient should be advised not to have sexual intercourse until both she and her partner(s) have completed treatment",
      ]},
      { type: "subheading", value: "What Should Partners Be Offered?" },
      { type: "list", items: [
        "Screening for STIs including chlamydia and gonorrhoea (NAAT)",
        "Epidemiological (empirical) treatment without waiting for results — treat for chlamydia and gonorrhoea",
        "Consider testing for M. genitalium if index patient is positive",
        "Referral to GUM/sexual health clinic for full STI screen",
      ]},
      { type: "subheading", value: "Expedited Partner Therapy (EPT)" },
      { type: "list", items: [
        "EPT: providing medication or a prescription to the index patient to give to their partner without that partner attending a clinic",
        "EPT should be considered where the partner is unable or unwilling to attend a clinic",
        "Provide written information for the partner about the diagnosis and treatment",
        "EPT does not replace partner attendance at a sexual health clinic — encourage referral alongside EPT",
      ]},
      { type: "subheading", value: "Referral to GUM/Sexual Health" },
      { type: "list", items: [
        "All women with PID should ideally be reviewed by or referred to a sexual health/GUM clinic",
        "GUM clinic provides: full STI screen, contact tracing support, partner notification services, repeat testing",
        "Refer urgently if gonorrhoea confirmed — culture and sensitivity needed given rising quinolone resistance",
      ]},
    ],
  },
  {
    id: "bashh-pid-followup",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Follow-up",
    title: "PID — Follow-up Protocol",
    tags: ["follow-up", "72 hours", "review", "test of cure", "TOC", "gonorrhoea", "mycoplasma genitalium", "MGen", "treatment failure", "re-assessment", "4 weeks"],
    content: [
      { type: "subheading", value: "72-Hour Review (All Patients)" },
      { type: "list", items: [
        "Review all patients at 72 hours — particularly those with moderate disease and all outpatients",
        "If clinical improvement: continue current antibiotics to complete 14-day course",
        "Assess: pain, fever, tenderness — improvement is expected in most within 72 hours",
      ]},
      { type: "subheading", value: "If No Improvement at 72 Hours" },
      { type: "list", items: [
        "Reconsider the diagnosis — is there a TOA? Is this appendicitis? Alternative diagnosis?",
        "USS pelvis if not already performed",
        "Consider admission for IV antibiotics if still outpatient",
        "Consider laparoscopy to confirm diagnosis and exclude surgical emergency",
        "Review microbiology results — if gonorrhoea isolated, check sensitivity and adjust accordingly",
      ]},
      { type: "subheading", value: "4-Week Review" },
      { type: "list", items: [
        "All patients should be reviewed by 4 weeks",
        "Ensure antibiotic course completed",
        "Review all microbiological results",
        "Assess for persistent symptoms or complications",
        "Discuss contraception and STI prevention (barrier methods)",
      ]},
      { type: "subheading", value: "Test of Cure" },
      { type: "list", items: [
        "Gonorrhoea positive: repeat culture at 2 weeks post-treatment to confirm eradication",
        "M. genitalium positive: repeat NAAT at 5 weeks (earlier if symptoms persist)",
        "Chlamydia: routine TOC not required in non-pregnant women unless symptoms persist or re-exposure risk",
      ]},
      { type: "alert", value: "Gonorrhoea culture and sensitivity MUST be performed if gonorrhoea is identified — quinolone resistance is high and culture-guided treatment is essential to avoid treatment failure." },
    ],
  },
  {
    id: "bashh-pid-fhc",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Fitz-Hugh-Curtis Syndrome",
    title: "PID — Fitz-Hugh-Curtis Syndrome (Perihepatitis)",
    tags: ["Fitz-Hugh-Curtis", "perihepatitis", "right upper quadrant", "RUQ", "liver capsule", "adhesions", "pleuritic", "chlamydia", "gonococcal"],
    content: [
      { type: "subheading", value: "Definition" },
      { type: "text", value: "Fitz-Hugh-Curtis syndrome is perihepatitis associated with ascending pelvic infection. It involves inflammation of the liver capsule (Glisson's capsule) and the formation of 'violin string' adhesions between the liver capsule and the anterior abdominal wall." },
      { type: "subheading", value: "Clinical Features" },
      { type: "list", items: [
        "Right upper quadrant or right-sided pleuritic pain — can be the dominant or presenting symptom",
        "May mimic cholecystitis, pleuritis, or pulmonary embolism",
        "Usually occurs alongside or following pelvic symptoms of PID",
        "Associated particularly with Chlamydia trachomatis and Neisseria gonorrhoeae",
        "Liver function tests are typically normal",
      ]},
      { type: "subheading", value: "Diagnosis" },
      { type: "list", items: [
        "Clinical diagnosis when RUQ pain occurs in context of PID",
        "Laparoscopy shows characteristic 'violin string' fibrinous adhesions between liver capsule and anterior abdominal wall",
        "USS: may show free fluid adjacent to liver; no gallstones or biliary dilation",
      ]},
      { type: "subheading", value: "Treatment" },
      { type: "list", items: [
        "Treat the underlying PID with standard antibiotic regimens (see outpatient or inpatient sections)",
        "No specific additional treatment is required for the perihepatitis itself",
        "Adhesions: established adhesions causing chronic pain may require laparoscopic adhesiolysis",
      ]},
    ],
  },
  {
    id: "bashh-pid-special",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Special Circumstances",
    title: "PID — Pregnancy, HIV & Adolescents",
    tags: ["pregnancy", "pregnant", "HIV", "adolescent", "young person", "safeguarding", "IV antibiotics", "ceftriaxone", "erythromycin", "special populations"],
    content: [
      { type: "subheading", value: "PID in Pregnancy" },
      { type: "list", items: [
        "PID in pregnancy is uncommon (ascending infection is limited by mucus plug from 12 weeks) but is associated with significant morbidity",
        "Complications: miscarriage, preterm labour and birth, intrauterine fetal death, maternal sepsis",
        "ALL women with PID in pregnancy should be admitted for IV antibiotics",
        "Consult genitourinary medicine and obstetric physicians",
        "Recommended regimen: IV ceftriaxone 1g once daily PLUS IV azithromycin 500mg once daily PLUS IV metronidazole 500mg three times daily — switch to oral on improvement to complete 14 days",
        "AVOID doxycycline, ofloxacin, and moxifloxacin in pregnancy",
        "Erythromycin may be used as alternative to azithromycin if azithromycin not available",
      ]},
      { type: "subheading", value: "PID and HIV" },
      { type: "list", items: [
        "Women with HIV are at higher risk of TOA and more severe disease",
        "Response to standard antibiotic regimens is generally good",
        "Lower threshold for inpatient treatment in moderate PID",
        "Same antibiotic regimens as HIV-negative women; broaden cover as clinically indicated",
      ]},
      { type: "subheading", value: "PID in Adolescents" },
      { type: "list", items: [
        "Adolescents are at higher risk of PID and more severe disease",
        "Consider lower threshold for inpatient treatment in under-18s",
        "Same antibiotic regimens apply",
        "Safeguarding: consider safeguarding implications if patient is under 16 years",
        "Confidentiality: maintain confidentiality unless safeguarding concern is identified",
        "Ensure access to sexual health services and long-term contraception advice",
      ]},
    ],
  },
  {
    id: "bashh-pid-sequelae",
    gl: "BASHH_PID",
    condition: "Pelvic Inflammatory Disease",
    setting: "Long-term Sequelae",
    title: "PID — Long-term Complications",
    tags: ["sequelae", "infertility", "ectopic", "chronic pelvic pain", "recurrence", "long-term", "fertility", "complications", "tubal factor"],
    content: [
      { type: "subheading", value: "Overview" },
      { type: "text", value: "PID has significant long-term consequences for reproductive health. Risk of sequelae increases substantially with each episode and with delayed or inadequate treatment. Early empirical treatment is the most effective strategy for reducing long-term harm." },
      { type: "subheading", value: "Infertility" },
      { type: "list", items: [
        "Caused by tubal scarring and occlusion following fallopian tube inflammation",
        "After first episode: ~10–15% of women develop tubal factor infertility",
        "After second episode: ~25–35%",
        "After third or more episodes: ~50–60%",
        "Risk is higher with more severe disease, delayed treatment, and gonococcal or chlamydial infection",
      ]},
      { type: "subheading", value: "Ectopic Pregnancy" },
      { type: "list", items: [
        "Risk of ectopic pregnancy increased 6–10-fold following PID",
        "Caused by impaired tubal motility and partial tubal obstruction",
        "Even mild or subclinical PID increases ectopic risk",
      ]},
      { type: "subheading", value: "Chronic Pelvic Pain" },
      { type: "list", items: [
        "Affects approximately 20% of women after one episode of PID",
        "Results from pelvic adhesions and ongoing inflammation",
        "Risk increases with repeated episodes",
      ]},
      { type: "subheading", value: "Recurrent PID" },
      { type: "list", items: [
        "20–25% of women develop recurrent PID",
        "Risk factors: ongoing STI exposure, inadequate treatment of contacts, failure to use barrier contraception",
        "Each recurrence dramatically increases the risk of infertility and chronic pain",
      ]},
      { type: "alert", value: "Counsel all women about the long-term risks of PID and the importance of: completing the full antibiotic course, partner treatment, STI screening, consistent condom use, and attending follow-up." },
    ],
  },
];
