export const GL983_SECTIONS = [
  {
    id: "dm-preexisting-antenatal", gl: "GL983", condition: "Diabetes in Pregnancy", setting: "Pre-existing T1/T2 — Antenatal",
    title: "Pre-existing Diabetes — Antenatal Management",
    tags: ["diabetes","type 1","type 2","t1dm","t2dm","pre-existing diabetes","dsm","diabetes specialist midwife","hba1c","folic acid 5mg","aspirin 150mg","ace inhibitor","arb","statin","cgm","libre","ketone monitor","retinal screening","blood glucose targets","fasting 5.3","5.3 mmol","7.8 mmol","6.4 mmol","glucose monitoring","viability scan","growth scan","22 weeks","28 weeks","36 weeks","renal","creatinine","pcr","booking bloods","free style libre","macrosomia","shoulder dystocia","stillbirth","fetal growth","neonatal unit"],
    content: [
      { type: "subheading", value: "Referral & MDT" },
      { type: "list", items: [
        "GP/CMW to refer women to Diabetes Specialist Midwives (DSM) as soon as pregnancy is confirmed",
        "DSM remains first point of contact throughout pregnancy and after delivery",
        "Women seen in MDT clinic (Consultant Obstetrician + Consultant Endocrinologist + DSM)",
        "Specialist diabetic dietician available via fortnightly Microsoft Teams drop-in sessions",
        "Refer to Miss Fayyaz/Miss Gajree if requiring retinopathy treatment, CKD 2 + PCR > 30, or CKD 3 — via regional maternal medicine meeting (OARS to Silver Star, Oxford)",
      ]},
      { type: "subheading", value: "Scans" },
      { type: "list", items: [
        "Viability scan at 7–8 weeks, routine dating and anomaly scans",
        "Fetal echo at 22–24 weeks no longer indicated (cardiac views are part of routine anomaly scan)",
        "Fetal growth monitored from 28 weeks every 4 weeks until 36 weeks; weekly/2-weekly may be required in some cases",
      ]},
      { type: "subheading", value: "Medications" },
      { type: "list", items: [
        "Folic acid 5 mg pre-pregnancy and continue to 14 weeks",
        "Aspirin 150 mg from 12 weeks onwards (unless advised earlier) to reduce risk of early-onset pre-eclampsia; stop at 36 weeks",
        "Discontinue ACE inhibitors, ARBs, statins, and all diabetes medications except insulin and metformin if planning pregnancy or as soon as possible after positive test",
        "LMWH strongly considered in all women with PCR > 300 mg/mol",
      ]},
      { type: "subheading", value: "Glucose Targets" },
      { type: "table", headers: ["Timing", "Target"], rows: [
        ["Fasting (pre-breakfast)", "< 5.3 mmol/L"],
        ["Pre-lunch and pre-dinner", "4.0–6.0 mmol/L"],
        ["1 hour post-meal", "< 7.8 mmol/L"],
        ["2 hours post-meal", "< 6.4 mmol/L"],
        ["Pre-bed (≥ 2 hours after dinner)", "< 6.4 mmol/L"],
      ]},
      { type: "subheading", value: "Blood Glucose Monitoring" },
      { type: "list", items: [
        "Type 2: blood glucose meter — monitor 6 times a day (before and 1 hour after each main meal)",
        "Type 1: offer real-time continuous glucose monitoring (CGM) — education and training by DSM",
        "Flash monitoring (FreeStyle Libre) may be available at discretion of primary care for T2 on insulin",
        "If poor control or poor hypo awareness — MDT will write to GP to prescribe Libre",
        "All T1 women: ensure ketone monitor and in-date test strips",
        "Hypoglycaemia safety: discuss with woman, provide Hypo-kits, teach adult relative to recognise and treat at home",
      ]},
      { type: "subheading", value: "HbA1c Targets (Saving Babies Lives v.3)" },
      { type: "text", value: "Measure HbA1c at booking and repeat at 24+0–30+0 weeks. Aim for HbA1c < 48 mmol/mol." },
      { type: "table", headers: ["Status", "HbA1c", "Action"], rows: [
        ["Green", "≤ 43 mmol/mol", "Continue current care"],
        ["Amber", "44–48 mmol/mol", "Consider additional input to improve glucose management"],
        ["Red", "> 48 mmol/mol", "MDT discussion; additional input; increased fetal surveillance; re-discuss increased risk of stillbirth, birth and neonatal complications"],
      ]},
      { type: "alert", value: "Women with HbA1c > 86 mmol/mol are advised to avoid pregnancy — counselling should acknowledge this." },
      { type: "subheading", value: "Retinal Screening" },
      { type: "list", items: [
        "Retinal screening once per trimester — organised by DSM in first instance",
        "Refer to Oxford (OARS to Silver Star) if treatment required during pregnancy",
        "Women with renal impairment referred to Oxford University Hospital via OARS",
      ]},
      { type: "subheading", value: "Plan for Delivery" },
      { type: "list", items: [
        "Delivery between 37+0 and 38+6 weeks; earlier if medical or obstetric complications",
        "Aim blood sugar < 7 mmol/L in 24 hours before delivery; use sliding scale if necessary",
        "Customised delivery plan made in joint diabetes clinic — available on EPR",
        "Discuss potential for baby to be admitted to Special Care Unit",
      ]},
    ]
  },
  {
    id: "dm-preexisting-intrapartum", gl: "GL983", condition: "Diabetes in Pregnancy", setting: "Pre-existing T1/T2 — Intrapartum & Postnatal",
    title: "Pre-existing Diabetes — Intrapartum & Postnatal Management",
    tags: ["diabetes","t1dm","t2dm","intrapartum","labour","vrii","sliding scale","insulin infusion","blood glucose monitoring","metformin stop","active labour","short acting insulin","u&e","potassium","bicarbonate","4 mmol","7 mmol","postnatal","insulin dose reduction","25 percent","50 percent","endocrine registrar","bleep 192 199","breastfeeding","cgm in labour","arm","cannula","iv cannula"],
    content: [
      { type: "subheading", value: "Intrapartum Management" },
      { type: "list", items: [
        "All inpatients using own insulin: assessed by admitting midwife for suitability to self-administer per RBH trust guidelines",
        "If using CGM/FreeStyle Libre: check reported result against finger prick — if within 0.3 mmol/L, existing monitor can be used",
        "Continue normal medication (Metformin and/or insulin) until active labour or after ARM; discontinue Metformin and short-acting insulin in women not eating",
        "IV cannula sited as soon as in established labour; second IV cannula required if VRII needed",
        "T1DM: offer VRII once in established labour or after ARM — stop short-acting (bolus) insulin but continue long-acting (basal) insulin on VRII; women may choose insulin pump as alternative",
        "T2DM on Metformin/diet: monitor BG 2-hourly; increase to hourly if BG > 7.0 mmol/L; if persistently > 7.0 mmol/L start VRII",
        "Target blood glucose 4.0–7.0 mmol/L during labour",
        "Monitor BG every hour in first stage and every 30 minutes in second stage for insulin-dependent T1 and T2",
        "Check U&Es 4–6 hourly during labour to maintain potassium and bicarbonate",
        "VRII: discontinued after delivery when patient is eating and drinking normally and BG < 8 mmol/L — ensure short-acting insulin given 30 minutes before stopping",
      ]},
      { type: "alert", value: "ALL insulin pumps and blood sugar monitors (e.g. FreeStyle Libre) MUST BE REMOVED IN THEATRE. Women advised to bring new sets." },
      { type: "subheading", value: "Postnatal Care (Pre-existing T1/T2)" },
      { type: "list", items: [
        "T1 and T2: significantly smaller insulin doses needed postnatally — document plan on EPR",
        "If no documented plan: reduce first insulin dose by 25% below last pregnancy dose, OR reduce last pregnancy dose by 50%",
        "If still unsure: contact endocrine registrar on bleep 192/199",
        "Monitor BG 4 times daily (before each meal and pre-bed); aim pre-meal glucose 6.0–10.0 mmol/L",
        "T1: CGM recordings can be used; replace sensor and pump from own kit immediately postnatal",
        "T2 on Metformin/diet: may or may not need medication — review delivery plan on EPR for postnatal instructions",
        "If BMs persistently > 10.0 mmol/L: consult DSM or endocrine registrar",
        "Breastfeeding/expressing: include 10–15 g carbohydrate and drink fluids with each feed and when expressing",
      ]},
    ]
  },
  {
    id: "dm-gdm", gl: "GL983", condition: "Diabetes in Pregnancy", setting: "Gestational Diabetes (GDM)",
    title: "Gestational Diabetes (GDM) — Screening, Diagnosis & Management",
    tags: ["gdm","gestational diabetes","ogtt","oral glucose tolerance test","screening","diagnosis","5.6 mmol","7.8 mmol","risk factors","previous gdm","south asian","black african","afro-caribbean","bmi 30","macrosomia","family history","glycosuria","anti-psychotics","bariatric","fasting blood glucose","hba1c diagnosis","41 mmol","28 weeks","40 weeks","metformin","insulin","diet","lifestyle","blood glucose","5.3","4.0","6.0","7.8","6.4","dsm","growth scan"],
    content: [
      { type: "subheading", value: "Screening — Risk Factors for GDM" },
      { type: "list", items: [
        "Previous GDM",
        "Ethnicity with high prevalence (South Asian, Black African, Afro-Caribbean, mixed ethnicity)",
        "Previous baby with birth weight > 4500 g",
        "BMI > 30 kg/m²",
        "First degree relative with diabetes",
        "Glycosuria: 1+ on 2 occasions or ≥ 2+ on 1 occasion",
        "Women on anti-psychotics",
        "Scan showing AC > 95th centile with or without polyhydramnios",
        "Previous bariatric surgery",
      ]},
      { type: "subheading", value: "Diagnosis" },
      { type: "list", items: [
        "OGTT is the preferred and validated method — offered if < 32+0 weeks",
        "From 32 weeks: fasting blood glucose and HbA1c taken",
        "GDM diagnosed if fasting BG ≥ 5.6 mmol/L or 2-hour level ≥ 7.8 mmol/L",
        "Previous gastric bypass: 1-week blood sugar monitoring at ~26/40 via diabetes midwives instead of OGTT",
        "HbA1c > 41 mmol/mol and < 28/40 OR > 39 mmol/mol and > 28/40 diagnoses gestational diabetes",
        "HbA1c > 48 mmol/mol: likely represents pre-existing Type 2 diabetes that will not resolve after pregnancy",
      ]},
      { type: "subheading", value: "Antenatal Management of GDM" },
      { type: "list", items: [
        "Aim fasting BG < 5.3 mmol/L and pre-prandial BG 4.0–6.0 mmol/L",
        "1-hour post-prandial BG target < 7.8 mmol/L; 2-hour post-prandial < 6.4 mmol/L",
        "Women send BG readings to DSMs by email or phone; DSMs initiate treatment if targets not met",
        "Fasting BG ≥ 7.0 mmol/L at diagnosis: offer immediate treatment with insulin ± metformin + diet/exercise changes",
        "Fasting BG 6.0–6.9 mmol/L with macrosomia or hydramnios: consider immediate insulin ± metformin",
        "Ultrasound growth scans from 28 weeks",
        "Deliver between 40+0 and 40+6 weeks (earlier if complications)",
        "Measure HbA1c at time of diagnosis to identify possible pre-existing T2DM",
      ]},
      { type: "subheading", value: "GDM Intrapartum Care" },
      { type: "list", items: [
        "Assess suitability to self-administer insulin; continue normal diet and medication until active labour or ARM",
        "Continue Metformin and/or insulin until active labour; discontinue Metformin and short-acting insulin if not eating",
        "Target BG 4.0–7.0 mmol/L during labour",
        "Monitor BG minimum 2-hourly; increase to hourly if above 7.0 mmol/L",
        "If persistently > 7.0 mmol/L and delivery not imminent: consider VRII to prevent neonatal hypoglycaemia",
      ]},
      { type: "subheading", value: "GDM Postnatal Care" },
      { type: "list", items: [
        "Vast majority: BG returns to normal within 24–36 hours",
        "Monitor BG minimum 4 times daily (pre-meals and pre-bed); discharge if BG < 6.0 mmol/L",
        "BG 6.0–10.0 mmol/L: can discharge with message left for DSM to follow up",
        "If BG > 10.0 mmol/L after 24 hours: do not discharge without DSM/Diabetes MDT review (likely pre-existing diabetes)",
      ]},
      { type: "alert", value: "Women should have a fasting blood glucose 5 weeks after delivery, reviewed by GP at 6-week visit. Referral to Diabetes Prevention Pathway should be offered." },
    ]
  },
  {
    id: "dm-vrii", gl: "GL983", condition: "Diabetes in Pregnancy", setting: "Variable Rate Insulin Infusion (VRII)",
    title: "VRII (Variable Rate Insulin Infusion) — Protocol",
    tags: ["vrii","sliding scale","variable rate insulin infusion","insulin infusion","algorithm 1","algorithm 2","algorithm 3","novorapid","50 units","normal saline","0.45 percent","5 percent glucose","potassium chloride","substrate solution","cbg","4 to 7.8","target","infusion rate","hyperglycaemia","steroid","intrapartum","dka","intercurrent illness","4 mmol","7 mmol","11 mmol","hourly cbg","preparation"],
    content: [
      { type: "subheading", value: "Indications for VRII" },
      { type: "list", items: [
        "Intercurrent illness", "Steroid treatment",
        "Intrapartum (for T1DM or when BG persistently > 7.0 mmol/L)",
        "Diabetic ketoacidosis — CAUTION: refer to DKA management section",
      ]},
      { type: "subheading", value: "Preparation" },
      { type: "text", value: "Soluble insulin (Novorapid) 50 units in 50 mL Normal Saline (NaCl 0.9%) in 50 mL IV syringe via Trust-approved infusion pump.\n\nSubstrate solution alongside VRII: 0.45% saline with 5% glucose and 0.15% potassium chloride OR 5% glucose (caution hyponatraemia). Prescribe on EPR — DO NOT use Powerplan fluids. Run at 50 mL/hr." },
      { type: "subheading", value: "VRII Algorithm Table" },
      { type: "table", headers: ["CBG (mmol/L)", "Algorithm 1 (most women)", "Algorithm 2 (> 80 units/day or not controlled on Alg 1)", "Algorithm 3 (specialist advice only)"], rows: [
        ["< 4.0", "STOP insulin 20 min; treat hypo; recheck CBG in 10 min", "", ""],
        ["4.0–5.5", "0.2 units/hr", "0.5 units/hr", "1.0 units/hr"],
        ["5.6–7.0", "0.5 units/hr", "1.0 units/hr", "2.0 units/hr"],
        ["7.1–8.5", "1.0 units/hr", "1.5 units/hr", "3.0 units/hr"],
        ["8.6–11.0", "1.5 units/hr", "2.0 units/hr", "4.0 units/hr"],
        ["11.1–14.0", "2.0 units/hr", "2.5 units/hr", "5.0 units/hr"],
        ["14.1–17.0", "2.5 units/hr", "3.0 units/hr", "6.0 units/hr"],
        ["17.1–20.0", "3.0 units/hr", "4.0 units/hr", "7.0 units/hr"],
        ["> 20.1", "4.0 units/hr", "—", "6.0 units/hr"],
      ]},
      { type: "subheading", value: "Key Principles" },
      { type: "list", items: [
        "Target CBG 4.0–7.8 mmol/L; check CBG every hour whilst on VRII",
        "Move to higher algorithm if CBG > target and not dropping; move to lower algorithm if CBG < 4.0 mmol/L or dropping too fast",
        "Women on VRII after steroids who are eating: continue short-acting (bolus) AND long-acting (basal) insulin alongside VRII",
        "If VRII started intrapartum: continue long-acting insulin only alongside VRII; avoid short-acting if not eating normally",
        "If not achieving targets: contact diabetes team (out of hours: Medical SpR on call)",
        "Continue VRII for 24 hours after second dose of steroid",
        "Add 10% Dextrose alongside Normal Saline when BG ≤ 14 mmol/L at 125 mL/hr (or 250 mL/hr if BG < 7 mL/hr)",
      ]},
    ]
  },
  {
    id: "dm-steroid", gl: "GL983", condition: "Diabetes in Pregnancy", setting: "Steroid Prophylaxis",
    title: "Diabetes — Steroid Prophylaxis Management",
    tags: ["diabetes","steroids","betamethasone","steroid prophylaxis","hyperglycaemia","insulin increase","10 percent","20 percent","vrii","blood glucose","11 mmol","ketones","1 plus","2 plus","urine ketones","capillary ketones","dka risk","admission","every 4 hours","triage","48 hours","fetal lung maturation","steroid treatment","bm","home"],
    content: [
      { type: "subheading", value: "Steroid Prophylaxis in Diabetic Women" },
      { type: "list", items: [
        "Steroids usually cause a rise in maternal blood glucose — can be apparent immediately or take time",
        "Women on insulin: increase insulin by 10–20% from steroid administration and for the next 48 hours; document increased dose on EPR",
        "DKA is a serious risk for diabetic women receiving steroids — admission may be necessary for Type 1, Metformin-controlled, or diet-controlled diabetics",
        "Urine ketone testing twice daily if admitted; if 1+ on dipstick — check capillary ketones; if 2+ — alert obstetric registrar",
        "Women who are on VRII and have had steroids: should eat and drink normally and continue all diabetes medication (short and long-acting insulin) in addition to VRII",
      ]},
      { type: "subheading", value: "Blood Glucose Monitoring at Home After Steroids" },
      { type: "list", items: [
        "Check BG every 4 hours",
        "If BM ≥ 11 mmol/L: repeat test in 1 hour",
        "If still ≥ 11 mmol/L: call triage and attend hospital for VRII",
        "If < 11 mmol/L: continue monitoring 4-hourly",
      ]},
    ]
  },
  {
    id: "dm-dka", gl: "GL983", condition: "Diabetes in Pregnancy", setting: "Diabetic Ketoacidosis (DKA)",
    flowchartId: "GL983_DKA",
    title: "Diabetic Ketoacidosis (DKA) in Pregnancy — Diagnosis & Treatment",
    tags: ["dka","diabetic ketoacidosis","ketones","3 mmol","1.5 mmol","ph 7.3","bicarbonate 15","venous gas","blood ketones","urinary ketones","nausea","vomiting","abdominal pain","polyuria","polydipsia","tachypnoea","frii","fixed rate insulin infusion","0.9% sodium chloride","potassium","fluid replacement","mortality","stillbirth","160 per 1000","obstetric registrar","endocrine registrar","itu","hdu","fbc","u&e","lactate","blood gas","mc&s","glucose","insulin infusion","treatment targets","resolution","subcutaneous insulin","t2dm","gestational","normal glucose","any woman","feeling unwell"],
    content: [
      { type: "alert", value: "DKA is a medical emergency. Any woman known to have diabetes who contacts triage/MAU feeling unwell should be invited in for assessment at whatever gestation." },
      { type: "subheading", value: "Overview" },
      { type: "list", items: [
        "DKA in pregnancy: stillbirth rate 160 per 1000 births; mortality 5–10% in adults with T1D",
        "Can occur in T1D, T2D, and gestational diabetes",
        "DKA in pregnancy may present with normal or modest rise in glucose — do NOT rely on glucose alone",
        "Causes: infection, hyperemesis gravidarum, neglect of diabetes care, steroid prophylaxis, faulty equipment, poor compliance",
        "Symptoms: nausea, vomiting, abdominal pain, polyuria, polydipsia, leg cramps, dehydration, blurred vision, tachypnoea, distinct breath smell, coma",
      ]},
      { type: "subheading", value: "Diagnosis" },
      { type: "list", items: [
        "Known diabetes (any type) PLUS:",
        "Urinary ketones ≥ 2+ OR blood ketones > 3.0 mmol/L (high risk if > 1.5 mmol/L)",
        "Blood gas pH < 7.3 and/or serum bicarbonate < 15 mmol/L (use venous gas)",
        "If on insulin pump: discontinue pump and start FRII",
      ]},
      { type: "subheading", value: "Investigations" },
      { type: "list", items: [
        "Bloods: FBC, U&Es, glucose and ketones, bicarbonate, venous lactate, cultures if indicated",
        "G&S, ABG if SpO₂ low",
        "Urine MC&S",
        "Consider Chest X-ray and ECG",
        "CTG as soon as woman is stabilised",
      ]},
      { type: "subheading", value: "Treatment" },
      { type: "list", items: [
        "Assessment ABC; site 2 × IV cannulae (grey, 16G)",
        "Inform obstetric registrar, obstetric consultant, and anaesthetic consultant early",
        "Request medical review and endocrine registrar (bleep 199/192)",
        "Assess for severity and consider ITU/HDU",
        "15-minute BP and pulse; hourly respiration and MOWS; 4-hourly temperatures",
      ]},
      { type: "subheading", value: "IV Fluid Replacement" },
      { type: "table", headers: ["Fluid", "Volume", "Duration", "Potassium"], rows: [
        ["0.9% NaCl", "1 litre", "1 hour", "None (give 500 mL bolus if SBP < 90 mmHg)"],
        ["0.9% NaCl", "1 litre", "2 hours", "Replace as below"],
        ["0.9% NaCl", "1 litre", "2 hours", "Replace as below"],
        ["0.9% NaCl", "1 litre", "4 hours", "Replace as below"],
        ["0.9% NaCl", "1 litre", "6–8 hours", "Replace as below"],
      ]},
      { type: "subheading", value: "Potassium Replacement (aim 4.0–5.5 mmol/L)" },
      { type: "table", headers: ["Potassium Level", "KCl per litre of fluid", "Comment"], rows: [
        ["< 3.5 mmol/L", "40 mmol", "Refer to endocrine registrar/outreach team"],
        ["3.5–5.5 mmol/L", "20 mmol", ""],
        ["> 5.5 mmol/L", "No potassium", "Potassium chloride NOT to be infused > 10 mmol/hr"],
      ]},
      { type: "subheading", value: "Fixed Rate Insulin Infusion (FRII)" },
      { type: "text", value: "50 units soluble insulin (Humulin S or Actrapid) in 49.5 mL NaCl 0.9% via syringe driver.\n\nWhen BG ≤ 14 mmol/L: add 10% Dextrose at 125 mL/hr (or 250 mL/hr if BG < 7 mL/hr).\n\nContinue long-acting insulin at usual dose and time.\n\nIncrease infusion rate by 1 mL/hr if target not met and no pump malfunction." },
      { type: "table", headers: ["Weight", "Hourly Infusion Rate"], rows: [
        ["60–69 kg", "6 units/hr"], ["70–79 kg", "7 units/hr"], ["80–89 kg", "8 units/hr"],
        ["90–99 kg", "9 units/hr"], ["100–109 kg", "10 units/hr"], ["110–119 kg", "11 units/hr"],
        ["120–129 kg", "12 units/hr"], ["130–139 kg", "13 units/hr"], ["≥ 140 kg", "14 units/hr"],
      ]},
      { type: "subheading", value: "Monitoring & Resolution" },
      { type: "list", items: [
        "First 6 hours: BG and ketones at least hourly",
        "Blood gas at 1, 2, 4, 6, 8 hours to check pH and potassium",
        "Monitor fluid status; CTG continuously — FHR abnormalities may improve with maternal improvement",
        "Signs of resolution: blood ketones < 0.3 mmol/L AND pH > 7.3",
        "When resolved and patient able to eat/drink: convert to subcutaneous insulin",
        "If resolved but cannot eat/drink: switch to VRII and start 5% Dextrose if BG < 14 mmol/L",
      ]},
    ]
  },
];
