// GTG67 — Management of Endometrial Hyperplasia
// RCOG/BSGE Green-top Guideline No. 67 (February 2016)
// Joint guideline: Royal College of Obstetricians and Gynaecologists (RCOG)
// and British Society for Gynaecological Endoscopy (BSGE)

export const GTG67_SECTIONS = [
  {
    id: "gtg67-overview",
    gl: "GTG67",
    condition: "Endometrial Hyperplasia",
    setting: "Gynaecology",
    title: "Endometrial Hyperplasia — Overview & Classification",
    tags: [
      "endometrial hyperplasia", "hyperplasia", "gtg67", "rcog", "bsge",
      "endometrial intraepithelial neoplasia", "ein", "atypical hyperplasia", "aeh",
      "endometrial cancer precursor", "abnormal uterine bleeding hyperplasia",
      "who classification hyperplasia", "uterine hyperplasia",
    ],
    flowchartId: "GTG67_MANAGEMENT",
    content: [
      { type: "text", value: "RCOG/BSGE Green-top Guideline No. 67 (February 2016) covers the diagnosis and management of endometrial hyperplasia. Endometrial hyperplasia describes a spectrum of morphological changes in the endometrium characterised by proliferation of endometrial glands of irregular size and shape with an increased gland-to-stroma ratio." },
      { type: "alert", value: "Atypical endometrial hyperplasia (AEH) / Endometrial Intraepithelial Neoplasia (EIN) is a premalignant condition with a concurrent endometrial cancer risk of approximately 8% and a long-term cancer risk of up to 27.5% — hysterectomy is the standard treatment in women who have completed their family." },
      { type: "subheading", value: "WHO 2014 Classification" },
      { type: "list", items: [
        "Endometrial hyperplasia WITHOUT atypia — benign; low malignant potential (~1–3%); often reversible with progestogen treatment",
        "Atypical endometrial hyperplasia (AEH) / Endometrial Intraepithelial Neoplasia (EIN) — premalignant; ~8% risk of concurrent endometrial cancer at time of diagnosis; up to 27.5% risk at 9 years if untreated",
      ]},
      { type: "text", value: "The 2014 WHO classification superseded the previous four-category classification (simple/complex without atypia; simple/complex with atypia). The new two-category system better reflects clinical behaviour and management decisions." },
      { type: "subheading", value: "Prevalence and Significance" },
      { type: "list", items: [
        "Endometrial hyperplasia without atypia: relatively common, particularly in perimenopausal women; spontaneous regression in ~75% over 12–18 months if oestrogen excess is corrected",
        "AEH/EIN: less common but clinically important — concurrent endometrial cancer found in up to 40% of women who proceed to hysterectomy after AEH diagnosis on biopsy",
        "Both types present most commonly with abnormal uterine bleeding (HMB, intermenstrual bleeding, postmenopausal bleeding)",
      ]},
      { type: "subheading", value: "Risk Factors" },
      { type: "list", items: [
        "Obesity (BMI >30) — the most significant independent risk factor; oestrogen produced by adipose tissue",
        "Polycystic ovary syndrome (PCOS) — anovulation causes prolonged unopposed oestrogen stimulation",
        "Nulliparity",
        "Unopposed oestrogen (HRT without adequate progestogen in women with a uterus)",
        "Tamoxifen use — partial oestrogen agonist on endometrium",
        "Diabetes mellitus type 2",
        "Late menopause (>52 years)",
        "Hereditary non-polyposis colorectal cancer (Lynch syndrome / HNPCC) — lifetime endometrial cancer risk 40–60%",
        "Oestrogen-secreting ovarian tumours (e.g. granulosa cell tumour)",
        "Chronic anovulation from any cause",
      ]},
    ],
  },

  {
    id: "gtg67-diagnosis",
    gl: "GTG67",
    condition: "Endometrial Hyperplasia",
    setting: "Gynaecology",
    title: "Diagnosis & Investigation",
    tags: [
      "endometrial hyperplasia diagnosis", "endometrial biopsy hyperplasia",
      "hysteroscopy hyperplasia", "pipelle hyperplasia", "endometrial sampling",
      "endometrial thickness", "transvaginal ultrasound hyperplasia",
      "postmenopausal endometrium", "endometrial assessment",
      "histological diagnosis hyperplasia",
    ],
    content: [
      { type: "text", value: "Endometrial hyperplasia is a histological diagnosis — it requires tissue sampling for confirmation. It cannot be diagnosed by ultrasound alone, though imaging is used to triage women for biopsy." },
      { type: "subheading", value: "Who Should be Investigated" },
      { type: "list", items: [
        "Postmenopausal bleeding (any bleeding ≥12 months after last period) — urgent assessment; 2WW referral in UK",
        "Persistent intermenstrual bleeding or irregular/heavy bleeding in premenopausal women with risk factors",
        "Endometrial thickening on USS in postmenopausal women: >4 mm warrants biopsy in symptomatic women",
        "Incidental USS finding of thickened endometrium in asymptomatic women: threshold for biopsy debated — generally >4 mm in postmenopausal women warrants investigation",
      ]},
      { type: "subheading", value: "Transvaginal USS (TVUSS)" },
      { type: "list", items: [
        "First-line imaging for abnormal uterine bleeding; measures endometrial thickness, identifies structural pathology",
        "Postmenopausal women: endometrial thickness <4 mm has high negative predictive value for endometrial cancer/hyperplasia in symptomatic women",
        "Does NOT diagnose hyperplasia histologically — thickness alone is not sufficient to diagnose or exclude hyperplasia",
        "Irregular, heterogeneous, or thickened endometrium on USS requires histological sampling",
      ]},
      { type: "subheading", value: "Endometrial Biopsy" },
      { type: "list", items: [
        "Pipelle suction biopsy (outpatient): acceptable first-line sampling method; evaluates ~4% of endometrial surface; may miss focal lesions",
        "Sensitivity: ~90% for detecting endometrial cancer; lower for detecting hyperplasia (particularly focal AEH or EIN)",
        "Hysteroscopy + directed biopsy: superior — allows direct visualisation and targeted sampling; can identify focal lesions missed by Pipelle",
        "RCOG/BSGE recommend hysteroscopy + biopsy for women in whom adequate Pipelle sampling fails, cervix is stenosed, or focal lesion is suspected",
        "All tissue removed at hysteroscopy should be sent for histology",
      ]},
      { type: "subheading", value: "MRI" },
      { type: "list", items: [
        "Not used for primary diagnosis of endometrial hyperplasia",
        "Used in AEH/EIN to assess for myometrial invasion (staging) before planned conservative management or hysterectomy",
        "MRI pelvis is recommended when AEH is diagnosed conservatively and concurrent cancer must be excluded before treatment",
      ]},
    ],
  },

  {
    id: "gtg67-hyperplasia-no-atypia",
    gl: "GTG67",
    condition: "Endometrial Hyperplasia",
    setting: "Gynaecology",
    title: "Management — Hyperplasia Without Atypia",
    tags: [
      "hyperplasia without atypia", "endometrial hyperplasia treatment",
      "lng-ius hyperplasia", "progestogen hyperplasia", "norethisterone hyperplasia",
      "mpa hyperplasia", "medroxyprogesterone acetate", "endometrial hyperplasia regression",
      "biopsy surveillance hyperplasia", "hyperplasia follow-up",
      "endometrial hyperplasia primary care", "benign hyperplasia",
    ],
    flowchartId: "GTG67_MANAGEMENT",
    content: [
      { type: "text", value: "Endometrial hyperplasia without atypia is a benign condition with a low (~1–3%) risk of malignant transformation. It commonly regresses spontaneously, particularly if the underlying oestrogen excess is addressed. When treatment is required, the LNG-IUS is first-line." },
      { type: "subheading", value: "Treatment Options" },
      { type: "alert", value: "LNG-IUS (52 mg, Mirena) is the preferred first-line treatment — it achieves higher regression rates than oral progestins and is associated with better side-effect profiles and patient satisfaction." },
      { type: "table", headers: ["Treatment", "Regression Rate", "Notes"], rows: [
        ["LNG-IUS 52 mg (Mirena)", ">90% at 6 months", "First-line. Local progestogen delivery; minimal systemic effects. Can remain in situ for surveillance period."],
        ["Continuous oral MPA (medroxyprogesterone acetate)", "~66–80% at 6 months", "10–20 mg daily. Alternative if LNG-IUS declined or unsuitable."],
        ["Continuous oral norethisterone", "~60–75% at 6 months", "10–15 mg daily. Alternative to MPA."],
        ["Observation alone (no progestogen)", "~74–81% at 24 months", "Only if reversible risk factors fully addressed (e.g. weight loss, stop tamoxifen). Requires close surveillance."],
      ]},
      { type: "subheading", value: "Observation Without Treatment" },
      { type: "list", items: [
        "Acceptable only if a reversible cause is identified and fully addressed (e.g. significant weight loss in obese women, cessation of tamoxifen or unopposed oestrogen)",
        "Requires surveillance endometrial biopsies at 6-monthly intervals",
        "Spontaneous regression rate is high but progestogen treatment achieves faster and more reliable regression",
      ]},
      { type: "subheading", value: "Addressing Risk Factors" },
      { type: "list", items: [
        "Weight reduction: counsel on weight management; referral to weight management services as appropriate — reduces oestrogen production from adipose tissue",
        "Cessation of tamoxifen: discuss with oncology team if switching to aromatase inhibitor is possible",
        "Correction of anovulation: cyclical progestogen or CHC in women with PCOS",
        "Adequate progestogen in HRT: ensure progestogen component is adequate if on HRT",
      ]},
      { type: "subheading", value: "Surveillance — Endometrial Biopsy Follow-up" },
      { type: "list", items: [
        "Repeat endometrial biopsy at 6-monthly intervals until TWO consecutive negative biopsies",
        "Method: Pipelle biopsy or hysteroscopy + biopsy",
        "After two consecutive negative biopsies: consider discharging from surveillance if risk factors resolved",
        "Retained LNG-IUS: recommend continuing LNG-IUS for up to 5 years after confirmed regression — reduces relapse risk",
        "If hyperplasia does not regress after 12 months of adequate treatment, or risk factors persist: review management; consider hysterectomy",
      ]},
      { type: "subheading", value: "Surgical Management" },
      { type: "list", items: [
        "Hysterectomy for hyperplasia without atypia: not first-line; appropriate if progestogen treatment fails after 12 months, is not tolerated, or woman requests definitive treatment after counselling",
        "Total hysterectomy: removes the uterus; no ongoing surveillance required post-operatively",
        "Ovarian conservation: appropriate in most premenopausal women",
      ]},
    ],
  },

  {
    id: "gtg67-atypical-hyperplasia",
    gl: "GTG67",
    condition: "Endometrial Hyperplasia",
    setting: "Gynaecology / Oncology",
    title: "Management — Atypical Hyperplasia (AEH/EIN)",
    tags: [
      "atypical endometrial hyperplasia", "aeh", "ein", "endometrial intraepithelial neoplasia",
      "aeh treatment", "hysterectomy aeh", "aeh hysterectomy",
      "fertility sparing aeh", "conservative aeh", "progestogen aeh",
      "lng-ius aeh", "oncology referral aeh", "endometrial cancer risk aeh",
      "concurrent endometrial cancer", "aeh surveillance",
    ],
    flowchartId: "GTG67_AEH",
    content: [
      { type: "text", value: "Atypical endometrial hyperplasia (AEH) / Endometrial Intraepithelial Neoplasia (EIN) is a premalignant condition. The concurrent risk of endometrial cancer at the time of AEH diagnosis is approximately 8% (up to 40% in some series when hysterectomy is promptly performed), and the risk of progression to cancer if untreated is up to 27.5% at 9 years." },
      { type: "alert", value: "Total hysterectomy is the recommended treatment for AEH/EIN in women who have completed their family or who are not suitable for fertility-sparing management. Fertility-sparing treatment is a specialist option only, at a centre with expertise in conservative management." },
      { type: "subheading", value: "Standard Treatment — Total Hysterectomy" },
      { type: "list", items: [
        "Total hysterectomy (TH): removes the uterus; curative for AEH and any concurrent endometrial cancer",
        "Route: total laparoscopic hysterectomy (TLH) preferred for minimally invasive approach; or abdominal depending on surgical history and uterine size",
        "Ovarian conservation vs bilateral salpingo-oophorectomy (BSO): individual decision",
        "BSO generally recommended in postmenopausal women (removes ovarian cancer risk; no impact on ovarian function if already menopausal)",
        "Premenopausal women: ovarian conservation can be discussed — retains ovarian function and avoids surgical menopause; ovarian cancer risk from AEH alone is low in premenopausal women",
        "Pre-operative MRI pelvis: recommended to assess myometrial invasion and detect concurrent cancer before surgery",
        "Post-operative histology: the hysterectomy specimen must be thoroughly examined — concurrent endometrial cancer found in up to 40% of cases",
        "If cancer found post-hysterectomy: MDT discussion; staging investigations; oncology follow-up as appropriate",
      ]},
      { type: "subheading", value: "Fertility-Sparing Treatment — Selected Cases Only" },
      { type: "list", items: [
        "Appropriate only for: women who strongly desire future fertility AND are fully informed of the risks AND are followed up at a specialist centre",
        "Before starting: MRI pelvis to exclude myometrial invasion or concurrent cancer; if cancer suspected on MRI → proceed to hysterectomy",
        "First-line fertility-sparing treatment: LNG-IUS 52 mg (Mirena) — highest evidence base for regression",
        "Alternative/adjunct: high-dose oral progestogens — medroxyprogesterone acetate (MPA) 400–600 mg/day, or megestrol acetate 160 mg/day",
        "LNG-IUS + oral progestogen combination: some centres use both concurrently; no definitive RCT evidence for superiority over LNG-IUS alone",
        "Approximately 1 in 3 patients fail to respond — retreat or escalate to hysterectomy",
        "Ovulation induction and IVF: may be offered concurrently or after confirmed complete remission — discuss with reproductive medicine",
      ]},
      { type: "subheading", value: "Surveillance During Fertility-Sparing Treatment" },
      { type: "list", items: [
        "3-monthly endometrial biopsy (Pipelle or hysteroscopy) throughout treatment period",
        "Response assessment at 3 months: if no regression → increase dose or change treatment; if regression → continue and re-biopsy",
        "Complete remission (CR): two consecutive normal biopsies required",
        "After CR: attempt conception without delay (higher relapse risk with delay); refer to reproductive medicine",
        "After completing childbearing: strongly recommend hysterectomy — AEH has a high relapse rate after conservative treatment",
        "No pregnancy achieved within 2 years of CR: reassess; further discussion regarding hysterectomy vs continued surveillance",
      ]},
      { type: "subheading", value: "Management of Relapse" },
      { type: "list", items: [
        "Relapse after CR: common — up to 40% within 5 years of stopping treatment",
        "Repeat progestogen treatment: if woman still wishes to preserve fertility and no progression to carcinoma",
        "Hysterectomy: recommended after second relapse, or if woman has completed her family",
        "Concurrent endometrial cancer: if diagnosed at any point → proceed to standard oncological management (hysterectomy + staging ± adjuvant therapy per gynaecological oncology MDT)",
      ]},
    ],
  },

  {
    id: "gtg67-lynch-tamoxifen",
    gl: "GTG67",
    condition: "Endometrial Hyperplasia",
    setting: "Gynaecology / Oncology",
    title: "Special Situations: Lynch Syndrome & Tamoxifen",
    tags: [
      "lynch syndrome endometrial", "hnpcc endometrial", "lynch endometrial cancer",
      "tamoxifen endometrial", "tamoxifen hyperplasia", "tamoxifen uterus",
      "endometrial surveillance lynch", "mismatch repair genes",
      "mlh1 msh2 msh6 pms2", "hereditary endometrial cancer",
    ],
    content: [
      { type: "text", value: "Certain groups of women face substantially higher risks of endometrial hyperplasia and cancer, warranting tailored surveillance and management strategies." },
      { type: "subheading", value: "Lynch Syndrome (HNPCC)" },
      { type: "list", items: [
        "Lynch syndrome (mismatch repair gene mutations: MLH1, MSH2, MSH6, PMS2) confers a lifetime endometrial cancer risk of 40–60% — higher than the general population risk of ~2–3%",
        "Endometrial cancer often develops at younger age (premenopausal) in Lynch syndrome",
        "Surveillance: annual endometrial sampling (hysteroscopy or Pipelle) from age 35 or 5 years before earliest affected family member",
        "Risk-reducing surgery: risk-reducing total hysterectomy ± bilateral salpingo-oophorectomy discussed once childbearing complete — removes risk of endometrial and ovarian cancer",
        "Genetic counselling: all women with AEH should be offered genetic testing for Lynch syndrome (especially if age <50 or family history of HNPCC-associated cancers)",
        "If Lynch syndrome confirmed and AEH diagnosed: hysterectomy is the recommended treatment regardless of fertility wishes (due to very high cancer risk)",
      ]},
      { type: "subheading", value: "Tamoxifen-Associated Endometrial Changes" },
      { type: "list", items: [
        "Tamoxifen is a selective oestrogen receptor modulator — oestrogenic effect on endometrium; increases risk of polyps, hyperplasia, and endometrial cancer",
        "Relative risk of endometrial cancer with tamoxifen: ~2–3 fold; absolute risk is low but clinically significant in long-term users",
        "Pre-menopausal women on tamoxifen: stimulatory endometrial effect offset by intact hypothalamic-pituitary-ovarian axis; endometrial cancer risk lower than postmenopausal users",
        "Post-menopausal women on tamoxifen: higher risk — annual surveillance considered (outpatient hysteroscopy ± biopsy if symptoms)",
        "Management of tamoxifen-associated hyperplasia: follow standard GTG67 pathway; consider switching to aromatase inhibitor with oncology team",
        "Any abnormal uterine bleeding in a woman on tamoxifen warrants prompt investigation (hysteroscopy ± biopsy)",
      ]},
    ],
  },
];
