// GTG73 — Preterm Prelabour Rupture of Membranes
// RCOG Green-Top Guideline No. 73 (November 2019)

export const GTG73_SECTIONS = [
  {
    id: "gtg73-overview",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Obstetric",
    title: "Overview, Definitions & Epidemiology",
    tags: [
      "pprom", "srom", "prelabour rupture of membranes", "preterm", "membrane rupture",
      "gtg73", "rcog", "green top guideline", "preterm birth", "preterm labour",
      "chorioamnionitis", "infection", "amniotic fluid", "liquor", "gestation",
      "prelabour", "premature rupture", "prom", "preterm prom",
    ],
    content: [
      { type: "text", value: "RCOG Green-Top Guideline No. 73 (November 2019) covers the management of preterm prelabour rupture of membranes (PPROM). PPROM is defined as spontaneous rupture of the membranes before 37+0 weeks of gestation, before the onset of labour." },
      { type: "alert", value: "PPROM complicates approximately 2–3% of pregnancies and is associated with 30–40% of all preterm births. It is a major cause of neonatal morbidity and mortality." },
      { type: "subheading", value: "Definitions" },
      { type: "list", items: [
        "PPROM: rupture of membranes before 37+0 weeks, before onset of labour",
        "Term SROM: spontaneous rupture of membranes at or after 37+0 weeks before onset of labour",
        "Latency period: time between membrane rupture and onset of labour",
        "Chorioamnionitis: infection of the chorion and amnion — can be clinical or subclinical",
      ]},
      { type: "subheading", value: "Risk Factors" },
      { type: "list", items: [
        "Previous PPROM — strongest individual risk factor",
        "Cervical weakness or short cervix on USS",
        "Genital tract infection (GBS, BV, chlamydia)",
        "Amniocentesis or other uterine instrumentation",
        "Cervical cerclage in situ",
        "Antepartum haemorrhage",
        "Smoking, low BMI, poor nutritional status",
        "Multiple pregnancy (risk of membrane rupture from one sac)",
      ]},
      { type: "subheading", value: "History — Key Points to Elicit" },
      { type: "list", items: [
        "Onset, character and amount of fluid loss — sudden gush vs slow trickle; ongoing or settled",
        "Colour and odour of fluid — clear, blood-stained, green (meconium), or offensive",
        "Exact gestation — confirm EDD, confirm dating USS",
        "Fetal movements since rupture",
        "Uterine contractions or abdominal pain",
        "Cervical cerclage in situ — document; plan removal once PPROM confirmed",
        "GBS status — known positive swab at any point in this pregnancy",
        "Risk factors for chorioamnionitis: previous PPROM, recent vaginal examination, recent cervical instrumentation",
      ]},
    ],
  },

  {
    id: "gtg73-diagnosis",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Acute",
    title: "Diagnosis & Confirmation of Membrane Rupture",
    tags: [
      "pprom diagnosis", "speculum examination pprom", "pooling amniotic fluid",
      "igfbp-1", "pamg-1", "actimprom", "amnisure", "membrane rupture confirmation",
      "digital vaginal examination pprom", "swab pprom", "hvs pprom",
      "amniotic fluid colour", "fern test", "ph test", "nitrazine",
      "srom diagnosis", "liquor pooling", "posterior fornix", "confirmatory test",
    ],
    content: [
      { type: "text", value: "Diagnosis of PPROM is primarily clinical based on history and sterile speculum examination. Confirmatory biochemical tests may be used when the diagnosis is uncertain." },
      { type: "alert", value: "Do NOT perform a digital vaginal examination in suspected PPROM — this significantly increases the risk of ascending infection and shortens the latency period. [Grade B]" },
      { type: "subheading", value: "Sterile Speculum Examination" },
      { type: "list", items: [
        "Visualise pooling of amniotic fluid in the posterior fornix — high specificity for PPROM",
        "Inspect colour and odour of liquor — green or offensive fluid raises concern for infection",
        "Assess cervical dilatation — note if cervix is open",
        "Send HVS for MC&S including GBS",
        "Do NOT perform a digital examination",
      ]},
      { type: "subheading", value: "Confirmatory Tests When Speculum Is Inconclusive" },
      { type: "list", items: [
        "IGFBP-1 (ActimPROM) or PAMG-1 (AmniSure) swabs — high sensitivity and specificity for amniotic fluid",
        "Nitrazine / pH testing — high false-positive rate (blood, semen, BV elevate pH); less reliable",
        "Ferning test — amniotic fluid crystallises in a fern pattern on drying; limited evidence in PPROM",
        "USS for reduced amniotic fluid volume — supports diagnosis but absence of oligohydramnios does not exclude PPROM",
      ]},
      { type: "subheading", value: "Key Investigations" },
      { type: "list", items: [
        "CTG — confirm fetal wellbeing; assess for fetal tachycardia or decelerations",
        "FBC — white cell count >17 × 10⁹/L raises concern for infection",
        "CRP — raised CRP >10 mg/L raises concern; trend over time more informative than single value",
        "HVS for MC&S including GBS — results may take 48 hours",
        "MSU — exclude UTI as a precipitant",
        "USS — confirm fetal presentation, placental site, amniotic fluid volume (AFI or deepest vertical pool), estimated fetal weight",
      ]},
    ],
  },

  {
    id: "gtg73-previable",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Consultant-led",
    title: "PPROM Before 24 Weeks (Pre-viable)",
    tags: [
      "pprom 24 weeks", "pprom previable", "pprom periviable", "pre-viable pprom",
      "pulmonary hypoplasia pprom", "limb deformities pprom", "prognosis pprom early",
      "survival pprom", "potter sequence", "renal agenesis", "oligohydramnios pprom",
      "termination pprom", "expectant management pprom", "pprom counselling",
      "pprom before viability", "22 weeks pprom", "23 weeks pprom", "24 weeks pprom",
    ],
    content: [
      { type: "text", value: "PPROM before 24 weeks of gestation is associated with very high rates of neonatal morbidity and mortality. Prognosis depends on the gestation at rupture, the extent of membrane rupture, and the degree of oligohydramnios." },
      { type: "alert", value: "PPROM before viability requires immediate consultant obstetrician involvement and joint counselling with neonatology. Do not manage pre-viable PPROM without senior support." },
      { type: "subheading", value: "Fetal Complications of Early PPROM" },
      { type: "list", items: [
        "Pulmonary hypoplasia — lungs fail to develop fully without adequate amniotic fluid for breathing movements; most significant risk when PPROM occurs before 22–26 weeks",
        "Limb positional deformities (contractures) — oligohydramnios limits fetal movement",
        "Potter sequence (in severe oligohydramnios) — pulmonary hypoplasia, limb deformities, facial compression",
        "Preterm delivery — median latency from PPROM to delivery at this gestation is 1–4 weeks",
        "Chorioamnionitis — rate of >50% before delivery in pre-viable PPROM",
      ]},
      { type: "subheading", value: "Management" },
      { type: "list", items: [
        "Involve consultant obstetrician and neonatology/neonatal intensive care team immediately",
        "Offer full parental counselling on prognosis — survival, disability, and quality of life",
        "Full infection screen: FBC, CRP, HVS for MC&S, MSU",
        "Serial USS for amniotic fluid volume and fetal growth",
        "Options include: expectant management, termination of pregnancy, or comfort care — shared patient decision required",
        "Document counselling in full; involve clinical psychologist or bereavement midwife if appropriate",
      ]},
      { type: "subheading", value: "Cerclage Removal" },
      { type: "text", value: "If a cervical cerclage is in situ at the time of PPROM, the decision to remove it should be made by a consultant obstetrician. There is no strong evidence to guide the optimal timing, and the risk of infection from retaining the cerclage must be weighed against the risk of precipitating delivery by removal." },
    ],
  },

  {
    id: "gtg73-infection",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Acute / Intrapartum",
    title: "Infection, Chorioamnionitis & Meconium",
    tags: [
      "chorioamnionitis pprom", "infection pprom", "clinical chorioamnionitis",
      "maternal pyrexia pprom", "maternal tachycardia pprom", "fetal tachycardia pprom",
      "uterine tenderness pprom", "offensive liquor pprom", "wcc pprom", "crp pprom",
      "white cell count pprom", "c-reactive protein pprom", "infection markers pprom",
      "chorioamnionitis diagnosis", "chorioamnionitis treatment", "iv antibiotics pprom",
      "expedite delivery chorioamnionitis", "meconium pprom", "meconium stained liquor",
      "green liquor pprom", "subclinical chorioamnionitis",
    ],
    content: [
      { type: "text", value: "Chorioamnionitis (infection of the chorion and amnion) is the most serious immediate complication of PPROM. It may be subclinical (positive cultures without symptoms) or clinical. Clinical chorioamnionitis requires immediate action." },
      { type: "alert", value: "Clinical chorioamnionitis = expedite delivery regardless of gestation. Do not await further investigation results before starting IV antibiotics." },
      { type: "subheading", value: "Clinical Chorioamnionitis — Diagnostic Criteria" },
      { type: "text", value: "Diagnosis is clinical, based on a combination of features. No single marker is diagnostic alone." },
      { type: "list", items: [
        "Maternal pyrexia ≥37.5°C (persistent or recurrent) — most sensitive single marker",
        "Maternal tachycardia >100 bpm",
        "Fetal tachycardia >160 bpm on CTG",
        "Uterine tenderness on palpation",
        "Offensive or discoloured (green/brown) amniotic fluid on speculum",
        "Raised WCC >17 × 10⁹/L — useful but not specific in isolation",
        "Raised CRP >10 mg/L — more useful as a trend than a single value",
      ]},
      { type: "subheading", value: "Management of Clinical Chorioamnionitis" },
      { type: "list", items: [
        "Call registrar immediately — senior obstetric involvement required",
        "IV broad-spectrum antibiotics without delay — do not wait for culture results",
        "Expedite delivery by the most appropriate route — continuous CTG monitoring in labour",
        "Continuous maternal observations: temperature, HR, BP at minimum hourly",
        "Neonatology team to attend delivery",
        "Placental swabs and blood cultures at delivery — guide postnatal antibiotic rationalisation",
      ]},
      { type: "subheading", value: "Meconium-Stained Liquor" },
      { type: "list", items: [
        "Fresh, thick meconium raises concern for fetal compromise — escalate immediately",
        "Offensive or discoloured (green/brown) liquor without typical meconium may indicate infection",
        "Continuous CTG and urgent FBC/CRP if green or offensive liquor noted on speculum",
        "Meconium at any gestation warrants urgent CTG and senior review",
      ]},
      { type: "subheading", value: "Monitoring Schedule to Detect Evolving Infection" },
      { type: "list", items: [
        "Maternal temperature, HR, and BP minimum 4-hourly",
        "Daily FBC and CRP during inpatient management",
        "CTG at minimum twice daily — more frequently if clinical concern",
        "Regular clinical assessment for uterine tenderness and change in liquor",
      ]},
    ],
  },

  {
    id: "gtg73-antibiotics",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Inpatient",
    title: "Antibiotic Prophylaxis in PPROM (ORACLE I)",
    tags: [
      "antibiotics pprom", "erythromycin pprom", "oracle i pprom", "antibiotic prophylaxis pprom",
      "co-amoxiclav pprom", "augmentin pprom", "nec pprom", "necrotising enterocolitis pprom",
      "benzylpenicillin pprom", "gbs antibiotics pprom", "penicillin pprom",
      "antibiotic duration pprom", "oral erythromycin pprom", "pprom antibiotic dose",
      "pprom antibiotic guideline", "pprom treatment antibiotic",
    ],
    content: [
      { type: "text", value: "The ORACLE I trial (Kenyon et al, Lancet 2001) remains the evidence base for antibiotic prophylaxis in PPROM. Erythromycin prolongs the latency period, reduces maternal and neonatal morbidity, and reduces need for mechanical ventilation, major cerebral abnormality, and postnatal surfactant." },
      { type: "alert", value: "Do NOT use co-amoxiclav (Augmentin) in PPROM — ORACLE I showed increased rates of neonatal necrotising enterocolitis (NEC) with co-amoxiclav. [Grade A evidence]" },
      { type: "subheading", value: "Recommended Antibiotic Regimen" },
      { type: "list", items: [
        "Erythromycin 250 mg orally four times daily for 10 days OR until established labour, whichever is sooner",
        "If penicillin is being given for GBS prophylaxis, erythromycin can be discontinued",
        "Co-amoxiclav is contraindicated in PPROM due to NEC risk",
        "Clindamycin may be used if erythromycin is not tolerated (no RCT evidence, but local protocols may specify alternative)",
      ]},
      { type: "subheading", value: "GBS Intrapartum Prophylaxis" },
      { type: "list", items: [
        "Women with known GBS colonisation in this pregnancy should receive IV benzylpenicillin in active labour",
        "Benzylpenicillin 3 g IV loading dose, then 1.5 g IV every 4 hours until delivery",
        "If penicillin allergy: discuss with microbiologist; clindamycin or vancomycin per local protocol",
        "Neonatology team should be informed of GBS status prior to delivery",
      ]},
      { type: "subheading", value: "Corticosteroids" },
      { type: "list", items: [
        "Betamethasone 12 mg IM × 2 doses, 24 hours apart — recommended for all women with PPROM at 24+0 to 34+6 weeks",
        "Corticosteroids significantly reduce rates of respiratory distress syndrome (RDS), IVH, and NEC",
        "Consider up to 35+6 weeks in the late preterm period (discuss with senior)",
        "Do not delay delivery in clinical chorioamnionitis to complete a course of corticosteroids",
      ]},
      { type: "subheading", value: "Magnesium Sulphate for Neuroprotection" },
      { type: "list", items: [
        "Consider magnesium sulphate for neuroprotection when delivery is anticipated before 30+0 weeks",
        "Per NG25/NICE: consider up to 33+6 weeks — refer to local protocol",
        "Reduces rates of cerebral palsy and death in preterm neonates",
        "Administer per local trust protocol (dose, monitoring, duration)",
      ]},
    ],
  },

  {
    id: "gtg73-preterm",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Inpatient",
    title: "Management — Preterm PPROM (24+0 to 33+6 Weeks)",
    tags: [
      "pprom management preterm", "pprom 24 weeks", "pprom 33 weeks", "pprom admit",
      "pprom inpatient", "pprom expectant management", "pprom monitoring",
      "pprom ctg", "pprom fbc", "pprom crp", "pprom digital examination",
      "pprom corticosteroids", "pprom betamethasone", "pprom magnesium sulphate",
      "pprom neuroprotection", "pprom latency", "pprom delivery timing",
    ],
    content: [
      { type: "text", value: "PPROM at 24+0 to 33+6 weeks requires inpatient management. Expectant management aims to prolong the pregnancy until 37+0 weeks or until complications necessitate delivery." },
      { type: "alert", value: "Do NOT perform digital vaginal examination in PPROM — this significantly shortens the latency period and increases infection risk. [Grade B]" },
      { type: "subheading", value: "Immediate Management (24+0–33+6 Weeks)" },
      { type: "list", items: [
        "Admit to hospital — inpatient management throughout latency period",
        "Antibiotics — erythromycin 250 mg QDS × 10 days (ORACLE I; co-amoxiclav contraindicated)",
        "Corticosteroids — betamethasone 12 mg IM × 2 doses, 24 hours apart",
        "Magnesium sulphate — if delivery anticipated before 30+0 weeks, for fetal neuroprotection; per local protocol",
        "Inform neonatology team of gestation and clinical status",
        "Expectant management until 37+0 weeks if no signs of infection or fetal compromise",
        "Tocolysis — not recommended in PPROM (may mask signs of chorioamnionitis)",
        "Do NOT perform digital vaginal examination",
      ]},
      { type: "subheading", value: "Ongoing Monitoring Schedule" },
      { type: "list", items: [
        "Maternal observations minimum 4-hourly: temperature, HR, BP, RR",
        "Daily FBC and CRP — trend over time is more informative than a single value",
        "CTG at minimum twice daily — more frequently if clinical concern",
        "Weekly USS for liquor volume and fetal growth",
        "Reassess GBS status if not known — HVS for MC&S",
      ]},
      { type: "subheading", value: "Indications for Delivery (Preterm)" },
      { type: "list", items: [
        "Clinical chorioamnionitis — expedite delivery regardless of gestation",
        "Fetal compromise on CTG or USS",
        "Heavy antepartum haemorrhage",
        "Established preterm labour",
        "Cord prolapse — obstetric emergency",
        "Maternal decision after informed counselling",
      ]},
    ],
  },

  {
    id: "gtg73-late-preterm",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal — Inpatient",
    title: "Management — Late Preterm PPROM (34+0 to 36+6 Weeks)",
    tags: [
      "pprom 34 weeks", "pprom 36 weeks", "late preterm pprom", "pprom late preterm",
      "pprom iol", "pprom expectant 34 weeks", "pprom delivery 34 weeks",
      "late preterm corticosteroids pprom", "pprom antibiotics 34 weeks",
      "pprom shared decision", "pprom 35 weeks",
    ],
    content: [
      { type: "text", value: "PPROM at 34+0 to 36+6 weeks requires hospital admission and shared decision-making between the clinical team and the patient regarding timing of delivery vs expectant management." },
      { type: "subheading", value: "Management" },
      { type: "list", items: [
        "Admit to hospital",
        "Antibiotics — per local trust protocol; erythromycin basis applies but evidence less strong at this gestation",
        "Corticosteroids — consider up to 35+6 weeks; weigh risks vs benefits; discuss with senior",
        "Discuss with patient: expectant management (until 37+0 weeks if no infection) vs IOL — shared decision-making",
        "No routine IOL below 34+0 weeks without infection or fetal compromise",
        "Document informed decision including risks of expectant management (infection, cord prolapse) and of preterm delivery",
      ]},
      { type: "subheading", value: "Monitoring" },
      { type: "list", items: [
        "Maternal observations minimum 4-hourly: temperature, HR, BP",
        "Daily FBC and CRP",
        "CTG at minimum twice daily",
        "Escalate promptly if any signs of chorioamnionitis appear",
      ]},
    ],
  },

  {
    id: "gtg73-term",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal / Intrapartum",
    title: "Management — Term SROM (≥37 Weeks) Including GBS",
    tags: [
      "term srom", "srom 37 weeks", "srom term", "gbs term srom",
      "gbs srom iol", "benzylpenicillin srom", "iol after srom",
      "expectant management srom term", "srom 24 hours", "prelabour rupture term",
      "gbs positive labour", "gbs prophylaxis intrapartum", "continuous efm srom",
      "gbs negative srom", "srom management", "prom term",
    ],
    content: [
      { type: "text", value: "Term SROM (at or after 37+0 weeks) differs from PPROM in that the fetus is mature and timing of delivery is the primary clinical decision. GBS colonisation status is the key determinant of management." },
      { type: "subheading", value: "GBS-Positive Women (Term SROM)" },
      { type: "list", items: [
        "Offer immediate induction of labour or caesarean birth — do not allow prolonged expectant management",
        "IV intrapartum antibiotic prophylaxis (IAP): benzylpenicillin 3 g IV loading dose, then 1.5 g IV every 4 hours until delivery",
        "Continuous electronic fetal monitoring (EFM) in labour",
        "Neonatology review after birth — observe neonate for ≥12 hours",
        "Penicillin allergy: discuss with microbiologist; alternatives per local protocol (clindamycin or vancomycin)",
      ]},
      { type: "subheading", value: "GBS-Negative or Unknown Women (Term SROM)" },
      { type: "list", items: [
        "Discuss expectant management vs IOL with patient — patient preference is important",
        "Most units offer IOL if not in established labour within 24 hours of membrane rupture",
        "IV antibiotics in labour if clinical chorioamnionitis develops — do not give prophylactically without indication",
        "Continuous EFM in labour",
        "If expectant: 4-hourly maternal observations (temperature, HR, BP); FHR assessment regularly",
        "Advise patient to report: fever, offensive or discoloured liquor, reduced fetal movements, abdominal pain",
      ]},
      { type: "subheading", value: "Monitoring During Expectant Management at Term" },
      { type: "list", items: [
        "Maternal temperature and HR minimum 4-hourly — pyrexia ≥37.5°C warrants urgent review",
        "Fetal heart assessment at every check — apply CTG if any concern",
        "Reassess at 24 hours — if not in labour, discuss IOL; expectant beyond 24 hours is associated with rising infection rates",
        "Report immediately: offensive or discoloured liquor, fever, maternal or fetal tachycardia, abdominal pain",
      ]},
    ],
  },

  {
    id: "gtg73-escalation",
    gl: "GTG73",
    condition: "Preterm Prelabour Rupture of Membranes",
    setting: "Antenatal / Intrapartum",
    title: "Escalation Criteria & When to Call the Senior",
    tags: [
      "pprom escalation", "pprom registrar", "pprom senior review", "pprom emergency",
      "cord prolapse pprom", "chorioamnionitis escalate", "pprom deterioration",
      "pprom aph", "pprom labour", "pprom ctg abnormal", "pprom labour established",
      "pprom falling liquor", "pprom distress", "meconium escalation", "pprom review",
    ],
    content: [
      { type: "text", value: "In PPROM, the clinical situation can change rapidly. A low threshold for escalation to a senior obstetrician is essential throughout the latency period and labour." },
      { type: "subheading", value: "Escalate Immediately to Registrar or Consultant If:" },
      { type: "list", items: [
        "Signs of chorioamnionitis — maternal pyrexia, tachycardia (maternal or fetal), uterine tenderness, offensive liquor",
        "Abnormal or suspicious CTG at any stage",
        "Cord prolapse visualised on speculum — obstetric emergency; call 2222",
        "Significant antepartum haemorrhage — activate major haemorrhage protocol if massive",
        "Meconium-stained liquor — fresh, thick meconium suggests fetal compromise",
        "Patient in established preterm labour at any gestation",
        "Rapidly falling amniotic fluid volume on USS (oligohydramnios developing acutely)",
        "Patient requesting delivery — requires senior shared decision-making",
        "Patient deteriorating or in pain not explained by uterine activity",
      ]},
    ],
  },
];
