// NG137 — Twin and Triplet Pregnancy
// (NICE Guideline NG137, published 4 September 2019, updated 2024, together
// with its companion Quality Standard QS46 — QS46's eight quality
// statements are the audit-facing distillation of this same guideline, not
// a separate source, so both live on one page here rather than two.)

export const NG137_SECTIONS = [
  {
    id: "ng137-overview",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "General — Antenatal",
    title: "Quality Statements Overview",
    tags: [
      "multiple pregnancy", "twins", "triplets", "twin pregnancy", "triplet pregnancy",
      "multiple birth", "qs46", "nice", "quality standard", "ng137",
      "monochorionic", "dichorionic", "trichorionic", "antenatal care",
    ],
    content: [
      { type: "text", value: "NICE Quality Standard QS46, based on this guideline (NG137), sets 8 quality statements for the care of women with twin and triplet pregnancies — a useful checklist for what a well-run multiple pregnancy pathway should guarantee." },
      { type: "subheading", value: "The 8 Quality Statements" },
      { type: "list", items: [
        "1: Chorionicity and amnionicity determined by ultrasound between 11+2 and 14+1 weeks",
        "2: Fetuses labelled by ultrasound between 11+2 and 14+1 weeks",
        "3: Care provided by a multidisciplinary core team",
        "4: Individualised care plan based on chorionicity and amnionicity",
        "5: Monitoring for fetal complications per chorionicity and amnionicity",
        "6: Consultant from tertiary fetal medicine centre involved for higher-risk or complicated pregnancies",
        "7: Discussion of preterm labour risks by 24 weeks",
        "8: Discussion of timing and mode of birth by 28 weeks, with agreed birth plan",
      ]},
    ],
  },

  {
    id: "ng137-chorionicity-amnionicity",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — First Trimester",
    flowchartId: "QS46_CARE_PATHWAY",
    title: "Chorionicity & Amnionicity",
    tags: [
      "chorionicity", "amnionicity", "monochorionic", "dichorionic", "trichorionic",
      "monoamniotic", "diamniotic", "triamniotic", "shared placenta",
      "twin pregnancy", "triplet", "multiple pregnancy", "ultrasound", "dating scan",
      "11 weeks", "14 weeks", "lambda sign", "t-sign", "membrane thickness",
      "placenta", "amniotic sac", "first trimester scan",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must have chorionicity and amnionicity determined by ultrasound and recorded between 11+2 weeks and 14+1 weeks." },
      { type: "alert", value: "Accurate determination of chorionicity is critical — monochorionic pregnancies carry higher risks due to shared placentation." },
      { type: "subheading", value: "Chorionicity" },
      { type: "text", value: "The number of chorionic (outer) membranes surrounding babies:" },
      { type: "list", items: [
        "1 membrane = Monochorionic — higher risk due to shared placenta",
        "2 membranes = Dichorionic",
        "3 membranes = Trichorionic",
      ]},
      { type: "subheading", value: "Amnionicity" },
      { type: "text", value: "The number of amnions (inner membranes) surrounding babies:" },
      { type: "list", items: [
        "1 amnion = Monoamniotic",
        "2 amnions = Diamniotic",
        "3 amnions = Triamniotic",
      ]},
      { type: "subheading", value: "Ultrasound Determination" },
      { type: "text", value: "Chorionicity is assessed on ultrasound using: number of placental masses, Lambda or T-sign, presence and thickness of amniotic membrane(s)." },
      { type: "subheading", value: "Recording Requirements" },
      { type: "list", items: [
        "Documented in the ultrasound report",
        "Electronic copy and image (Lambda/T-sign) stored on radiology/PACS system",
        "Hard copy placed in hand-held maternity notes and hospital notes",
      ]},
    ],
  },

  {
    id: "ng137-labelling-fetuses",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — First Trimester",
    title: "Labelling the Fetuses",
    tags: [
      "fetus labelling", "fetal labelling", "label fetuses", "identify fetuses",
      "twin pregnancy", "triplet", "multiple pregnancy", "ultrasound", "dating scan",
      "11 weeks", "14 weeks", "left right", "upper lower", "lateral orientation",
      "vertical orientation", "fetal identification", "consistent labelling",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must have their fetuses labelled using ultrasound and recorded between 11+2 weeks and 14+1 weeks." },
      { type: "subheading", value: "Why Label?" },
      { type: "text", value: "Labelling at the dating scan ensures consistent identification throughout pregnancy. Numbering (Twin 1, Twin 2) can cause confusion — particularly for left and right fetuses — as the 'leading' fetus may change." },
      { type: "subheading", value: "Labelling Method" },
      { type: "list", items: [
        "Use lateral orientation: Left (L) and Right (R)",
        "OR use vertical orientation: Upper and Lower",
        "The same labelling method must be used at every subsequent scan",
      ]},
      { type: "subheading", value: "Documentation" },
      { type: "list", items: [
        "Documented in the ultrasound report",
        "Electronic copy and image stored on PACS",
        "Hard copy placed in hand-held maternity notes and hospital notes",
      ]},
    ],
  },

  {
    id: "ng137-mdt-core-team",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — Ongoing",
    title: "Multidisciplinary Core Team",
    tags: [
      "mdt", "multidisciplinary", "core team", "specialist obstetrician", "specialist midwife",
      "ultrasonographer", "multiple pregnancy", "twin", "triplet", "team care",
      "continuity of care", "twin clinic", "antenatal care", "mental health", "nutrition",
      "breastfeeding", "parenting support",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must be cared for by a multidisciplinary core team (MDT) of named specialists." },
      { type: "subheading", value: "MDT Composition" },
      { type: "list", items: [
        "Specialist obstetrician — with special interest, experience and knowledge of multiple pregnancy",
        "Specialist midwife — with special interest, experience and knowledge of multiple pregnancy",
        "Ultrasonographer — with postgraduate certificate in obstetric ultrasound",
      ]},
      { type: "subheading", value: "MDT Responsibilities" },
      { type: "list", items: [
        "Minimise number of hospital visits",
        "Provide care as close to the woman's home as possible",
        "Provide continuity of care within and between hospitals and the community",
        "May refer women to community midwifery team for some additional antenatal appointments",
      ]},
      { type: "subheading", value: "Information & Support to Offer" },
      { type: "list", items: [
        "Antenatal and postnatal mental health and wellbeing",
        "Antenatal nutrition",
        "Risks, symptoms and signs of preterm labour and potential need for corticosteroids",
        "Likely timing and possible modes of delivery",
        "Breastfeeding",
        "Parenting",
      ]},
    ],
  },

  {
    id: "ng137-care-plan",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — Ongoing",
    title: "Care Planning",
    tags: [
      "care plan", "care planning", "antenatal appointments", "schedule", "appointment schedule",
      "multiple pregnancy", "twin", "triplet", "chorionicity", "amnionicity",
      "mdt appointments", "specialist appointments", "twins trust", "proforma",
      "antenatal care pathway",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must have an individualised care plan specifying the timing of MDT appointments appropriate for the chorionicity and amnionicity of their pregnancy." },
      { type: "text", value: "The care plan should be provided at determination of chorionicity." },
      { type: "subheading", value: "Care Plan Contents" },
      { type: "list", items: [
        "Expected number of antenatal appointments",
        "Who each appointment is with (specialist name/role)",
        "Where appointments will take place",
        "Schedule of specialist appointments per chorionicity and amnionicity",
      ]},
      { type: "subheading", value: "Additional Community Appointments" },
      { type: "text", value: "Women may have additional appointments with neonatal unit staff, community midwives and GPs — coordinated by the MDT." },
      { type: "alert", value: "The number of appointments and scans depends on chorionicity, amnionicity and any associated risk factors or complications." },
    ],
  },

  {
    id: "ng137-fetal-monitoring",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — Ongoing",
    title: "Monitoring for Fetal Complications",
    tags: [
      "fetal monitoring", "fetal complications", "fetal growth restriction", "fgr", "iugr",
      "fetal weight discordance", "weight discordance", "growth discordance",
      "ttts", "twin to twin transfusion", "feto-fetal transfusion", "ffts",
      "monochorionic monitoring", "dichorionic monitoring", "ultrasound surveillance",
      "biometry", "biometric parameters", "head circumference", "abdominal circumference",
      "femoral length", "amniotic fluid", "amniotic fluid index", "multiple pregnancy",
      "16 weeks", "24 weeks", "fortnightly scan", "every 14 days",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must be monitored for fetal complications according to the chorionicity and amnionicity of their pregnancy." },
      { type: "alert", value: "Fetal growth restriction is more likely in monochorionic and dichorionic pregnancies. Feto-fetal transfusion syndrome (FFTS/TTTS) is a risk specific to monochorionic pregnancies." },
      { type: "subheading", value: "Monochorionic Pregnancies — from 16 weeks" },
      { type: "list", items: [
        "Ultrasound every 14 days (fortnightly) from 16 weeks until birth for FFTS surveillance",
        "At each scan: 2+ biometric parameters AND amniotic fluid level assessment for fetal weight discordance",
      ]},
      { type: "subheading", value: "Dichorionic Twin / Trichorionic Triplet — from 24 weeks" },
      { type: "list", items: [
        "At each ultrasound: 2+ biometric parameters AND amniotic fluid levels for fetal weight discordance",
      ]},
      { type: "subheading", value: "Fetal Biometric Parameters" },
      { type: "list", items: [
        "Head circumference (HC)",
        "Abdominal circumference (AC)",
        "Femoral length (FL)",
      ]},
      { type: "subheading", value: "Fetal Growth Restriction Definition" },
      { type: "text", value: "Clinically significant if: weight discordance ≥25% between twins/triplets, OR estimated fetal weight (EFW) of any baby below the 10th centile for gestational age." },
      { type: "subheading", value: "Feto-Fetal Transfusion Syndrome (FFTS / TTTS)" },
      { type: "text", value: "Blood moves from donor baby to recipient baby via shared placental circulation. A complication of monochorionic pregnancies only — see the staging section below for how this shapes referral." },
    ],
  },

  {
    id: "ng137-tertiary-referral",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — High Risk",
    flowchartId: "QS46_TERTIARY",
    title: "Tertiary Fetal Medicine Centre Involvement",
    tags: [
      "tertiary referral", "fetal medicine", "fetal medicine centre", "fmc", "tertiary centre",
      "higher risk multiple pregnancy", "complicated multiple pregnancy",
      "monochorionic monoamniotic", "dcda triplets", "mcda triplets", "mcma triplets",
      "ttts", "ffts", "twin to twin transfusion", "fetal anomaly", "discordant fetal death",
      "trap sequence", "twin reverse arterial perfusion", "conjoined twins",
      "taps", "twin anaemia polycythaemia sequence", "fetoscopic laser", "laser ablation",
      "selective termination", "cord occlusion", "radiofrequency ablation", "rfa",
      "weight discordance", "fetal weight discordance",
    ],
    content: [
      { type: "text", value: "Women with a higher-risk or complicated multiple pregnancy must have a consultant from a tertiary level fetal medicine centre (FMC) involved in their care." },
      { type: "subheading", value: "Higher-Risk Multiple Pregnancies" },
      { type: "list", items: [
        "Monochorionic monoamniotic (MCMA) twins",
        "Dichorionic diamniotic (DCDA) triplets",
        "Monochorionic diamniotic (MCDA) triplets",
        "Monochorionic monoamniotic (MCMA) triplets",
      ]},
      { type: "subheading", value: "Complicated Multiple Pregnancies" },
      { type: "list", items: [
        "Fetal weight discordance ≥25% AND EFW below 10th centile",
        "Fetal anomaly (structural or chromosomal)",
        "Discordant fetal death",
        "Feto-fetal transfusion syndrome (FFTS/TTTS)",
        "Twin reverse arterial perfusion sequence (TRAP)",
        "Conjoined twins or triplets",
        "Suspected twin anaemia polycythaemia sequence (TAPS)",
      ]},
      { type: "subheading", value: "What Involvement Means" },
      { type: "text", value: "The consultant can be involved by seeking an opinion (recording the discussion in the notes) OR by formal referral to the FMC. The aim is to access specialist expertise while maintaining care locally where possible." },
      { type: "subheading", value: "Tertiary FMC Capabilities" },
      { type: "list", items: [
        "Fetoscopic laser ablation for FFTS",
        "Selective termination using fetoscopic cord occlusion",
        "Radiofrequency ablation (RFA)",
        "Complex fetal interventions and therapies",
      ]},
    ],
  },

  {
    id: "ng137-ttts-staging",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — Complications",
    title: "TTTS Staging & Other Monochorionic Complications",
    tags: [
      "ttts staging", "quintero staging", "twin to twin transfusion syndrome",
      "selective fetal growth restriction", "sfgr", "taps", "fetoscopic laser ablation",
    ],
    content: [
      { type: "text", value: "The sections above cover the surveillance schedule and tertiary referral triggers for these complications; this adds the staging detail that shapes the management conversation once a complication is suspected." },
      { type: "subheading", value: "Twin-to-twin transfusion syndrome (TTTS) — Quintero staging" },
      { type: "table",
        headers: ["Stage", "Features"],
        rows: [
          ["I", "Oligohydramnios/polyhydramnios sequence; donor's bladder still visible; normal Dopplers"],
          ["II", "Donor's bladder not visible; Dopplers still normal"],
          ["III", "Critically abnormal Doppler waveforms (either twin)"],
          ["IV", "Hydrops in either twin"],
          ["V", "Death of one or both twins"],
        ],
      },
      { type: "alert", value: "Stage II or higher, identified before around 26 weeks, is the usual threshold for considering fetoscopic laser ablation at a tertiary fetal medicine centre — refer promptly rather than waiting for progression once TTTS is suspected." },
      { type: "subheading", value: "Selective fetal growth restriction (sFGR)" },
      { type: "text", value: "Growth discordance in a monochorionic pregnancy behaves differently from dichorionic FGR because of the shared circulation — the growth-restricted twin's Doppler pattern (and its variability) drives risk and monitoring frequency more than the discordance percentage alone. Manage jointly with the tertiary fetal medicine centre once identified (see the discordance thresholds above)." },
      { type: "subheading", value: "Twin anaemia polycythaemia sequence (TAPS)" },
      { type: "text", value: "A more subtle, slower variant of inter-twin transfusion without the amniotic fluid discordance of TTTS — suspected from middle cerebral artery Doppler differences between the twins (one showing signs of anaemia, the other of polycythaemia). Refer to the tertiary centre in the same way as suspected TTTS." },
    ],
  },

  {
    id: "ng137-preterm-birth-advice",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — 24 Weeks",
    title: "Preterm Birth — Advice by 24 Weeks",
    tags: [
      "preterm birth", "preterm labour", "premature birth", "premature labour",
      "preterm", "multiple pregnancy", "twin", "triplet", "signs of labour",
      "symptoms preterm labour", "24 weeks", "corticosteroids", "steroids",
      "fetal lung maturation", "betamethasone", "neonatal unit", "nicu", "scbu",
      "contractions", "ruptured membranes", "backache", "neonatal network",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must have a discussion by 24 weeks with one or more MDT members about the risks, signs and symptoms of preterm labour and possible outcomes of preterm birth." },
      { type: "alert", value: "~60 in 100 twin pregnancies deliver by 37 weeks. ~75 in 100 triplet pregnancies deliver by 35 weeks." },
      { type: "subheading", value: "Signs & Symptoms of Preterm Labour" },
      { type: "list", items: [
        "More frequent and regular contractions",
        "Ruptured membranes",
        "Unusual or severe backache or other pain",
      ]},
      { type: "subheading", value: "Topics to Cover" },
      { type: "list", items: [
        "Risks of preterm birth in multiple pregnancy",
        "Signs and symptoms to watch for — and who to contact quickly",
        "Benefits and risks of targeted corticosteroids for fetal lung maturation",
        "Possible need for admission to a neonatal unit (NICU/SCBU)",
        "Role of neonatal networks",
        "Neonatal unit staff should be involved in discussion where possible",
      ]},
    ],
  },

  {
    id: "ng137-birth-plan",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal — 28 Weeks",
    title: "Preparation for Birth & Birth Plan",
    tags: [
      "birth plan", "mode of delivery", "mode of birth", "timing of birth",
      "multiple pregnancy", "twin", "triplet", "28 weeks", "caesarean section",
      "vaginal delivery", "vaginal birth", "elective delivery", "delivery planning",
      "twin delivery", "triplet delivery", "birth discussion", "informed decision",
    ],
    content: [
      { type: "text", value: "Women with a multiple pregnancy must have a discussion by 28 weeks with one or more MDT members about the timing of birth and possible modes of delivery so that a birth plan can be agreed." },
      { type: "alert", value: "Most women with multiple pregnancies deliver by 37 weeks — either spontaneously or electively. Birth planning should happen well in advance." },
      { type: "subheading", value: "Discussion Should Include" },
      { type: "list", items: [
        "Likely timing of birth (expected gestation by chorionicity/amnionicity — see below for the specific recommended windows)",
        "Risks and benefits of different modes of birth (vaginal vs caesarean — see below)",
        "How different modes of delivery are managed",
        "Risk of admission to neonatal unit with preterm birth",
        "Women's preferences — to enable an informed birth plan",
      ]},
      { type: "subheading", value: "Agreed Birth Plan" },
      { type: "text", value: "An agreed birth plan should be documented by 28 weeks. Women should feel well informed and able to make decisions that reflect what is important to them." },
    ],
  },

  {
    id: "ng137-timing-of-birth",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Antenatal",
    title: "Timing of Birth",
    tags: [
      "twin timing of birth", "triplet timing of birth", "dichorionic diamniotic timing",
      "monochorionic diamniotic timing", "monoamniotic timing", "elective birth twins",
    ],
    flowchartId: "NG137_TWINS",
    content: [
      { type: "text", value: "Recommended timing balances the rising stillbirth risk of continuing an uncomplicated multiple pregnancy further against the risks of iatrogenic prematurity — these are default planning windows for an uncomplicated pregnancy of the stated chorionicity/amnionicity, brought forward for any complication." },
      { type: "table",
        headers: ["Pregnancy type", "Planned birth"],
        rows: [
          ["Uncomplicated dichorionic diamniotic (DCDA) twins", "37+0 weeks"],
          ["Uncomplicated monochorionic diamniotic (MCDA) twins", "36+0 weeks"],
          ["Monochorionic monoamniotic (MCMA) twins", "32+0–33+6 weeks"],
          ["Uncomplicated trichorionic or dichorionic triamniotic triplets", "35+0 weeks"],
        ],
      },
      { type: "alert", value: "These aren't arbitrary — continuing an uncomplicated DCDA twin pregnancy beyond 37+6 weeks, or an uncomplicated MCDA twin pregnancy beyond 36+6 weeks, is associated with an increased risk of fetal death. Bring the plan forward, don't push it later, if in doubt." },
      { type: "text", value: "Offer a single course of antenatal corticosteroids ahead of any planned preterm birth (elective or in response to a complication), on the same principles as for a singleton pregnancy." },
    ],
  },

  {
    id: "ng137-mode-of-birth",
    gl: "NG137",
    condition: "Twin & Triplet Pregnancy",
    setting: "Intrapartum",
    title: "Mode of Birth",
    tags: [
      "twin mode of birth", "twin vaginal birth", "twin caesarean", "first twin presentation",
      "second twin delivery", "twin continuous monitoring",
    ],
    content: [
      { type: "subheading", value: "Twin 1 cephalic, beyond 32 weeks, no other complication" },
      { type: "list", items: [
        "Both planned vaginal birth and planned caesarean section are reasonable options — NICE does not recommend one over the other in this scenario, irrespective of chorionicity, provided there's no significant size discordance between the twins and no other obstetric contraindication to labour.",
        "This is a genuine choice to discuss with the woman, not a default toward either mode.",
      ]},
      { type: "subheading", value: "Twin 1 non-cephalic, or monoamniotic twins" },
      { type: "list", items: [
        "Twin 1 not cephalic: caesarean section is recommended.",
        "Monochorionic monoamniotic (MCMA) twins: caesarean section is recommended for all — the cord entanglement risk between the twins makes vaginal birth unsuitable regardless of presentation.",
      ]},
      { type: "subheading", value: "Requirements for planned vaginal twin birth" },
      { type: "list", items: [
        "Continuous electronic fetal monitoring of both babies throughout labour.",
        "Birth in an obstetric unit, attended by staff experienced and confident in twin birth — not a midwife-led unit or home birth setting.",
        "IV access established.",
        "A small proportion of women planning vaginal birth will still need an emergency caesarean section to deliver the second twin after the first is born vaginally — counsel for this possibility in advance rather than presenting vaginal birth as an all-or-nothing plan.",
        "There's no single mandated maximum time interval between the birth of twin 1 and twin 2 — decisions on augmentation, amniotomy for twin 2, or moving to caesarean are based on the fetal condition and progress, not a fixed clock.",
      ]},
    ],
  },
];
