// NICE NG73 — Endometriosis: Diagnosis and Management
// Originally published September 2017
// Partially updated April 2024 (surgical fertility) and November 2024 (diagnosis)
// https://www.nice.org.uk/guidance/ng73

export const NG73_SECTIONS = [
  {
    id: "ng73-overview",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Overview & Symptoms",
    title: "Endometriosis — Overview & Symptoms",
    tags: ["endometriosis", "pelvic pain", "dysmenorrhoea", "dyspareunia", "infertility", "chronic pelvic pain", "endometrioma", "adenomyosis", "DIE", "deep infiltrating endometriosis", "period pain", "painful periods"],
    content: [
      { type: "subheading", value: "Definition" },
      { type: "text", value: "Endometriosis is a chronic inflammatory condition in which tissue similar to the endometrium grows outside the uterus. It most commonly affects the pelvic peritoneum, ovaries (endometrioma), rectovaginal septum, and uterosacral ligaments. Deep infiltrating endometriosis (DIE) involves tissue >5 mm below the peritoneal surface." },
      { type: "subheading", value: "Prevalence & Diagnostic Delay" },
      { type: "list", items: [
        "Affects approximately 1 in 10 women of reproductive age",
        "Estimated 1.5 million women living with endometriosis in the UK",
        "Average diagnostic delay in the UK is 7.5–8 years from symptom onset to diagnosis",
        "Severity of symptoms does not correlate with extent of disease — stage I can cause severe pain",
      ]},
      { type: "subheading", value: "Key Symptoms" },
      { type: "alert", value: "Suspect endometriosis in any woman with unexplained pelvic pain, dysmenorrhoea, or subfertility — especially if symptoms are severe, cyclical, or unresponsive to simple analgesia." },
      { type: "list", items: [
        "Dysmenorrhoea — severe and often disabling menstrual pain",
        "Chronic pelvic pain — present for ≥6 months, often cyclical",
        "Deep dyspareunia — pain with sexual intercourse",
        "Cyclical bowel symptoms — dyschezia, rectal bleeding, bloating (especially at menstruation)",
        "Cyclical urinary symptoms — dysuria, haematuria, frequency at menstruation",
        "Subfertility / infertility",
        "Chronic fatigue — often underestimated; can be debilitating",
        "Shoulder tip pain at menstruation (diaphragmatic endometriosis — rare)",
      ]},
      { type: "subheading", value: "Examination Findings" },
      { type: "list", items: [
        "May be entirely normal — normal examination does NOT exclude endometriosis",
        "Fixed, retroverted uterus on bimanual examination",
        "Uterosacral nodularity or tenderness on bimanual / rectal examination",
        "Adnexal mass (endometrioma) — may be tender",
        "Speculum: 'powder-burn' lesions on posterior fornix (rare to see in clinic)",
      ]},
    ],
  },

  {
    id: "ng73-diagnosis",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Diagnosis",
    title: "Endometriosis — Diagnosis Pathway",
    tags: ["endometriosis diagnosis", "TVUS", "transvaginal ultrasound", "laparoscopy", "MRI", "referral", "primary care", "secondary care", "endometrioma", "NG73 2024"],
    flowchartId: "NG73_DIAGNOSIS",
    content: [
      { type: "subheading", value: "Primary Care Assessment (NG73 — Updated November 2024)" },
      { type: "alert", value: "GPs should now OFFER a transvaginal ultrasound (TVUS) to all people with suspected endometriosis. This is a significant 2024 update — previously TVUS was only recommended in secondary care after empirical treatment failed." },
      { type: "list", items: [
        "Take a full history: symptom onset, severity, impact on daily life and work",
        "Offer TVUS at first point of contact if symptoms suggest endometriosis",
        "Do not use a normal TVUS to exclude endometriosis — TVUS cannot reliably detect peritoneal disease",
        "Refer to gynaecology if: TVUS positive for endometrioma/DIE, symptoms persist despite simple analgesia and hormonal treatment, or if subfertility is a concern",
      ]},
      { type: "subheading", value: "What TVUS Can and Cannot Detect" },
      { type: "list", items: [
        "Can detect: ovarian endometrioma (ground-glass appearance), deep infiltrating endometriosis of rectovaginal septum, uterosacral ligaments, bladder",
        "Cannot detect: superficial peritoneal endometriosis — a normal scan does not exclude disease",
        "Always document: uterine position, mobility (sliding sign), ovarian mobility",
        "MRI pelvis: recommended if deep infiltrating endometriosis (DIE) is suspected — maps disease for surgical planning",
      ]},
      { type: "subheading", value: "Referral Criteria" },
      { type: "list", items: [
        "TVUS positive for endometrioma or features of DIE",
        "Symptoms not controlled by simple analgesia ± empirical hormonal treatment",
        "Suspected or confirmed deep infiltrating endometriosis",
        "Subfertility with suspected endometriosis",
        "Cyclical haematuria or rectal bleeding suggesting bladder/bowel involvement",
        "Diagnostic uncertainty — symptoms without clear alternative explanation",
      ]},
      { type: "subheading", value: "Laparoscopy — Diagnostic Gold Standard" },
      { type: "list", items: [
        "Laparoscopy is the only definitive way to diagnose peritoneal endometriosis",
        "Histological confirmation should be obtained where possible but absence of histology does not exclude diagnosis",
        "Therapeutic laparoscopy should be offered at the same time as diagnostic laparoscopy where possible",
        "Do NOT offer empirical GnRH agonist treatment instead of laparoscopy to confirm diagnosis",
        "MRI pre-operatively if DIE suspected — for operative planning",
      ]},
      { type: "subheading", value: "Who Does Not Need Laparoscopy First" },
      { type: "list", items: [
        "Women with typical symptoms where empirical treatment is being tried first (COCP or progestogen)",
        "Women who do not wish to proceed to surgery",
        "Note: endometriosis can be managed clinically without histological confirmation if diagnosis is clinically likely and response to treatment is adequate",
      ]},
    ],
  },

  {
    id: "ng73-classification",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Classification & Staging",
    title: "Endometriosis — Classification & Staging",
    tags: ["endometriosis staging", "rASRM", "ENZIAN", "endometrioma", "deep infiltrating endometriosis", "BSGE", "endometriosis centre", "superficial peritoneal", "ovarian", "DIE"],
    content: [
      { type: "subheading", value: "rASRM Staging (Most Widely Used)" },
      { type: "text", value: "The revised American Society for Reproductive Medicine (rASRM) system scores endometriosis based on location, size, depth of implants, and extent of adhesions at laparoscopy. It correlates poorly with symptom severity but is useful for surgical documentation." },
      { type: "table", headers: ["Stage", "Score", "Description"], rows: [
        ["I — Minimal", "1–5", "Few superficial implants"],
        ["II — Mild", "6–15", "More implants, some deep; small endometrioma"],
        ["III — Moderate", "16–40", "Multiple deep implants; endometrioma; peritubal/periovarian adhesions"],
        ["IV — Severe", ">40", "Many deep implants; large endometrioma; dense adhesions; DIE"],
      ]},
      { type: "subheading", value: "Types of Endometriosis" },
      { type: "list", items: [
        "Superficial peritoneal endometriosis — most common; implants on peritoneal surface",
        "Ovarian endometrioma — endometriotic cyst of ovary ('chocolate cyst'); ground-glass appearance on USS",
        "Deep infiltrating endometriosis (DIE) — disease >5mm below peritoneum; affects uterosacral ligaments, rectovaginal septum, bladder, ureters, bowel",
        "Extra-pelvic endometriosis — umbilical, caesarean section scar, diaphragm, lung (rare)",
      ]},
      { type: "subheading", value: "BSGE Endometriosis Centre Referral" },
      { type: "alert", value: "Refer to a BSGE-accredited endometriosis centre for severe or complex disease. Do not attempt DIE surgery in non-specialist centres." },
      { type: "list", items: [
        "Deep infiltrating endometriosis (bowel, bladder, ureteric involvement)",
        "Endometriosis causing hydronephrosis",
        "Recurrent disease after previous surgery",
        "Disease adjacent to major blood vessels or ureters",
        "Endometriosis requiring bowel resection or ureteric reimplantation",
        "Suspected malignant transformation of endometrioma",
      ]},
    ],
  },

  {
    id: "ng73-medical",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Medical Management",
    title: "Endometriosis — Medical Management",
    tags: ["endometriosis treatment", "COCP", "progestogen", "GnRH agonist", "dienogest", "goserelin", "leuprorelin", "add-back", "hormonal treatment", "pain", "norethisterone", "LNG-IUS", "mirena"],
    content: [
      { type: "subheading", value: "Principles" },
      { type: "list", items: [
        "Medical treatment suppresses endometriosis activity but does NOT eradicate disease",
        "Most hormonal treatments are contraceptive — discuss with the patient",
        "Treatment should be tailored to: pain control vs fertility wish, side effect profile, patient preference",
        "NSAIDs (e.g. ibuprofen, mefenamic acid) for pain — evidence base is limited but widely used first-line for dysmenorrhoea",
      ]},
      { type: "subheading", value: "First-Line Hormonal Treatment" },
      { type: "alert", value: "Offer hormonal treatment to people with suspected, confirmed, or recurrent endometriosis unless contraindicated or fertility is the immediate priority." },
      { type: "list", items: [
        "Combined oral contraceptive pill (COCP) — e.g. Microgynon 30, Rigevidon; may be used continuously (skip pill-free interval) to suppress cyclical pain",
        "Oral progestogen — norethisterone 5–10 mg daily, or medroxyprogesterone acetate 10 mg daily",
        "Levonorgestrel IUS 52mg (Mirena) — particularly effective for dysmenorrhoea and pelvic pain; licensed for endometriosis",
        "Desogestrel 75 mcg (Cerazette) — POP with anovulatory effect; useful when oestrogen is contraindicated",
        "Etonogestrel implant (Nexplanon) — off-label for endometriosis pain; useful long-term option",
        "Progestogen depot injection (Depo-Provera 150mg IM 12-weekly) — effective but delayed return of fertility",
      ]},
      { type: "subheading", value: "Dienogest (Visanne) — Endometriosis-Specific Progestogen" },
      { type: "list", items: [
        "Dienogest 2 mg orally once daily — licensed in the UK specifically for endometriosis",
        "Higher selectivity for progesterone receptors than older progestogens",
        "Effective for pain and endometrioma suppression",
        "Contraceptive but not licensed as contraception — use additional contraception if needed",
        "Side effects: irregular bleeding (especially initial months), reduced bone density with long-term use",
      ]},
      { type: "subheading", value: "GnRH Agonists (Second-Line)" },
      { type: "list", items: [
        "Goserelin 3.6 mg SC monthly (Zoladex) or 10.8 mg SC every 3 months",
        "Leuprorelin 3.75 mg IM monthly (Prostap 3DCS) or 11.25 mg IM every 3 months",
        "Induce pseudomenopause — highly effective for pain",
        "Maximum 6 months without add-back HRT due to bone density loss",
        "Add-back HRT (e.g. norethisterone 5 mg daily or continuous combined HRT) should be offered from the start of GnRH agonist therapy to reduce menopausal side effects and protect bone density",
        "With add-back: treatment can be extended beyond 6 months",
        "Side effects without add-back: hot flushes, night sweats, vaginal dryness, bone loss",
      ]},
      { type: "subheading", value: "GnRH Antagonists" },
      { type: "list", items: [
        "Relugolix/estradiol/norethisterone (Ryeqo) — oral GnRH antagonist with built-in add-back; licensed in UK for moderate-severe endometriosis",
        "Advantage over GnRH agonists: immediate effect (no flare), fully oral, add-back combined in one tablet",
        "Elagolix (Orilissa) — not currently licensed in UK for endometriosis",
      ]},
      { type: "subheading", value: "What Medical Treatment Does NOT Do" },
      { type: "list", items: [
        "Medical treatment does NOT improve fertility — do not use hormonal treatment with the aim of improving fertility",
        "Medical treatment does NOT cure endometriosis — symptoms typically return after stopping",
        "GnRH agonists do NOT treat endometrioma definitively — surgical removal required",
      ]},
    ],
  },

  {
    id: "ng73-surgical",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Surgical Management",
    title: "Endometriosis — Surgical Management",
    tags: ["endometriosis surgery", "laparoscopy", "excision", "ablation", "endometrioma", "cystectomy", "BSGE", "deep infiltrating endometriosis", "DIE", "bowel endometriosis", "hysterectomy"],
    flowchartId: "NG73_TREATMENT",
    content: [
      { type: "subheading", value: "General Principles" },
      { type: "list", items: [
        "Offer laparoscopic surgery to treat endometriosis-associated pain when medical treatment has failed, is contraindicated, or is not tolerated",
        "Therapeutic surgery at the same time as diagnostic laparoscopy where possible — avoid two-stage procedures",
        "Obtain histological confirmation of endometriosis where feasible",
        "Post-surgical hormonal treatment should be offered to reduce recurrence",
      ]},
      { type: "subheading", value: "Excision vs Ablation" },
      { type: "alert", value: "Excision (cutting out) is preferred over ablation (burning) for peritoneal endometriosis — excision has better evidence for pain relief and allows histological confirmation." },
      { type: "list", items: [
        "Laparoscopic excision of peritoneal endometriosis: superior to ablation for long-term pain relief",
        "Ablation may be appropriate for superficial peritoneal disease where excision is not feasible",
        "Do not use ablation alone for endometriomas — high recurrence rate",
      ]},
      { type: "subheading", value: "Endometrioma (Ovarian Endometriosis)" },
      { type: "list", items: [
        "Laparoscopic cystectomy (excision of the cyst wall) preferred over drainage and ablation — lower recurrence and less impact on fertility",
        "Drainage alone is not recommended — very high recurrence rate",
        "Counsel regarding risk to ovarian reserve: cystectomy inevitably removes some normal ovarian tissue",
        "Anti-Müllerian hormone (AMH) should be measured before surgery if fertility is a concern",
        "Endometrioma >3 cm before IVF: consider cystectomy — improves ovarian access and may improve outcomes (discuss risks to ovarian reserve)",
      ]},
      { type: "subheading", value: "Deep Infiltrating Endometriosis (DIE)" },
      { type: "alert", value: "DIE surgery (bowel, bladder, ureteric endometriosis) must be performed in a BSGE-accredited endometriosis centre. Do not attempt in a non-specialist setting." },
      { type: "list", items: [
        "MRI pelvis mandatory before DIE surgery — maps extent for planning",
        "Multi-disciplinary team: gynaecologist, colorectal surgeon, urologist",
        "Bowel endometriosis: shave excision, disc resection, or bowel resection depending on depth/extent",
        "Bladder endometriosis: laparoscopic cystectomy/partial cystectomy",
        "Ureteric involvement: ureterolysis ± ureteric reimplantation",
      ]},
      { type: "subheading", value: "Hysterectomy" },
      { type: "list", items: [
        "Hysterectomy with bilateral salpingo-oophorectomy (BSO): for women who have completed their family and have not responded to other treatments",
        "Hysterectomy without BSO: for adenomyosis-predominant disease in younger women — residual endometriosis may be stimulated by remaining ovarian function",
        "HRT should be considered after BSO in young women — risks of surgical menopause outweigh endometriosis recurrence risk",
        "Even after hysterectomy, endometriosis can persist if not excised — remove all visible disease at time of surgery",
      ]},
      { type: "subheading", value: "Post-Surgical Hormonal Treatment" },
      { type: "list", items: [
        "Offer hormonal treatment post-surgery to reduce symptom recurrence and disease progression",
        "COCP or progestogen (including LNG-IUS) are appropriate long-term options",
        "GnRH agonists post-surgery: 3–6 months can reduce recurrence but should be followed by long-term hormonal maintenance therapy",
        "Discuss with patient: fertility wishes, symptom burden, and side effect tolerability",
      ]},
    ],
  },

  {
    id: "ng73-fertility",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Fertility & Endometriosis",
    title: "Endometriosis — Fertility Management",
    tags: ["endometriosis fertility", "IVF", "subfertility", "endometrioma", "laparoscopy fertility", "ART", "assisted reproduction", "cystectomy fertility", "NG73 2024"],
    content: [
      { type: "subheading", value: "Key Principles (NG73 April 2024 Update)" },
      { type: "alert", value: "Medical hormonal treatment for endometriosis does NOT improve fertility. Do not use GnRH agonists, COCP, or progestogens with the aim of improving natural conception rates." },
      { type: "list", items: [
        "Endometriosis is associated with reduced fertility but many women conceive naturally",
        "Laparoscopic surgery can improve fertility outcomes — particularly in minimal to moderate disease",
        "Refer to a fertility specialist early — do not delay assisted reproduction in women with endometriosis and subfertility",
        "Discuss with multidisciplinary team: pain specialist, fertility specialist, gynaecologist",
      ]},
      { type: "subheading", value: "Surgery for Fertility" },
      { type: "list", items: [
        "Laparoscopic excision of peritoneal endometriosis improves spontaneous pregnancy rates in minimal-mild disease (stage I–II)",
        "Endometrioma: laparoscopic cystectomy before IVF if endometrioma >3 cm — improves ovarian access and possibly IVF outcomes (April 2024 update: offer cystectomy rather than drainage)",
        "Warn about risk to ovarian reserve with cystectomy — measure AMH pre-operatively",
        "For severe (stage III–IV) endometriosis with subfertility: IVF may be first-line as surgery alone often insufficient",
        "Tubal endometriosis: discuss tubal surgery vs IVF — IVF is generally preferred",
      ]},
      { type: "subheading", value: "IVF in Endometriosis" },
      { type: "list", items: [
        "Endometriosis reduces IVF success rates — counsel appropriately",
        "Pre-IVF treatment with GnRH agonists for 3–6 months may improve IVF outcomes in severe endometriosis (limited evidence)",
        "Endometrioma drainage at egg collection: not routinely recommended — risk of infection and ovarian damage",
        "Endometrioma cystectomy preferred over repeated aspiration before IVF if endometrioma >3 cm",
        "Active endometriosis does not preclude IVF but outcomes may be poorer",
      ]},
      { type: "subheading", value: "Fertility Preservation" },
      { type: "list", items: [
        "Consider fertility preservation (oocyte/embryo cryopreservation) before surgery for endometrioma — particularly if bilateral disease or low ovarian reserve",
        "Discuss ovarian reserve (AMH, antral follicle count) before any ovarian surgery",
        "Women with bilateral endometrioma or recurrent disease are at high risk of premature ovarian insufficiency",
      ]},
    ],
  },

  {
    id: "ng73-longterm",
    gl: "NG73",
    condition: "Endometriosis",
    setting: "Long-term Management & Recurrence",
    title: "Endometriosis — Long-term Management",
    tags: ["endometriosis recurrence", "long term", "menopause", "HRT", "endometriosis menopause", "recurrence prevention", "monitoring", "quality of life", "psychological", "endometriosis sequelae"],
    content: [
      { type: "subheading", value: "Recurrence Risk" },
      { type: "list", items: [
        "Endometriosis is a chronic condition — symptoms frequently recur after stopping treatment or following surgery",
        "5-year recurrence rate after conservative surgery: approximately 20–40%",
        "Recurrence is higher in severe disease (stage III–IV) and DIE",
        "Post-surgical hormonal treatment significantly reduces recurrence risk",
      ]},
      { type: "subheading", value: "Long-term Hormonal Treatment" },
      { type: "list", items: [
        "COCP continuously (no pill-free interval) or cyclically — effective and well-tolerated long-term",
        "LNG-IUS (Mirena) — excellent for dysmenorrhoea and pelvic pain; can be re-inserted",
        "Progestogens (norethisterone, dienogest, desogestrel) — long-term use acceptable",
        "GnRH agonists with add-back: can be continued long-term with adequate add-back HRT",
        "Review need for treatment at least annually — assess symptom control, side effects, and fertility wishes",
      ]},
      { type: "subheading", value: "Endometriosis and Menopause" },
      { type: "list", items: [
        "Endometriosis generally regresses after natural menopause as oestrogen levels fall",
        "HRT after surgical menopause (BSO): benefits usually outweigh risks — discuss with patient",
        "Combined HRT (oestrogen + progestogen) preferred after BSO for endometriosis to avoid stimulating residual disease",
        "Tibolone: an alternative to combined HRT post-BSO",
        "Oestrogen-only HRT after total hysterectomy + BSO for endometriosis: risk of stimulating residual disease — consider combined HRT or tibolone",
      ]},
      { type: "subheading", value: "Psychological and Quality of Life Impact" },
      { type: "list", items: [
        "Chronic pain causes significant psychological morbidity — screen for depression and anxiety",
        "Offer referral to pain psychology, pelvic physiotherapy, and support groups",
        "Endometriosis UK: support organisation for women with endometriosis",
        "Provide written information — NICE has patient decision aids for endometriosis",
        "Occupational impact: discuss workplace adjustments where appropriate",
      ]},
      { type: "subheading", value: "Malignancy Risk" },
      { type: "list", items: [
        "Endometriosis carries a slightly increased risk of endometrioid and clear cell ovarian cancer",
        "Absolute risk remains low — routine CA125 monitoring not recommended",
        "Suspicious features in endometrioma: rapid growth, solid components, septa, vascularity on USS — refer urgently",
        "Malignant transformation of endometrioma: rare but recognised; always obtain histology from excised endometriomas",
      ]},
    ],
  },
];
