// NG88 — Heavy Menstrual Bleeding: Assessment and Management
// NICE Guideline NG88 (November 2018, updated September 2023)
// Co-produced with RCOG

export const NG88_SECTIONS = [
  {
    id: "ng88-overview",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Primary Care / Gynaecology",
    title: "Overview, Definition & Impact",
    tags: [
      "heavy menstrual bleeding", "hmb", "menorrhagia", "heavy periods",
      "ng88", "nice", "rcog", "menstrual blood loss", "quality of life",
      "abnormal uterine bleeding", "aub", "heavy bleeding", "flooding",
      "menstrual disorder", "period problems",
    ],
    flowchartId: "NG88_ASSESSMENT",
    content: [
      { type: "text", value: "NICE Guideline NG88 (updated September 2023) covers the assessment and management of heavy menstrual bleeding (HMB) in women of reproductive age. HMB is defined as excessive menstrual blood loss which interferes with a woman's physical, social, emotional and/or material quality of life. This replaces the previous quantitative definition of >80 ml per cycle." },
      { type: "alert", value: "HMB is a clinical diagnosis. Women's own assessment of the impact on their quality of life is central to diagnosis and management decisions — blood loss does not need to be objectively measured." },
      { type: "subheading", value: "Prevalence & Impact" },
      { type: "list", items: [
        "HMB affects approximately 1 in 3 women of reproductive age in the UK",
        "One of the commonest reasons for gynaecological referral — accounts for ~20% of all gynaecology outpatient appointments",
        "Associated with iron deficiency anaemia in ~60% of women with confirmed HMB",
        "Significant impact on daily activities, work, social life, and mental health",
        "Women may use up to 30 or more pads/tampons per day in severe HMB",
      ]},
      { type: "subheading", value: "PALM-COEIN Classification (FIGO)" },
      { type: "text", value: "The FIGO PALM-COEIN system classifies causes of abnormal uterine bleeding (AUB) into structural and non-structural categories:" },
      { type: "list", items: [
        "PALM (structural): Polyp — Adenomyosis — Leiomyoma (fibroid) — Malignancy & hyperplasia",
        "COEIN (non-structural): Coagulopathy — Ovulatory dysfunction — Endometrial — Iatrogenic — Not yet classified",
        "Many women have no identifiable structural cause ('dysfunctional uterine bleeding')",
      ]},
      { type: "subheading", value: "Symptoms Prompting Assessment" },
      { type: "list", items: [
        "Periods lasting >7 days",
        "Flooding or clots, soaking through protection, or changing pads/tampons more than hourly",
        "Passage of clots >2.5 cm in diameter",
        "Need to use double protection (pad + tampon simultaneously)",
        "Symptoms of anaemia: fatigue, breathlessness, palpitations",
        "HMB significantly affecting work, school, exercise, or social activities",
      ]},
    ],
  },

  {
    id: "ng88-assessment",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Primary Care",
    title: "Assessment in Primary Care",
    tags: [
      "hmb assessment", "menorrhagia assessment", "history taking periods",
      "pelvic examination hmb", "fbc hmb", "thyroid hmb", "investigations hmb",
      "pictorial blood assessment chart", "pbac", "menstrual calendar",
      "anaemia periods", "iron deficiency periods", "coagulation hmb",
      "von willebrand disease", "inherited bleeding disorder",
    ],
    flowchartId: "NG88_ASSESSMENT",
    content: [
      { type: "text", value: "A thorough history and examination identifies women with structural pathology, excludes malignancy, and guides treatment choice. The aim is to characterise the bleeding pattern, identify contributing factors, and assess quality-of-life impact." },
      { type: "subheading", value: "History" },
      { type: "list", items: [
        "Menstrual history: cycle length, duration, volume (use validated scoring tool e.g. PBAC if helpful), clots, flooding",
        "Associated symptoms: dysmenorrhoea (adenomyosis, fibroids), pelvic pressure/urinary symptoms (large fibroids), intermenstrual bleeding (IMB), postcoital bleeding (PCB) — these require prompt investigation",
        "Onset and duration of HMB: lifelong suggests coagulopathy; perimenopausal onset consider endometrial pathology",
        "Obstetric and gynaecological history: parity, previous surgery, contraceptive use",
        "Smear history and any recent pelvic infections",
        "Desire for future fertility: critical for treatment planning",
        "Impact on quality of life: work, social activities, relationships, mental health",
        "Medical history: thyroid disease, bleeding disorders, liver disease, hypertension, diabetes, obesity (endometrial cancer risk factors)",
        "Family history: coagulation disorders (Von Willebrand disease, haemophilia carrier)",
        "Medications: anticoagulants (increase blood loss), hormonal contraception, tamoxifen",
      ]},
      { type: "subheading", value: "Examination" },
      { type: "list", items: [
        "BMI (obesity is a risk factor for endometrial hyperplasia and cancer)",
        "Signs of anaemia (pallor, tachycardia)",
        "Abdominal examination: palpable uterus (large fibroids), tenderness",
        "Pelvic examination (if clinically appropriate): uterine size, mobility, tenderness, adnexal masses; speculum for cervical assessment",
        "Not all women require pelvic examination before starting pharmacological treatment in primary care",
      ]},
      { type: "subheading", value: "Investigations" },
      { type: "table", headers: ["Investigation", "Indication", "Notes"], rows: [
        ["FBC (Full Blood Count)", "All women with HMB", "Identifies anaemia — treat iron deficiency concurrently with HMB management"],
        ["Coagulation screen (inc. VWF antigen, activity, FVIII)", "Suspected inherited bleeding disorder", "Consider if: HMB since menarche, family history of bleeding disorder, personal history of bleeding after dental/surgical procedures — prevalence ~13% in HMB"],
        ["Thyroid function tests (TFTs)", "Only if clinical signs/symptoms of thyroid disease", "Not routinely indicated for HMB alone"],
        ["Pelvic ultrasound", "Structural pathology suspected, uterus palpable abdominally, pharmacological treatment has failed, or before surgical intervention", "Transvaginal USS preferred; identifies fibroids, adenomyosis, polyps"],
        ["Endometrial biopsy", "See indications below", "Pipelle biopsy in outpatient; hysteroscopy if polyp/focal lesion suspected"],
        ["Pregnancy test", "If pregnancy cannot be excluded", "Always exclude before initiating treatment"],
      ]},
      { type: "subheading", value: "Endometrial Biopsy Indications" },
      { type: "alert", value: "NICE NG88: Offer endometrial biopsy only at time of hysteroscopy (directed/hysteroscopic biopsy). Do NOT perform blind endometrial biopsy (e.g. Pipelle alone without hysteroscopy) — it is not recommended by NICE NG88 for HMB assessment." },
      { type: "list", items: [
        "Offer hysteroscopy + directed biopsy for women with persistent intermenstrual bleeding (any age)",
        "Offer hysteroscopy + directed biopsy for infrequent heavy bleeding + obesity (BMI >30) or PCOS",
        "Offer hysteroscopy + directed biopsy for any clinical feature raising concern for endometrial pathology",
        "Risk factors for endometrial pathology warranting hysteroscopy: BMI >30, PCOS, nulliparity, diabetes mellitus, Lynch syndrome (HNPCC), tamoxifen use",
        "Blind endometrial sampling (Pipelle alone) is NOT recommended by NG88 — has high false-negative rate for focal pathology (~60% miss rate for polyps/fibroids)",
      ]},
    ],
  },

  {
    id: "ng88-pharmacological",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Primary Care / Gynaecology",
    title: "Pharmacological Treatment",
    tags: [
      "hmb treatment", "menorrhagia treatment", "lng-ius", "mirena", "levonorgestrel iud",
      "tranexamic acid", "nonsteroidal anti-inflammatory", "nsaid", "mefenamic acid",
      "combined oral contraceptive pill", "norethisterone", "progesterone",
      "gnrh analogue", "goserelin", "ulipristal acetate", "esmya",
      "relugolix", "ryeqo", "linzagolix", "yselty",
      "first line treatment periods", "hormonal treatment hmb",
      "non hormonal treatment hmb", "progestogen hmb",
    ],
    flowchartId: "NG88_TREATMENT",
    content: [
      { type: "text", value: "Treatment should be tailored to the woman's individual circumstances, severity of HMB, presence of structural pathology, desire for contraception, and future fertility plans. If no structural or histological abnormality is identified (or fibroids <3 cm with no distortion of the uterine cavity), the following sequential approach is recommended." },
      { type: "subheading", value: "First-Line: LNG-IUS (Levonorgestrel Intrauterine System)" },
      { type: "alert", value: "LNG-IUS (e.g. Mirena 52 mg) should be the first treatment offered to women with HMB unless they specifically decline or it is contraindicated. It is the most effective medical treatment for HMB." },
      { type: "list", items: [
        "Reduces menstrual blood loss by 71–95% after 3 months; >90% reduction at 12 months",
        "Approximately 20–50% of users become amenorrhoeic within 1 year",
        "Provides effective contraception (>99.8% efficacy)",
        "Licensed for HMB for up to 5 years (52 mg LNG-IUS)",
        "Common side effects: irregular spotting first 3–6 months, hormonal side effects (acne, breast tenderness, mood changes) — less systemic than pills",
        "Contraindications: current breast cancer, unexplained uterine abnormality, distorted uterine cavity (e.g. large submucosal fibroids), active STI/PID",
      ]},
      { type: "subheading", value: "Second-Line Pharmacological Options" },
      { type: "text", value: "If LNG-IUS is declined or contraindicated, offer in the following order of preference:" },
      { type: "table", headers: ["Drug", "Dose & Timing", "Blood Loss Reduction", "Notes"], rows: [
        ["Tranexamic acid", "1 g (2 × 500 mg) up to 4 times daily, during menstruation only (max 4 days)", "~50% reduction", "Non-hormonal; does not affect ovulation. Do not use with combined hormonal contraceptive or in thromboembolic history."],
        ["NSAIDs (e.g. mefenamic acid, ibuprofen)", "Mefenamic acid 500 mg TDS during menstruation; ibuprofen 400–600 mg TDS with food", "~20–30% reduction", "Also reduces dysmenorrhoea. Non-hormonal. Avoid in renal disease, peptic ulcer disease, asthma (if NSAID-sensitive)."],
        ["Combined hormonal contraception (CHC)", "Standard pill, patch, or ring; can be used back-to-back to reduce cycle frequency", "~40–50% reduction (cyclically); greater if back-to-back", "Provides contraception. Consider UKMEC categories before prescribing. Not suitable for some migraineurs, smokers >35 years, high cardiovascular risk."],
        ["Norethisterone 5 mg", "5 mg TDS from day 5 to day 26 of cycle (cyclically)", "~80% reduction", "Effective but compliance can be an issue; irregular bleeding common initially. Not a contraceptive at this dose/regimen."],
        ["Long-acting progestogens (injectable/implant)", "Depo-Provera 150 mg IM every 12 weeks; Nexplanon implant", "Variable — often induces amenorrhoea", "Also contraceptive. Irregular bleeding common initially with implant. DMPA associated with bone density reduction with long-term use."],
      ]},
      { type: "subheading", value: "GnRH Analogues (Agonists)" },
      { type: "list", items: [
        "Goserelin (Zoladex), leuprorelin (Prostap), or nafarelin — cause medical menopause by downregulating gonadotrophin receptors",
        "Indications: pre-operative fibroid shrinkage (reduces size and vascularity before myomectomy/hysterectomy), bridge to surgery, correction of anaemia pre-operatively",
        "Amenorrhoea in ~89% of users; reduces uterine size by 30–50% over 3 months",
        "Duration: usually limited to 3–6 months due to bone mineral density loss and hypo-oestrogenic side effects",
        "Add-back HRT (tibolone or low-dose oestrogen + progestogen): allows longer use and substantially reduces side effects without compromising fibroid shrinkage effect",
        "NICE NG88: offer GnRH analogue pre-treatment before hysterectomy or myomectomy if uterine fibroids are causing enlarged or distorted uterus",
      ]},
      { type: "subheading", value: "GnRH Antagonists (Oral) — Specialist/Secondary Care" },
      { type: "list", items: [
        "Relugolix + estradiol + norethisterone acetate (Ryeqo): NICE TA832 (2022) — oral GnRH antagonist with built-in HRT add-back; single daily tablet; licensed up to 24 months for moderate-severe fibroid symptoms",
        "Linzagolix (Yselty): NICE TA996 (2024) — oral GnRH antagonist; two doses: 100 mg (no add-back required) and 200 mg (add-back HRT required); licensed up to 24 months",
        "Advantages over GnRH agonists: no initial flare effect, oral administration, faster onset, add-back included (relugolix) or dose-dependent (linzagolix)",
        "Both effective for HMB and bulk symptoms from fibroids; appropriate for women who decline or are not suitable for surgery",
      ]},
      { type: "subheading", value: "Ulipristal Acetate (Esmya) — RESTRICTED" },
      { type: "list", items: [
        "Selective progesterone receptor modulator (SPRM): reduces fibroid size and HMB",
        "MHRA safety review (2020–2021): risk of serious liver injury identified; marketing authorisation suspended then reinstated May 2021 with strict safety measures",
        "Current restrictions: only for women where surgery and UAE are not suitable, have failed, or declined; mandatory liver function tests before treatment, monthly for first 2 courses, then before each subsequent course; not for use with chronic liver disease",
        "Prescribers and dispensing pharmacists must be registered with the patient safety programme",
        "Dose: 5 mg daily for up to 3 months per course (intermittent treatment)",
        "In practice: largely replaced by GnRH antagonists (relugolix, linzagolix) due to safety profile",
      ]},
      { type: "subheading", value: "Concurrent Iron Supplementation" },
      { type: "list", items: [
        "Offer iron supplementation to all women with confirmed iron deficiency anaemia (Hb <120 g/L or ferritin <15–30 µg/L)",
        "Oral: ferrous fumarate 210 mg BD or ferrous sulphate 200 mg BD/TDS; take on empty stomach if tolerated; vitamin C enhances absorption",
        "IV iron (ferric carboxymaltose / Ferinject): consider if oral not tolerated, severe anaemia (Hb <80 g/L), or surgery planned in <4 weeks — see GL783 Iron Deficiency Anaemia guideline",
      ]},
    ],
  },

  {
    id: "ng88-surgical",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Secondary Care / Gynaecology",
    title: "Surgical & Interventional Treatment",
    tags: [
      "endometrial ablation", "hysterectomy", "myomectomy", "uterine artery embolisation",
      "uae", "surgical treatment hmb", "ablation", "tcre", "nea",
      "novasure", "thermachoice", "hysterectomy hmb", "abdominal hysterectomy",
      "vaginal hysterectomy", "laparoscopic hysterectomy", "tlh",
      "fibroid surgery", "fibroid treatment", "submucous fibroid", "submucosal",
      "mri guided fibroid treatment", "hifu",
    ],
    flowchartId: "NG88_SURGICAL",
    content: [
      { type: "text", value: "Surgical options should be discussed when pharmacological treatment has failed, is contraindicated, or is declined. Women should be informed of all appropriate options including their risks, benefits, recovery times, and implications for fertility." },
      { type: "subheading", value: "Endometrial Ablation" },
      { type: "alert", value: "Only offer endometrial ablation to women who do not want to preserve their fertility. Effective contraception is required after ablation as pregnancy carries high risks (morbid placentation, miscarriage, preterm labour)." },
      { type: "list", items: [
        "Destroys the endometrium using heat, cold, or microwave energy",
        "Second-generation techniques (NovaSure, ThermaChoice, Microwave) preferred — done without hysteroscopic visualisation, shorter procedure, similar efficacy",
        "First-generation: transcervical resection of endometrium (TCRE) — requires hysteroscopic skills",
        "Blood loss reduction: 70–90%; amenorrhoea rates 15–35% at 1 year; satisfaction rates ~80%",
        "Can be performed under local anaesthetic (in outpatient setting with second-generation devices) or general/spinal anaesthesia",
        "Recovery: typically 1–2 days off work (vs weeks for hysterectomy)",
        "Risk of treatment failure: ~30% require further treatment within 5 years; 15–20% will eventually need hysterectomy",
        "Contraindications: current or suspected pregnancy, current or recent endometrial infection, endometrial cancer or pre-cancer, desire for future fertility, uterine length >12 cm, distorted cavity (relative contraindication for some devices)",
      ]},
      { type: "subheading", value: "Hysterectomy" },
      { type: "list", items: [
        "Definitive cure for HMB — 100% patient satisfaction rates compared with ablation at 5 years (90% vs 79%)",
        "Reserve for women in whom other treatments have failed, are contraindicated, or who prefer definitive treatment",
        "Route: vaginal (preferred if uterus mobile and not enlarged), laparoscopic (TLH or LAVH), or abdominal",
        "Minimally invasive routes (vaginal/laparoscopic) associated with fewer complications, shorter hospital stay, faster recovery",
        "Ovarian conservation at hysterectomy: discuss risks and benefits — conserving ovaries avoids surgical menopause but retains risk of ovarian cancer",
        "Complications (all routes): haemorrhage (~1%), bowel/bladder injury (<1%), vault dehiscence, VTE (~1%), infection",
        "Recovery: 4–8 weeks from work (abdominal); 2–4 weeks (vaginal/laparoscopic)",
      ]},
      { type: "subheading", value: "Uterine Artery Embolisation (UAE)" },
      { type: "list", items: [
        "Interventional radiology procedure: embolises uterine arteries to infarct fibroids",
        "Suitable for: symptomatic uterine fibroids where uterine preservation desired; women who do not want surgery",
        "Symptom improvement (bulk/HMB): 85–90% at 1 year; fibroid volume reduction 40–70%",
        "NOT recommended for women who wish to preserve fertility — increased risk of premature ovarian failure, placenta praevia, preterm birth, intrauterine growth restriction in subsequent pregnancies",
        "Common side effects: post-embolisation syndrome (pain, fever, nausea) — lasts 3–7 days; managed with NSAIDs and antiemetics",
        "Complications: premature menopause (1–2%, more likely if age >45), fibroid expulsion, endometritis, ovarian artery embolisation",
        "Fibroid re-growth and symptom recurrence over time — re-intervention rate 20–30% by 5 years",
        "Alternatives to UAE for fibroid-related HMB: MRI-guided focused ultrasound surgery (MRgFUS), laparoscopic uterine artery occlusion",
      ]},
      { type: "subheading", value: "Myomectomy" },
      { type: "list", items: [
        "Surgical removal of fibroids preserving the uterus — suitable for women who want to preserve fertility",
        "Routes: hysteroscopic (for submucosal fibroids), laparoscopic, or open (abdominal) depending on fibroid number, size, location",
        "Hysteroscopic myomectomy: optimal for type 0 and type 1 submucosal fibroids; highly effective for HMB from submucous fibroids",
        "Symptom improvement in ~80%; fibroid recurrence at 5–10 years in ~30%",
        "Repeat surgery required in ~10–15% within 5 years",
        "GnRH analogue pre-treatment may help reduce fibroid size and blood loss during surgery",
      ]},
      { type: "subheading", value: "Pre-Surgical Optimisation" },
      { type: "list", items: [
        "Treat iron deficiency anaemia before elective surgery — target Hb ≥100 g/L",
        "GnRH analogue for 3 months pre-operatively if fibroids large (>10 cm) to reduce size and vascularity",
        "Tranexamic acid perioperatively may reduce intraoperative blood loss",
        "Cell salvage should be available for major cases",
      ]},
    ],
  },

  {
    id: "ng88-fibroids",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Secondary Care / Gynaecology",
    title: "HMB with Uterine Fibroids",
    tags: [
      "uterine fibroids", "leiomyomata", "myomata", "fibroid", "fibroids hmb",
      "submucosal fibroid", "submucous fibroid", "intramural fibroid", "subserosal fibroid",
      "figo fibroid classification", "type 0 fibroid", "type 1 fibroid", "type 2 fibroid",
      "fibroid symptoms", "fibroid management", "fibroid treatment",
      "bulk symptoms fibroids", "urinary frequency fibroids", "fibroid uterus",
    ],
    flowchartId: "NG88_FIBROID",
    content: [
      { type: "text", value: "Uterine fibroids (leiomyomata) affect approximately 20–40% of women of reproductive age, rising to 70–80% by age 50. They are the most common cause of HMB with structural pathology. Management depends on fibroid size, location, number, and the woman's fertility wishes." },
      { type: "subheading", value: "FIGO Fibroid Classification" },
      { type: "table", headers: ["Type", "Location", "Relationship to Cavity/Serosa", "HMB Association"], rows: [
        ["Type 0", "Submucosal — pedunculated", "Entirely within cavity", "Highest (most impact on bleeding)"],
        ["Type 1", "Submucosal — sessile", "<50% intramural", "High"],
        ["Type 2", "Submucosal — sessile", "≥50% intramural", "Moderate-High"],
        ["Type 3", "Intramural — entirely intramural, contacting endometrium", "100% intramural, no serosal extension", "Moderate"],
        ["Type 4", "Intramural", "Not reaching endometrium or serosa", "Lower"],
        ["Types 5–6", "Subserosal", "Pedunculated or sessile, subserosa", "Low (mainly bulk symptoms)"],
        ["Type 7", "Cervical / parasitic", "Various", "Variable"],
      ]},
      { type: "subheading", value: "Symptoms" },
      { type: "list", items: [
        "HMB — particularly from submucosal/cavity-distorting fibroids",
        "Bulk symptoms: pelvic pressure, urinary frequency/urgency (anterior fibroids compressing bladder), urinary retention (rare), constipation (posterior fibroids), abdominal distension",
        "Pelvic pain/pressure — chronic or with degeneration (sudden severe pain, fever, tenderness)",
        "Subfertility — particularly type 0–2 submucosal fibroids distorting the cavity",
        "Pregnancy complications: placentation abnormalities, preterm labour, fetal malpresentation",
      ]},
      { type: "subheading", value: "Investigation" },
      { type: "list", items: [
        "Pelvic USS (transvaginal preferred): characterise fibroids — size, number, FIGO type, relationship to cavity",
        "Saline infusion sonography (SIS/SHG) or 3D USS: better visualisation of submucosal fibroids and cavity",
        "MRI pelvis: for large/multiple fibroids before surgery or UAE — maps location and vascularity",
        "Hysteroscopy: direct visualisation ± biopsy of submucosal fibroids; essential before hysteroscopic myomectomy",
      ]},
      { type: "subheading", value: "Medical Management (Fibroids)" },
      { type: "list", items: [
        "LNG-IUS: effective for HMB from fibroids that do NOT distort the uterine cavity (overall fibroid diameter <3 cm preferred); not suitable for distorted cavities",
        "Tranexamic acid and NSAIDs: provide symptomatic relief but do not reduce fibroid size",
        "GnRH analogues: reduce fibroid volume by 30–50%; used pre-operatively (3–6 months) to shrink fibroids, reduce vascularity, and correct anaemia; not for long-term use",
        "Ulipristal acetate (Esmya): previously used but marketing authorisation suspended in UK due to serious liver injury risk — NOT currently in clinical use in UK",
        "Relugolix-oestradiol-norethindrone (Ryeqo): a new oral GnRH receptor antagonist approved by NICE (2023) — reduces fibroid volume and HMB; offers add-back HRT in single pill; used as bridge to surgery or for women who decline/are unfit for surgery",
      ]},
      { type: "subheading", value: "Surgical/Interventional Options by Fibroid Type" },
      { type: "list", items: [
        "Submucosal (type 0–2): hysteroscopic myomectomy — first-line surgical option for cavity-distorting fibroids",
        "Intramural/multiple: laparoscopic or open myomectomy depending on size; UAE if fertility not desired",
        "Any size, fertility not desired: UAE (if suitable) or hysterectomy",
        "Fibroids with severe bulk symptoms or failed UAE: hysterectomy often definitive",
      ]},
    ],
  },

  {
    id: "ng88-adenomyosis",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Secondary Care / Gynaecology",
    title: "HMB with Adenomyosis",
    tags: [
      "adenomyosis", "adenomyosis treatment", "adenomyosis hmb",
      "uterine adenomyosis", "adenomyosis diagnosis", "adenomyosis ultrasound",
      "adenomyosis mri", "uterine junctional zone", "diffuse adenomyosis",
      "focal adenomyosis", "adenomyoma", "dysmenorrhoea adenomyosis",
      "heavy periods adenomyosis",
    ],
    content: [
      { type: "text", value: "Adenomyosis is the presence of endometrial glands and stroma within the myometrium, causing uterine enlargement and smooth muscle hypertrophy. It affects approximately 20–35% of reproductive-age women (prevalence varies depending on diagnostic criteria). Definitive diagnosis is by histology following hysterectomy, but imaging can strongly suggest the diagnosis." },
      { type: "subheading", value: "Clinical Features" },
      { type: "list", items: [
        "HMB with progressive, severe dysmenorrhoea (most characteristic presentation)",
        "Uterine tenderness on bimanual examination; diffusely enlarged, globular, 'boggy' uterus",
        "Chronic pelvic pain, dyspareunia",
        "May co-exist with endometriosis (in up to 40% of cases)",
        "Worsens over time; typically improves after menopause",
      ]},
      { type: "subheading", value: "Diagnosis" },
      { type: "list", items: [
        "Transvaginal ultrasound (TVUSS): first-line — features include asymmetrical thickening of myometrium, myometrial cysts, heterogeneous myometrium, poor definition of endometrial-myometrial border (junctional zone), fan-shaped acoustic shadowing",
        "MRI pelvis: more accurate than USS for adenomyosis — junctional zone thickness >12 mm (or >40% of total myometrial thickness) is diagnostic; identifies extent and differentiates from fibroids",
        "Endometrial biopsy: does NOT diagnose adenomyosis (diagnosis requires full myometrial sampling)",
      ]},
      { type: "subheading", value: "Management" },
      { type: "list", items: [
        "LNG-IUS (Mirena): effective first-line — reduces dysmenorrhoea and HMB; may slow progression; can be effective even in enlarged uteri",
        "Combined hormonal contraception (CHC): back-to-back use to induce amenorrhoea",
        "GnRH analogues: temporary — effective whilst taking but symptoms recur after stopping; use as bridge to surgery",
        "Relugolix-oestradiol-norethindrone (Ryeqo): oral GnRH antagonist with add-back; suitable for women who want to avoid surgery",
        "Hysterectomy: definitive treatment — appropriate for women who have completed their family and have failed medical management; must include uterus (oophorectomy at surgeon/patient discretion depending on age and risk)",
        "Conservative surgery (adenomyomectomy): technically challenging; evidence limited; for focal adenomyosis in women wishing to preserve fertility",
        "UAE: limited evidence specifically for adenomyosis (better evidence for fibroids); may help in selected cases",
      ]},
    ],
  },

  {
    id: "ng88-polyps",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Secondary Care / Gynaecology",
    title: "HMB with Endometrial Polyps",
    tags: [
      "endometrial polyp", "uterine polyp", "polyp treatment", "polyp removal",
      "hysteroscopic polypectomy", "endometrial polyp hmb",
      "intermenstrual bleeding polyp", "postcoital bleeding polyp",
      "cervical polyp", "resectoscope polyp",
    ],
    content: [
      { type: "text", value: "Endometrial polyps are focal overgrowths of endometrial glands and stroma within the uterine cavity. They affect approximately 7–12% of women, increase in prevalence with age, and account for a significant proportion of HMB and intermenstrual bleeding. Risk factors include tamoxifen use, obesity, hypertension, diabetes, and oestrogen therapy." },
      { type: "subheading", value: "Presentation" },
      { type: "list", items: [
        "Intermenstrual bleeding (IMB) — commonest presentation; warrants investigation",
        "Postmenopausal bleeding (PMB) — must exclude malignancy",
        "HMB — may contribute to flooding/clots",
        "Postcoital bleeding (PCB) — consider endocervical polyp",
        "Often asymptomatic — incidental finding on pelvic USS",
      ]},
      { type: "subheading", value: "Investigation" },
      { type: "list", items: [
        "Transvaginal USS: identifies echogenic endometrial lesions, thickened endometrium; sensitivity ~70% for polyps",
        "Saline infusion sonography (SIS): superior to standard USS — delineates polyps within the cavity; sensitivity ~90%",
        "Hysteroscopy: gold standard — direct visualisation ± biopsy; diagnostic and therapeutic in one step",
        "Endometrial biopsy (Pipelle): high false-negative rate for polyps (~60%) — biopsy may miss focal pathology",
      ]},
      { type: "subheading", value: "Management" },
      { type: "list", items: [
        "Symptomatic polyps: hysteroscopic polypectomy — outpatient or day case; highly effective (>90% resolution of bleeding)",
        "Hysteroscopic polypectomy: resect at base using resectoscope, bipolar or mechanical system; send for histology",
        "Incidental asymptomatic polyps: expectant management acceptable as many regress spontaneously (up to 25%); reassess",
        "Malignancy risk: small (<1%) in premenopausal; higher in postmenopausal women (3–5%) — all PMB polyps warrant histological assessment",
        "Post-polypectomy follow-up: symptom resolution expected; repeat hysteroscopy if symptoms recur",
      ]},
    ],
  },

  {
    id: "ng88-referral",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Primary Care",
    title: "When to Refer & Red Flags",
    tags: [
      "hmb referral", "menorrhagia referral", "gynaecology referral",
      "urgent referral hmb", "two week wait", "2ww gynaecology",
      "red flag bleeding", "postmenopausal bleeding pmb",
      "intermenstrual bleeding imb", "postcoital bleeding pcb",
      "endometrial cancer referral", "cervical cancer referral",
      "abnormal uterine bleeding referral", "when to refer periods",
    ],
    content: [
      { type: "text", value: "Primary care management of HMB is appropriate in most cases. Referral to secondary care gynaecology is indicated when pharmacological treatment has failed, structural pathology is identified or suspected, or investigation beyond the primary care scope is required." },
      { type: "alert", value: "Urgent suspected cancer (2-week wait) referral is mandatory for postmenopausal bleeding. Consider urgent referral for persistent abnormal uterine bleeding in women with risk factors for endometrial cancer." },
      { type: "subheading", value: "Urgent (2-Week Wait / Suspected Cancer) Referral" },
      { type: "list", items: [
        "Postmenopausal bleeding (PMB): any woman who is ≥55 years (using age as proxy for menopause) with unexplained vaginal bleeding",
        "Postmenopausal women <55 years: treat as PMB if clinically menopausal",
        "Consider urgent referral (2WW): endometrial thickening >4 mm on USS + PMB; endometrial or cervical cancer suspected on examination",
      ]},
      { type: "subheading", value: "Non-Urgent Referral to Gynaecology" },
      { type: "list", items: [
        "Pharmacological treatment has failed (at least 2 treatments tried in primary care)",
        "Structural abnormality identified on USS (fibroids, polyps, adenomyosis) requiring secondary care management",
        "Uterus palpable abdominally (clinically significant fibroid enlargement)",
        "Persistent intermenstrual bleeding or postcoital bleeding (to exclude cervical/endometrial pathology)",
        "Consideration of surgical treatment: ablation, myomectomy, hysterectomy, UAE",
        "Women with coagulopathy or complex medical conditions requiring specialist input",
        "Concern about endometrial cancer in at-risk women with failed first-line treatment",
        "Subfertility associated with structural pathology (fibroids, polyps)",
        "Adolescent girls with HMB since menarche (? inherited coagulopathy)",
      ]},
      { type: "subheading", value: "Investigations Before Referral" },
      { type: "list", items: [
        "FBC — always perform; correct anaemia",
        "Pelvic USS — if structural pathology suspected or treatment has failed",
        "Coagulation studies if inherited bleeding disorder suspected",
        "Cervical smear — ensure up to date",
        "Sexual health screen if PID/STI is a possible contributing factor",
      ]},
    ],
  },

  {
    id: "ng88-special-populations",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Gynaecology",
    title: "Special Populations",
    tags: [
      "hmb adolescents", "hmb teenagers", "hmb perimenopause", "hmb menopause transition",
      "hmb fertility preservation", "hmb fertility", "coagulopathy hmb", "von willebrand hmb",
      "hmb anticoagulation", "hmb warfarin", "hmb doac", "hmb obesity",
      "hmb endometrial cancer risk", "tamoxifen bleeding", "hmb special cases",
      "hmb women wanting children",
    ],
    content: [
      { type: "text", value: "Certain groups of women with HMB require tailored assessment and management." },
      { type: "subheading", value: "Adolescents with HMB" },
      { type: "list", items: [
        "Consider inherited coagulopathy (particularly Von Willebrand disease) in girls with HMB since menarche — prevalence ~13% in this group",
        "Initial investigations: FBC, blood group, coagulation screen including VWF antigen, VWF activity (Ristocetin cofactor), FVIII",
        "Referral to haematology if inherited bleeding disorder confirmed",
        "Treatment: tranexamic acid, NSAIDs, CHC are appropriate first-line options; consider LNG-IUS for ongoing management",
        "Hormonal contraception has additional benefits (cycle regulation, contraception, dysmenorrhoea relief)",
      ]},
      { type: "subheading", value: "Women Wanting to Preserve Fertility" },
      { type: "list", items: [
        "Avoid endometrial ablation and hysterectomy — these are permanent and end fertility",
        "LNG-IUS is appropriate (fertility returns promptly after removal)",
        "Pharmacological options: tranexamic acid, NSAIDs, CHC, GnRH analogues (short-term)",
        "Hysteroscopic polypectomy or myomectomy if structural cause identified",
        "UAE is not recommended for women who wish to conceive — risk of ovarian failure, obstetric complications",
        "GnRH analogues + conservative surgery for significant fibroids in those wanting fertility",
      ]},
      { type: "subheading", value: "Perimenopausal Women" },
      { type: "list", items: [
        "HMB is common in perimenopause — anovulatory cycles cause oestrogen dominance without progesterone opposition",
        "Higher risk of endometrial hyperplasia/cancer than younger women — lower threshold for endometrial biopsy",
        "Offer endometrial biopsy if: persistent IMB, treatment failure, BMI >30, or other risk factors",
        "LNG-IUS: highly effective and also provides endometrial protection from oestrogen excess; can be used as the progestogen component of HRT when transitioning",
        "CHC: suitable if not contraindicated (UKMEC); can regularise cycles and reduce flow",
        "HRT: systemic HRT with adequate progestogen protects the endometrium — does not exacerbate HMB if well-regulated",
        "Natural menopause resolves HMB — hormonal bridging strategies to menopause are often appropriate",
      ]},
      { type: "subheading", value: "Women on Anticoagulation" },
      { type: "list", items: [
        "Anticoagulation (warfarin, DOACs, heparin) significantly worsens menstrual blood loss",
        "LNG-IUS is the treatment of choice — most effective at reducing blood loss without systemic interactions",
        "Tranexamic acid: discuss with the anticoagulating team — generally safe but use with caution; theoretical interaction with anticoagulants",
        "Norethisterone or combined pill: discuss with relevant specialist",
        "Consider dose review/modification of anticoagulant if clinically appropriate",
      ]},
      { type: "subheading", value: "Women with Coagulopathy (e.g. Von Willebrand Disease)" },
      { type: "list", items: [
        "Multi-disciplinary management with haematology",
        "Desmopressin (DDAVP): for VWD type 1 — intranasal or IV at time of heavy bleeding; check response with trial dose",
        "VWF concentrate (e.g. Haemate P): for VWD types 2/3 and severe HMB",
        "Tranexamic acid: effective adjunct — reduces fibrinolysis",
        "LNG-IUS, norethisterone, CHC: all appropriate hormonal options",
        "Avoid aspirin and NSAIDs (may worsen platelet function)",
      ]},
    ],
  },

  {
    id: "ng88-secondary-care",
    gl: "NG88",
    condition: "Heavy Menstrual Bleeding",
    setting: "Secondary Care / Gynaecology",
    title: "Secondary Care: Investigation & Management Pathway",
    tags: [
      "hysteroscopy hmb", "hysteroscopy investigation", "outpatient hysteroscopy",
      "saline infusion sonography", "sis", "shg", "endometrial biopsy",
      "pipelle biopsy", "endometrial hyperplasia", "endometrial cancer",
      "secondary care hmb management", "gynaecology outpatient hmb",
      "secondary care pathway hmb",
    ],
    flowchartId: "NG88_SECONDARY",
    content: [
      { type: "text", value: "Women referred to secondary care with HMB should have a structured assessment to identify any underlying structural or histological abnormality and to offer appropriate treatment, including surgical options not available in primary care." },
      { type: "subheading", value: "Secondary Care Investigations" },
      { type: "list", items: [
        "Pelvic USS (transvaginal): characterise uterus, endometrium, fibroids, polyps, ovaries — if not already performed",
        "Saline infusion sonography (SIS): superior to standard USS for detecting submucosal fibroids and polyps; recommended before hysteroscopic surgery",
        "Hysteroscopy: gold standard for intrauterine pathology; can be diagnostic or therapeutic (outpatient preferable)",
        "Endometrial biopsy: Pipelle in outpatient or concurrent at hysteroscopy; histology mandatory if endometrial cancer suspected",
        "MRI pelvis: indicated for large or complex fibroids, suspected adenomyosis, or pre-UAE assessment",
        "Haematology referral: if coagulopathy identified or suspected",
      ]},
      { type: "subheading", value: "Outpatient Hysteroscopy" },
      { type: "list", items: [
        "Preferred approach for diagnostic hysteroscopy and minor therapeutic procedures (polypectomy, submucosal fibroid assessment)",
        "No-touch technique using a 2–3 mm hysteroscope improves tolerability",
        "Local anaesthetic (paracervical block or intrauterine local anaesthetic) can be offered",
        "Pre-procedure: prostaglandin (misoprostol) to soften the cervix is NOT routinely recommended (no clear benefit, side effects)",
        "Complications: failure to enter cavity (~3%), vasovagal reaction, rarely perforation (<1%), endometritis",
        "Pain management: NSAID 30–60 minutes before procedure; distension media warmed to body temperature",
      ]},
      { type: "subheading", value: "Endometrial Hyperplasia" },
      { type: "text", value: "Endometrial hyperplasia without atypia has a low malignant potential (<5%) and is usually associated with oestrogen excess (obesity, anovulation, PCOS). Atypical endometrial hyperplasia (AEH) / Endometrial Intraepithelial Neoplasia (EIN) carries a 25–30% risk of concurrent or future endometrial cancer." },
      { type: "list", items: [
        "Without atypia: LNG-IUS is first-line treatment — regression in >90% at 6 months; 6-monthly endometrial biopsy to confirm regression",
        "Without atypia (alternative): oral progestogen (norethisterone 10–15 mg daily or medroxyprogesterone acetate 10–20 mg daily) — lower compliance, higher regression rates with LNG-IUS",
        "Atypical (AEH/EIN): hysterectomy is the recommended treatment for women who have completed their family — risk of concurrent cancer ~25–30%",
        "Atypical + fertility desired: high-dose oral progestogen (megestrol acetate 160 mg daily, or norethisterone 10–15 mg daily) + LNG-IUS; mandatory 3-monthly hysteroscopy + biopsy; managed at specialist centre",
        "Follow-up of hyperplasia without atypia: continue until two consecutive negative biopsies",
      ]},
    ],
  },
];
