export const SYNONYMS = {
  // Counsel (formerly Consent)
  "counsel": ["consent","counselling","risks","benefits","patient information"],
  "counselling": ["consent","counsel","risks","benefits","patient information"],
  "consent": ["counsel","counselling","risks","patient information"],
  "vbac": ["birth after caesarean","vaginal birth after caesarean","ercs","uterine rupture","gtg45","counsel"],
  "birth after caesarean": ["vbac","ercs","repeat caesarean","uterine rupture","gtg45"],
  "uterine rupture": ["scar rupture","vbac","scar dehiscence","gtg45"],
  "scar rupture": ["uterine rupture","vbac","scar dehiscence"],
  "tolac": ["vbac","trial of labour after caesarean","birth after caesarean"],
  "ercs": ["vbac","repeat caesarean","elective caesarean","birth after caesarean"],
  "ecv": ["external cephalic version","breech","turning baby","tocolysis","gtg20"],
  "external cephalic version": ["ecv","breech","turning baby","gtg20"],
  "breech": ["ecv","external cephalic version","caesarean","vaginal breech birth","gtg20"],

  "caesarean": ["caesarean section","c section","lscs","ng192","category 1","category 2"],
  "caesarean section": ["caesarean","c section","lscs","ng192"],
  "c section": ["caesarean","caesarean section","lscs","ng192"],
  "lscs": ["caesarean","caesarean section","c section"],
  "category 1 caesarean": ["crash section","emergency caesarean","decision to delivery interval","30 minutes"],
  "category 2 caesarean": ["emergency caesarean","decision to delivery interval","75 minutes"],
  "crash section": ["category 1 caesarean","emergency caesarean","decision to delivery interval"],
  "decision to delivery interval": ["category 1 caesarean","category 2 caesarean","ddi"],
  "maternal request caesarean": ["caesarean","elective caesarean","ng192"],
  "assisted vaginal birth": ["operative vaginal delivery","forceps","ventouse","instrumental delivery","gtg26"],
  "operative vaginal delivery": ["assisted vaginal birth","forceps","ventouse","instrumental delivery","gtg26"],
  "instrumental delivery": ["assisted vaginal birth","operative vaginal delivery","forceps","ventouse"],
  "forceps": ["ventouse","assisted vaginal birth","instrumental delivery","kiellands forceps"],
  "ventouse": ["forceps","vacuum extraction","assisted vaginal birth","kiwi omnicup"],
  "vacuum extraction": ["ventouse","assisted vaginal birth","instrumental delivery"],
  "kiellands forceps": ["rotational forceps","forceps","assisted vaginal birth"],
  "trial in theatre": ["trial of instrumental delivery","assisted vaginal birth","failed instrumental delivery"],
  "failed instrumental delivery": ["trial in theatre","assisted vaginal birth","abandon instrumental delivery"],
  "oasi": ["obstetric anal sphincter injury","third degree tear","fourth degree tear","perineal trauma"],
  "obstetric anal sphincter injury": ["oasi","third degree tear","fourth degree tear","perineal trauma"],
  "cephalhaematoma": ["ventouse","neonatal head injury","subgaleal haemorrhage"],

  // Fetal monitoring / CTG (NICE NG229)
  "ctg": ["cardiotocography","cardiotocograph","fetal monitoring","fetal heart rate","fhr","efm","ng229","pathological ctg","suspicious ctg"],
  "cardiotocography": ["ctg","fetal monitoring","fetal heart rate","efm","ng229"],
  "cardiotocograph": ["ctg","cardiotocography","fetal monitoring","ng229"],
  "efm": ["ctg","cardiotocography","electronic fetal monitoring","fetal monitoring","ng229"],
  "fetal monitoring": ["ctg","cardiotocography","efm","intermittent auscultation","fetal heart rate","ng229"],
  "fhr": ["fetal heart rate","ctg","baseline","cardiotocography"],
  "deceleration": ["decelerations","late decelerations","variable decelerations","prolonged deceleration","ctg"],
  "decelerations": ["deceleration","late decelerations","variable decelerations","ctg"],
  "variability": ["baseline variability","reduced variability","ctg","cardiotocography"],
  "sinusoidal": ["ctg","cardiotocography","pathological ctg","fetal anaemia"],
  "bravado": ["dr c bravado","ctg","ctg interpretation","fetal monitoring"],
  "fbs": ["fetal blood sampling","fetal scalp stimulation","ctg","pathological ctg"],
  "fetal blood sampling": ["fbs","fetal scalp stimulation","ctg","pathological ctg"],

  // Induction of labour
  "iol": ["induction of labour","induction","induce","propess","crb","prostin","oxytocin","bishop score"],
  "induction": ["induction of labour","iol","propess","crb","dinoprostone","oxytocin","arm","bishop score"],
  "induce": ["induction of labour","iol","propess","crb","bishop score"],
  "post dates": ["post-maturity","induction","40+7","overdue","iol"],
  "post-dates": ["post-maturity","induction","40+7","overdue","iol"],
  "overdue": ["post-dates","post-maturity","40+7","induction of labour"],
  "propess": ["dinoprostone","prostaglandin","induction of labour","iol","cervical ripening","second line"],
  "dinoprostone": ["propess","prostaglandin","induction of labour","iol"],
  "crb": ["cervical ripening balloon","balloon","induction of labour","iol","first line"],
  "balloon": ["crb","cervical ripening balloon","induction of labour","iol"],
  "cervical ripening": ["crb","balloon","propess","induction","bishop score"],
  "bishop score": ["cervix","induction of labour","iol","crb","propess","amniotomy","arm"],
  "bishop": ["bishop score","cervix","induction","iol"],
  "arm": ["amniotomy","artificial rupture of membranes","induction","iol","oxytocin"],
  "amniotomy": ["arm","artificial rupture of membranes","induction","oxytocin","iol"],
  "oxytocin": ["syntocinon","augmentation","induction of labour","arm","amniotomy"],
  "syntocinon": ["oxytocin","augmentation","induction of labour"],
  "augmentation": ["oxytocin","syntocinon","arm","induction of labour"],
  "prostin": ["dinoprostone","gel","induction","iol","prom","second line"],
  "prom": ["pre-labour rupture of membranes","plrom","srom","waters breaking","term prom"],
  "plrom": ["prom","term prom","srom","rupture of membranes","induction of labour"],
  "srom": ["prom","plrom","rupture of membranes","waters broken","term prom","liquor"],
  "waters broken": ["srom","prom","plrom","rupture of membranes","liquor","pprom","amni-sure"],
  "water breaking": ["srom","prom","plrom","rupture of membranes"],
  "rupture of membranes": ["srom","prom","plrom","amnisure","liquor","term prom"],
  "hyperstimulation": ["propess","dinoprostone","terbutaline","induction","contractions","fhr"],
  "tachysystole": ["propess","contractions","induction","ctg"],
  "terbutaline": ["hyperstimulation","propess","tocolysis","uterine contractions"],
  // Skin & wound
  "cellulitis": ["wound","skin infection","soft tissue","cellulitis","redness","erythema","infected wound","co-amoxiclav","flucloxacillin"],
  "skin infection": ["cellulitis","wound","soft tissue","erythema","infected wound"],
  "wound infection": ["cellulitis","cs wound","wound","surgical site","co-amoxiclav"],
  "infected wound": ["cellulitis","wound infection","cs wound","co-amoxiclav"],
  "red wound": ["cellulitis","wound infection","erythema"],
  "perineal infection": ["perineal","episiotomy","wound","cellulitis","soft tissue"],
  // Seizure
  "fitting": ["eclampsia","seizure","convulsion","mgso4"],
  "fit": ["eclampsia","seizure","mgso4"],
  "seizure": ["eclampsia","fitting","convulsion","mgso4"],
  "convulsion": ["eclampsia","seizure","fitting","mgso4"],
  // Discharge
  "how long": ["length of stay","discharge","stay","duration"],
  "go home": ["discharge","criteria","length of stay"],
  "when can she leave": ["discharge criteria","discharge","length of stay"],
  // PET / hypertension
  "pe":  ["pre-eclampsia","preeclampsia","eclampsia","pet","hypertension in pregnancy"],
  "pet": ["pre-eclampsia","preeclampsia","hypertension in pregnancy","eclampsia"],
  "pih": ["pregnancy induced hypertension","pregnancy-induced hypertension","gestational hypertension","hypertension in pregnancy","pre-eclampsia"],
  "pregnancy induced hypertension": ["pih","gestational hypertension","hypertension in pregnancy","pre-eclampsia","ng133"],
  "gestational hypertension": ["pih","pregnancy induced hypertension","hypertension in pregnancy","pre-eclampsia","ng133"],
  "chronic hypertension pregnancy": ["pre-existing hypertension","ace inhibitor","arb","labetalol","nifedipine","ng133"],
  "hypertension in pregnancy": ["pih","gestational hypertension","pre-eclampsia","pet","ng133","labetalol","antihypertensive"],
  "aspirin pregnancy": ["aspirin","pre-eclampsia prevention","pih","gestational hypertension","ng133","75mg","150mg"],
  // BP / medication
  "bp meds": ["antihypertensive","labetalol","nifedipine","medication"],
  "blood pressure tablets": ["antihypertensive","labetalol","nifedipine"],
  "high bp": ["hypertension","blood pressure","antihypertensive"],
  // UTI
  "urine infection": ["uti","urinary tract infection","cystitis"],
  "water infection": ["uti","urinary tract infection","cystitis"],
  "wee infection": ["uti","cystitis"],
  "kidney infection": ["pyelonephritis","uti","renal"],
  // CS / section
  "section antibiotics": ["caesarean","lscs","prophylaxis","co-amoxiclav"],
  "cs antibiotics": ["caesarean","lscs","prophylaxis"],
  // GBS
  "gbs": ["group b strep","streptococcus","iap","benzylpenicillin","gtg36"],
  "strep b": ["gbs","group b strep","iap"],
  "group b streptococcus": ["gbs","strep b","iap","gtg36"],
  "gbs bacteriuria": ["gbs","group b strep","iap"],
  "gbs screening": ["gbs","universal screening","risk based","gtg36"],
  "early onset neonatal infection": ["gbs","neonatal sepsis","ng195","red flag neonatal"],
  "well baby observation": ["neonatal observation","gbs","ng195"],
  // Sepsis / infection
  "bug": ["infection","sepsis","antibiotics"],
  "womb infection": ["endometritis","uterus"],
  "infection after birth": ["endometritis","sepsis","postnatal","puerperal"],
  // Allergy
  "allergy": ["penicillin allergy","teicoplanin","clindamycin","alternative"],
  "pen allergy": ["penicillin allergy","teicoplanin","clindamycin"],
  // Breast
  "sore breast": ["mastitis","breast abscess","breast"],
  "breast infection": ["mastitis","breast abscess","cellulitis","flucloxacillin"],
  // Breastfeeding
  "breastfeed": ["breastfeeding","lactation","safe"],
  // Miscarriage — general
  "mc": ["miscarriage","early pregnancy loss","first trimester"],
  "miscarriage": ["missed miscarriage","incomplete miscarriage","complete miscarriage","threatened","early pregnancy loss"],
  "early pregnancy loss": ["miscarriage","first trimester","epagu"],
  "erpc": ["smm","surgical management of miscarriage","evacuation","surgical"],
  "evacuation": ["smm","erpc","surgical management of miscarriage","theatre"],
  "pregnancy loss": ["miscarriage","missed miscarriage","incomplete","complete"],
  "retained products": ["incomplete miscarriage","erpc","smm","poc","retained"],
  "poc": ["products of conception","retained products","histology","smm"],
  "products of conception": ["poc","retained products","smm","histology"],
  // Miscarriage — types
  "missed mc": ["missed miscarriage","no heartbeat","anembryonic"],
  "silent miscarriage": ["missed miscarriage","no heartbeat","anembryonic"],
  "blighted ovum": ["anembryonic","missed miscarriage","gestation sac"],
  "no heartbeat": ["missed miscarriage","fetal loss","anembryonic"],
  "incomplete mc": ["incomplete miscarriage","retained products","open os"],
  "threatened mc": ["threatened","viable","bleeding in pregnancy"],
  "threatened miscarriage": ["viable","threatened","bleeding","progesterone"],
  // Medical management of miscarriage
  "mifepristone": ["mifepristone","misoprostol","medical management","200mg"],
  "misoprostol": ["misoprostol","mifepristone","medical management","800mcg"],
  "medical miscarriage": ["mifepristone","misoprostol","medical management","cg621"],
  "pills for miscarriage": ["mifepristone","misoprostol","medical management"],
  // Ectopic
  "ectopic": ["ectopic pregnancy","methotrexate","mtx","bhcg","tubal","unruptured"],
  "ectopic pregnancy": ["methotrexate","mtx","bhcg","tubal","unruptured","ectopic"],
  "tube": ["ectopic pregnancy","tubal","fallopian","bhcg"],
  "mtx": ["methotrexate","ectopic","bhcg","day 4","day 7"],
  "methotrexate": ["mtx","ectopic","bhcg","day 4","day 7","cytotoxic"],
  "bhcg": ["beta hcg","ectopic","bhcg monitoring","day 4","day 7"],
  "beta hcg": ["bhcg","ectopic","monitoring"],
  "tubal": ["ectopic","tubal pregnancy","fallopian","mtx"],
  "shoulder tip pain": ["ectopic","haemorrhage","rupture","attend ed"],
  // Genital herpes in pregnancy (BASHH/RCOG 2024)
  "herpes": ["genital herpes","hsv","herpes simplex","aciclovir","valaciclovir","neonatal herpes","suppression","bashh hsv"],
  "genital herpes": ["hsv","herpes simplex virus","aciclovir","valaciclovir","caesarean","suppression","neonatal herpes"],
  "hsv": ["genital herpes","herpes simplex virus","aciclovir","valaciclovir","neonatal herpes"],
  "cold sore": ["herpes","hsv","neonatal herpes","cold sores","postnatal transmission"],
  "aciclovir": ["genital herpes","hsv","valaciclovir","suppression","antiviral"],
  "valaciclovir": ["genital herpes","hsv","aciclovir","suppression","antiviral"],
  "neonatal herpes": ["hsv","genital herpes","sem","paediatric infectious diseases","highest risk neonate"],
  // PPRoM
  "pprom": ["pprom","preterm","rupture of membranes","amoxicillin","azithromycin","liquor","amni-sure"],
  "leaking": ["srom","prom","pprom","rupture of membranes","liquor","amni-sure","waters broken"],
  "leaking fluid": ["srom","prom","pprom","rupture of membranes","liquor","amni-sure"],
  "membranes": ["pprom","rupture","liquor","preterm"],
  "liquor": ["pprom","amniotic fluid","amni-sure","rupture of membranes","oligohydramnios","deepest vertical pocket","uss rfm"],
  "amni-sure": ["pprom","liquor","rupture of membranes"],
  "preterm rupture": ["pprom","premature rupture","membranes","amoxicillin"],
  "chorioamnionitis": ["pprom","infection","antibiotics","delivery","sepsis"],
  // PUV / uncertain viability
  "uncertain viability": ["puv","pregnancy of uncertain viability","rescan","7-14 days"],
  "puv": ["uncertain viability","rescan","gestation sac","fetal pole"],
  "pul": ["pregnancy of unknown location","ectopic","bhcg","complete miscarriage"],
  "pregnancy of unknown location": ["pul","ectopic","bhcg","complete miscarriage"],
  // Iron deficiency anaemia
  "anaemia": ["iron deficiency","haemoglobin","ferritin","hb","oral iron","ferinject","iv iron","ida"],
  "anemia": ["iron deficiency","haemoglobin","ferritin","hb","oral iron","ferinject","iv iron","ida"],
  "ida": ["iron deficiency anaemia","ferritin","haemoglobin","ferinject","oral iron","enoxaparin"],
  "iron": ["iron deficiency","anaemia","ferritin","ferinject","oral iron","ferrous fumarate","ferrous sulphate"],
  "ferinject": ["iv iron","intravenous iron","ferric carboxymaltose","ganzoni","anaemia","ida"],
  "iv iron": ["ferinject","intravenous iron","ferric carboxymaltose","ganzoni","ida"],
  "ferritin": ["iron deficiency","anaemia","ida","ferrous fumarate","ferinject"],
  "ferrous fumarate": ["oral iron","iron","anaemia","ida","ferrous sulphate"],
  "ferrous sulphate": ["oral iron","iron","anaemia","ida","ferrous fumarate"],
  "low haemoglobin": ["anaemia","iron deficiency","hb","ida","ferinject"],
  "low hb": ["anaemia","iron deficiency","haemoglobin","ida","ferinject"],
  "ganzoni": ["ferinject","iv iron","iron deficit","dose calculation"],
  // ICP / obstetric cholestasis
  "icp": ["intrahepatic cholestasis","obstetric cholestasis","bile acids","pruritus","itch","udca"],
  "cholestasis": ["icp","intrahepatic cholestasis","bile acids","pruritus","itch","obstetric cholestasis"],
  "obstetric cholestasis": ["icp","intrahepatic cholestasis","bile acids","pruritus","itch"],
  "itching": ["icp","pruritus","bile acids","obstetric cholestasis","antihistamine"],
  "itch": ["icp","pruritus","bile acids","cholestasis","antihistamine","aqueous cream"],
  "pruritus": ["icp","itching","bile acids","cholestasis","antihistamine"],
  "bile acids": ["icp","cholestasis","udca","intrahepatic cholestasis","pruritus"],
  "udca": ["ursodeoxycholic acid","icp","cholestasis","bile acids"],
  "ursodeoxycholic": ["udca","icp","cholestasis","bile acids"],
  // VTE / DVT / PE
  "vte": ["venous thromboembolism","dvt","pe","pulmonary embolism","deep vein thrombosis","lmwh","enoxaparin","thromboprophylaxis"],
  "dvt": ["deep vein thrombosis","vte","lmwh","enoxaparin","thrombosis","thromboembolism"],
  "pulmonary embolism": ["pe","vte","lmwh","enoxaparin","thromboembolism","dvt"],
  "deep vein thrombosis": ["dvt","vte","lmwh","enoxaparin","thrombosis"],
  "clot": ["dvt","pe","vte","thrombosis","lmwh","enoxaparin"],
  "blood clot": ["dvt","pe","vte","thrombosis","lmwh","enoxaparin"],
  "enoxaparin": ["lmwh","heparin","vte","thromboprophylaxis","anti-xa","inhixa"],
  "lmwh": ["enoxaparin","heparin","vte","thromboprophylaxis","inhixa","low molecular weight"],
  "thromboprophylaxis": ["vte","lmwh","enoxaparin","dvt","pe","thromboembolism"],
  "anticoagulation": ["lmwh","enoxaparin","vte","heparin","therapeutic","prophylactic"],
  "heparin": ["lmwh","enoxaparin","vte","thromboprophylaxis","anti-xa"],
  "anti-xa": ["enoxaparin","lmwh","therapeutic","monitoring","anti xa"],
  "thrombophilia": ["antithrombin","protein c","protein s","antiphospholipid","aps","vte","lmwh"],
  // Diabetes
  "diabetes": ["gdm","gestational diabetes","type 1","type 2","insulin","dka","hba1c","glucose","vrii"],
  "gdm": ["gestational diabetes","ogtt","glucose","insulin","diabetes in pregnancy","hba1c"],
  "gestational diabetes": ["gdm","ogtt","glucose","insulin","diabetes in pregnancy","hba1c"],
  "dka": ["diabetic ketoacidosis","ketones","insulin","vrii","frii","acidosis","emergency"],
  "diabetic ketoacidosis": ["dka","ketones","insulin","vrii","frii","acidosis"],
  "insulin": ["diabetes","type 1","dka","vrii","frii","gdm","glucose","hba1c"],
  "vrii": ["variable rate insulin infusion","insulin","diabetes","sliding scale","glucose","dka"],
  "sliding scale": ["vrii","variable rate insulin infusion","insulin","diabetes"],
  "hba1c": ["diabetes","gdm","glucose","insulin","type 1","type 2"],
  "ketones": ["dka","diabetic ketoacidosis","diabetes","insulin","vrii","acidosis"],
  "ogtt": ["oral glucose tolerance test","gdm","gestational diabetes","glucose"],
  "glucose": ["diabetes","gdm","dka","insulin","vrii","blood sugar","cbg"],
  "blood sugar": ["glucose","diabetes","gdm","dka","insulin","cbg"],
  "type 1 diabetes": ["type 1","diabetes","insulin","dka","vrii","cgm","hba1c"],
  "type 2 diabetes": ["type 2","diabetes","metformin","insulin","gdm","hba1c"],
  "metformin": ["diabetes","gdm","type 2 diabetes","insulin","glucose"],
  // Multiple pregnancy / twins / triplets
  "twins": ["twin pregnancy","multiple pregnancy","monochorionic","dichorionic","mcda","dcda","mcma"],
  "twin": ["twin pregnancy","multiple pregnancy","monochorionic","dichorionic"],
  "triplets": ["triplet pregnancy","multiple pregnancy","trichorionic","monochorionic"],
  "triplet": ["triplet pregnancy","multiple pregnancy","trichorionic"],
  "multiple pregnancy": ["twins","triplets","twin pregnancy","triplet pregnancy","monochorionic","dichorionic"],
  "chorionicity": ["monochorionic","dichorionic","trichorionic","shared placenta","lambda sign","t-sign","chorionicity"],
  "amnionicity": ["monoamniotic","diamniotic","triamniotic","amniotic sac"],
  "monochorionic": ["mc","mcda","mcma","shared placenta","twin to twin transfusion","ttts","ffts"],
  "dichorionic": ["dc","dcda","dcta","twin pregnancy","triplet"],
  "mcda": ["monochorionic diamniotic","monochorionic","twins","ttts","ffts","fetal monitoring"],
  "mcma": ["monochorionic monoamniotic","monochorionic","twins","higher risk","tertiary referral"],
  "dcda": ["dichorionic diamniotic","dichorionic","twins"],
  "ttts": ["twin to twin transfusion","twin-to-twin transfusion","feto-fetal transfusion","ffts","monochorionic","laser ablation"],
  "ffts": ["feto-fetal transfusion syndrome","twin to twin transfusion","ttts","monochorionic"],
  "twin to twin transfusion": ["ttts","ffts","feto-fetal transfusion","monochorionic","laser ablation","tertiary referral"],
  "taps": ["twin anaemia polycythaemia sequence","twin anemia polycythemia","monochorionic","tertiary referral"],
  "trap": ["twin reverse arterial perfusion","acardiac twin","monochorionic","tertiary referral"],
  "fetal weight discordance": ["weight discordance","growth discordance","fgr","iugr","25%","fetal growth restriction"],
  "weight discordance": ["fetal weight discordance","fgr","iugr","biometry","ultrasound"],
  "laser ablation": ["fetoscopic laser","ttts","ffts","monochorionic","tertiary referral","fetal medicine"],
  "fetal medicine": ["fmc","tertiary referral","fetal medicine centre","ttts","laser ablation"],
  "birth plan": ["delivery plan","mode of delivery","mode of birth","caesarean","vaginal birth","twins","28 weeks"],
  "twin clinic": ["multiple pregnancy","mdt","specialist obstetrician","specialist midwife"],
  "quintero staging": ["ttts","twin to twin transfusion","ttts staging","laser ablation"],
  "sfgr": ["selective fetal growth restriction","selective growth restriction","monochorionic","fetal growth restriction"],
  "selective fetal growth restriction": ["sfgr","selective growth restriction","monochorionic"],
  "timing of birth twins": ["ng137","twin pregnancy","dcda","mcda","mcma","elective birth twins"],
  "obesity": ["obesity in pregnancy","bmi","class 1 obesity","class 2 obesity","morbid obesity","gtg72"],
  "obesity in pregnancy": ["obesity","bmi","morbid obesity","gtg72"],
  "bmi": ["obesity","obesity in pregnancy","body mass index"],
  "morbid obesity": ["obesity","class 3 obesity","bmi 40","gtg72"],
  "folic acid 5mg": ["obesity in pregnancy","high dose folic acid","folic acid"],
  // Antenatal care / QS22
  "booking": ["booking appointment","antenatal booking","10 weeks","first appointment","antenatal care"],
  "booking appointment": ["booking","antenatal booking","10 weeks","first antenatal","risk assessment"],
  "antenatal care": ["booking","appointments","antenatal","midwife","risk assessment","qs22"],
  "antenatal appointments": ["appointment schedule","booking","nulliparous","multiparous","antenatal care"],
  "nulliparous": ["first pregnancy","primiparous","10 appointments","nulliparous schedule","primigravida"],
  "multiparous": ["previous birth","multipara","7 appointments","multiparous schedule","multigravida"],
  "continuity of carer": ["named midwife","small team","midwife team","continuity of care","caseload midwifery"],
  "named midwife": ["continuity of carer","midwife team","small team","antenatal care"],
  "flu vaccine": ["influenza vaccine","flu jab","flu in pregnancy","vaccines pregnancy"],
  "whooping cough": ["pertussis","pertussis vaccine","tdap","whooping cough vaccine","vaccines pregnancy"],
  "pertussis": ["whooping cough","pertussis vaccine","tdap","whooping cough vaccine"],
  "carbon monoxide": ["co test","co testing","smoking","4 ppm","opt-out referral","stop smoking"],
  "co test": ["carbon monoxide","co monitor","smoking","4 ppm","stop smoking service","opt-out"],
  "smoking": ["carbon monoxide","co test","stop smoking","opt-out referral","tobacco","cigarette"],
  "stop smoking": ["smoking cessation","carbon monoxide","co test","opt-out referral","sss"],
  "opt-out referral": ["stop smoking","carbon monoxide","co test","smoking referral","sss"],
  "foods to avoid": ["food safety","listeria","raw meat","liver","soft cheese","sushi","shellfish","food in pregnancy"],
  "food safety pregnancy": ["foods to avoid","listeria","raw meat","liver","soft cheese","food safety","nutrition"],
  "listeria": ["listeriosis","soft cheese","pate","deli meat","foods to avoid","food safety pregnancy"],
  "soft cheese": ["listeria","brie","camembert","stilton","foods to avoid","food safety"],
  "folic acid": ["folate","supplements pregnancy","neural tube defect","400 micrograms","5mg folic acid"],
  "vitamin d": ["supplements pregnancy","vitamin d in pregnancy","10 micrograms","folic acid"],
  "complex social factors": ["substance misuse","domestic abuse","homelessness","immigration","booking","vulnerable"],
  "domestic abuse": ["intimate partner violence","safeguarding","complex social factors","booking","domestic violence"],
  "late booking": ["late presenter","booking","10 weeks","self-referral","antenatal care"],
  "self referral": ["self-referral","late booking","booking","antenatal care","maternity services"],
  "sfh": ["symphysis fundal height","fundal height","growth","fgr","small for dates"],
  "symphysis fundal height": ["sfh","fundal height","growth","fgr","small for dates"],
  "membrane sweep": ["sweep","40 weeks","41 weeks","induction of labour","overdue"],
  // Reduced fetal movements / GTG57
  "rfm": ["reduced fetal movements","decreased fetal movements","fetal movements","baby not moving","baby moving less"],
  "reduced fetal movements": ["rfm","decreased fetal movements","baby not moving","fetal movement","stillbirth risk"],
  "decreased fetal movements": ["rfm","reduced fetal movements","baby not moving","fetal activity"],
  "baby not moving": ["rfm","reduced fetal movements","decreased fetal movements","fetal death"],
  "baby moving less": ["rfm","reduced fetal movements","fetal movements","fetal wellbeing"],
  "fetal movements": ["rfm","reduced fetal movements","fetal activity","fetal wellbeing","movement pattern"],
  "kick counting": ["fetal movement counting","rfm","fetal movements","10 movements","count to ten"],
  "fetal movement counting": ["kick counting","rfm","reduced fetal movements","fetal wellbeing"],
  "iufd": ["intrauterine fetal death","stillbirth","rfm","fetal death","baby died"],
  "stillbirth": ["iufd","fetal death","rfm","reduced fetal movements","stillbirth risk"],
  "fetal death": ["iufd","stillbirth","rfm","reduced fetal movements"],
  "fetal compromise": ["rfm","ctg","fetal distress","fetal wellbeing","acute compromise"],
  "ctg rfm": ["cardiotocograph","fetal monitoring","reactive ctg","rfm","fetal wellbeing"],
  "reactive ctg": ["normal ctg","fhr accelerations","fetal wellbeing","ctg rfm"],
  "sinusoidal ctg": ["sinusoidal trace","fmh","fetomaternal haemorrhage","fetal anaemia","rfm"],
  "fetal anaemia": ["fmh","fetomaternal haemorrhage","mca doppler","kleihauer","sinusoidal ctg"],
  "fetomaternal haemorrhage": ["fmh","kleihauer","mca doppler","fetal anaemia","sinusoidal","anti-d","rhd negative","aph"],
  "kleihauer": ["kleihauer betke","fmh","fetomaternal haemorrhage","fetal anaemia"],
  "oligohydramnios": ["reduced liquor","amniotic fluid","rfm","fgr","sga","uss rfm"],
  "sga": ["small for gestational age","fgr","iugr","rfm","efw below 10th centile","growth restriction"],
  "small for gestational age": ["sga","fgr","iugr","rfm","growth restriction","efw"],
  "fgr": ["fetal growth restriction","sga","iugr","rfm","placental insufficiency","small for dates"],
  "fetal growth restriction": ["fgr","sga","iugr","rfm","placental insufficiency","umbilical artery doppler"],
  "placental insufficiency": ["fgr","sga","rfm","stillbirth","umbilical artery doppler","placental dysfunction"],
  "umbilical artery doppler": ["uad","doppler rfm","fgr","sga","rfm","absent end diastolic flow","aedf"],
  "absent end diastolic flow": ["aedf","reversed flow","umbilical artery doppler","fgr","severe fgr"],
  "cpr": ["cerebroplacental ratio","rfm","mca doppler","umbilical artery doppler","fetal wellbeing"],
  "cerebroplacental ratio": ["cpr","mca pi","umbilical artery doppler","rfm","fetal wellbeing"],
  "mca doppler": ["middle cerebral artery","cpr","fetal anaemia","rfm","fmh"],
  "recurrent rfm": ["recurrent reduced fetal movements","repeated rfm","multiple rfm","rfm twice"],
  "excessive fetal movements": ["increased fetal movements","frantic movements","violent movements","rfm","stillbirth"],
  "anterior placenta rfm": ["anterior placenta","reduced movements","perception","rfm"],
  "biophysical profile": ["bpp","fetal wellbeing","rfm","amniotic fluid","fetal tone"],
  // Antepartum haemorrhage / GTG63
  "aph": ["antepartum haemorrhage","bleeding in pregnancy","antenatal bleeding","antepartum bleeding"],
  "antepartum haemorrhage": ["aph","bleeding in pregnancy","placental abruption","placenta praevia"],
  "antepartum bleeding": ["aph","vaginal bleeding pregnancy","bleeding 24 weeks","antepartum haemorrhage"],
  "bleeding in pregnancy": ["aph","antepartum haemorrhage","vaginal bleeding","placental abruption","placenta praevia"],
  "placental abruption": ["abruption","abruptio placentae","retroplacental haemorrhage","aph","concealed abruption"],
  "abruption": ["placental abruption","abruptio placentae","concealed haemorrhage","revealed haemorrhage","aph"],
  "abruptio placentae": ["placental abruption","abruption","retroplacental clot","aph"],
  "placenta praevia": ["low lying placenta","praevia","placenta previa","low placenta","aph","gtg27a"],
  "low lying placenta": ["placenta praevia","praevia","placenta previa","low placenta","gtg27a"],
  "praevia": ["placenta praevia","low lying placenta","low placenta","bleeding praevia"],
  "vasa praevia": ["vasa previa","fetal vessel rupture","umbilical cord vessel","srom bleeding","gtg27b"],
  "vasa previa": ["vasa praevia","fetal vessel rupture","umbilical cord vessel","gtg27b"],
  "placenta accreta": ["placenta accreta spectrum","pas","placenta increta","placenta percreta","gtg27a"],
  "placenta accreta spectrum": ["placenta accreta","pas","placenta increta","placenta percreta"],
  "pas": ["placenta accreta spectrum","placenta accreta","placenta increta","placenta percreta"],
  "placenta increta": ["placenta accreta spectrum","placenta accreta","placenta percreta"],
  "placenta percreta": ["placenta accreta spectrum","placenta accreta","placenta increta"],
  "velamentous cord insertion": ["vasa praevia","bilobed placenta","succenturiate lobe"],
  "bilobed placenta": ["succenturiate lobe","vasa praevia","velamentous cord insertion"],
  "succenturiate lobe": ["bilobed placenta","vasa praevia","velamentous cord insertion"],
  "caesarean hysterectomy": ["placenta accreta","placenta accreta spectrum","pas","peripartum hysterectomy"],
  "concealed abruption": ["concealed haemorrhage","retroplacental clot","hidden bleeding","placental abruption"],
  "revealed abruption": ["revealed haemorrhage","vaginal bleeding abruption","placental abruption"],
  "woody uterus": ["tense uterus","board-like abdomen","abruption signs","placental abruption"],
  "board-like abdomen": ["woody uterus","tense uterus","abruption","rigid abdomen"],
  "massive haemorrhage": ["major haemorrhage","obstetric haemorrhage","blood loss shock","haemorrhagic shock","massive aph"],
  "major haemorrhage protocol": ["massive haemorrhage","obstetric haemorrhage","mhp","blood products"],
  "obstetric haemorrhage": ["massive haemorrhage","aph","pph","major haemorrhage protocol","blood products"],
  "dic": ["disseminated intravascular coagulation","consumptive coagulopathy","coagulopathy abruption","clotting failure"],
  "disseminated intravascular coagulation": ["dic","consumptive coagulopathy","coagulopathy","abruption"],
  "blood products": ["fresh frozen plasma","ffp","cryoprecipitate","platelets transfusion","crossmatch","blood transfusion"],
  "ffp": ["fresh frozen plasma","blood products","coagulation factors","dic","massive haemorrhage"],
  "fresh frozen plasma": ["ffp","blood products","coagulation factors","massive haemorrhage"],
  "cryoprecipitate": ["cryo","fibrinogen replacement","blood products","dic","massive haemorrhage"],
  "kleihauer betke": ["kleihauer","fmh","fetomaternal haemorrhage","anti-d dose","rhd negative"],
  "fmh": ["fetomaternal haemorrhage","kleihauer","anti-d","rhd negative"],
  "anti-d": ["anti-d immunoglobulin","rhesus prophylaxis","rhd negative","rh negative","kleihauer","anti-d ig"],
  "anti-d immunoglobulin": ["anti-d","rhesus prophylaxis","rhd negative","500 iu","fetomaternal haemorrhage"],
  "rhd negative": ["rh negative","rhesus negative","anti-d","group and screen","anti-d ig"],
  "rhesus negative": ["rhd negative","rh negative","anti-d","anti-d immunoglobulin","kleihauer"],
  "rhesus prophylaxis": ["anti-d","anti-d immunoglobulin","rhd negative","kleihauer"],
  "raadp": ["routine antenatal anti-d prophylaxis","anti-d","anti-d immunoglobulin","28 weeks anti-d"],
  "sensitising event": ["sensitizing event","anti-d","potentially sensitising event","kleihauer","fetomaternal haemorrhage"],
  "sensitizing event": ["sensitising event","anti-d","kleihauer"],
  // Heavy Menstrual Bleeding / NG88
  "hmb": ["heavy menstrual bleeding","menorrhagia","heavy periods","flooding","menstrual blood loss","abnormal uterine bleeding"],
  "menorrhagia": ["hmb","heavy menstrual bleeding","heavy periods","flooding","aub","ng88"],
  "heavy periods": ["hmb","menorrhagia","heavy menstrual bleeding","flooding","clots","menstrual blood loss"],
  "heavy bleeding periods": ["hmb","menorrhagia","heavy menstrual bleeding","abnormal uterine bleeding"],
  "flooding": ["hmb","heavy menstrual bleeding","menorrhagia","pads","menstrual blood loss"],
  "menstrual clots": ["hmb","heavy periods","menorrhagia","flooding"],
  "abnormal uterine bleeding": ["aub","hmb","menorrhagia","imb","pcb","pmb","intermenstrual"],
  "aub": ["abnormal uterine bleeding","hmb","menorrhagia","intermenstrual bleeding"],
  "intermenstrual bleeding": ["imb","abnormal uterine bleeding","aub","polyp","endometrial","cervical"],
  "imb": ["intermenstrual bleeding","abnormal uterine bleeding","polyp","endometrial pathology"],
  "postcoital bleeding": ["pcb","cervical pathology","polyp","cervical ectropion","endometrial"],
  "pcb": ["postcoital bleeding","cervical","polyp","smear","colposcopy"],
  "postmenopausal bleeding": ["pmb","endometrial cancer","endometrial hyperplasia","2ww","urgent referral"],
  "pmb": ["postmenopausal bleeding","endometrial cancer","2ww","urgent referral","endometrial thickening"],
  "two week wait gynaecology": ["2ww","pmb","urgent referral","endometrial cancer","suspected cancer"],
  // LNG-IUS / Mirena
  "lng-ius": ["mirena","levonorgestrel iud","levonorgestrel coil","iud hmb","coil hmb","intrauterine system"],
  "mirena": ["lng-ius","levonorgestrel","coil","intrauterine system","hmb treatment","contraception hmb"],
  "coil hmb": ["lng-ius","mirena","levonorgestrel","intrauterine system","hmb treatment"],
  "intrauterine system": ["lng-ius","mirena","levonorgestrel","coil","hmb treatment"],
  // Pharmacological HMB treatment
  "tranexamic acid": ["hmb treatment","antifibrinolytic","menorrhagia treatment","non-hormonal","cyklokapron"],
  "mefenamic acid": ["nsaid","ponstan","hmb","dysmenorrhoea","menstrual pain","non-hormonal hmb"],
  "norethisterone": ["progestogen","hmb treatment","norethindrone","dysmenorrhoea","progesterone hmb"],
  "gnrh analogue": ["goserelin","zoladex","leuprorelin","prostap","nafarelin","buserelin","fibroid treatment","hmb bridge"],
  "goserelin": ["zoladex","gnrh analogue","fibroid shrinkage","hmb","pre-operative"],
  "zoladex": ["goserelin","gnrh analogue","fibroid","hmb","medical menopause"],
  "relugolix": ["ryeqo","gnrh antagonist","fibroid treatment","hmb treatment","add-back hrt"],
  "ryeqo": ["relugolix","gnrh antagonist","fibroid","hmb","oral gnrh"],
  // Uterine fibroids
  "fibroid": ["uterine fibroid","leiomyoma","myoma","submucosal fibroid","intramural fibroid","hmb fibroids"],
  "fibroids": ["uterine fibroids","leiomyomata","myomata","submucosal","intramural","subserosal","hmb fibroids"],
  "uterine fibroid": ["fibroid","leiomyoma","myoma","hmb","bulk symptoms","uae","myomectomy"],
  "leiomyoma": ["fibroid","uterine fibroid","myoma","leiomyomata","hmb"],
  "submucosal fibroid": ["submucous fibroid","figo type 0","figo type 1","figo type 2","hmb fibroid","hysteroscopic myomectomy"],
  "submucous fibroid": ["submucosal fibroid","figo type 0","figo type 1","figo type 2","hmb fibroid","hysteroscopic myomectomy"],
  "intramural fibroid": ["fibroid","leiomyoma","hmb","myomectomy","uae"],
  "subserosal fibroid": ["fibroid","bulk symptoms","pressure symptoms","myomectomy","uae"],
  // Fibroid treatment
  "uae": ["uterine artery embolisation","fibroid embolisation","uterine embolisation","interventional radiology fibroid"],
  "uterine artery embolisation": ["uae","fibroid embolisation","interventional radiology","fibroids","hmb"],
  "myomectomy": ["fibroid removal","uterine fibroid surgery","laparoscopic myomectomy","open myomectomy","hysteroscopic myomectomy"],
  "hysteroscopic myomectomy": ["myomectomy","submucosal fibroid","fibroid resection","tcre","hysteroscopy fibroid"],
  // Endometrial ablation
  "endometrial ablation": ["ablation","novasure","thermachoice","mea","tcre","hmb surgery"],
  "ablation": ["endometrial ablation","novasure","thermachoice","mea","hmb treatment","no more periods"],
  "novasure": ["endometrial ablation","ablation","hmb","no more periods","nea"],
  "tcre": ["transcervical resection","ablation","endometrial resection","hysteroscopic","hmb surgery"],
  // Adenomyosis
  "adenomyosis": ["adenomyosis","uterine adenomyosis","endometrium myometrium","dysmenorrhoea hmb","adenomyoma"],
  "adenomyoma": ["adenomyosis","focal adenomyosis","hmb","dysmenorrhoea"],
  // Endometrial pathology
  "endometrial polyp": ["polyp","uterine polyp","endometrial polyp","imb","hysteroscopy polyp","polypectomy"],
  "uterine polyp": ["endometrial polyp","polyp","imb","intermenstrual bleeding","hysteroscopy"],
  "polypectomy": ["hysteroscopic polypectomy","polyp removal","hysteroscopy","endometrial polyp"],
  "endometrial hyperplasia": ["hyperplasia","aeh","ein","endometrial cancer risk","lng-ius hyperplasia","progestogen hyperplasia"],
  "hyperplasia": ["endometrial hyperplasia","aeh","ein","endometrial cancer","lng-ius hyperplasia","progestogen hyperplasia"],
  "atypical hyperplasia": ["aeh","ein","endometrial intraepithelial neoplasia","endometrial cancer","hysterectomy","hysterectomy aeh"],
  "aeh": ["atypical endometrial hyperplasia","endometrial intraepithelial neoplasia","ein","endometrial cancer risk","oncology referral","hysterectomy"],
  "ein": ["endometrial intraepithelial neoplasia","aeh","atypical hyperplasia","endometrial cancer","hysterectomy","fertility sparing"],
  // Hysteroscopy
  "hysteroscopy": ["hysteroscopic","outpatient hysteroscopy","diagnostic hysteroscopy","therapeutic hysteroscopy","see and treat"],
  "outpatient hysteroscopy": ["hysteroscopy","no-touch hysteroscopy","see and treat","office hysteroscopy","polyp hmb"],
  "pipelle biopsy": ["endometrial biopsy","pipelle","endometrial sampling","histology","endometrial cancer"],
  "endometrial biopsy": ["pipelle biopsy","endometrial sampling","histology","endometrial cancer","hyperplasia"],
  // Hysterectomy
  "hysterectomy": ["womb removal","hysterectomy hmb","total hysterectomy","laparoscopic hysterectomy","vaginal hysterectomy"],
  "womb removal": ["hysterectomy","total hysterectomy","subtotal hysterectomy"],
  "tlh": ["total laparoscopic hysterectomy","laparoscopic hysterectomy","minimally invasive hysterectomy","keyhole hysterectomy"],
  // Saline infusion sonography
  "sis": ["saline infusion sonography","shg","sonohysterography","endometrial polyp uss","submucosal fibroid uss"],
  "saline infusion sonography": ["sis","shg","sonohysterography","polyp","submucosal fibroid","endometrial cavity"],
  // Von Willebrand / coagulopathy HMB
  "von willebrand": ["vwd","von willebrand disease","coagulopathy hmb","bleeding disorder periods","vwf","desmopressin"],
  "vwd": ["von willebrand disease","coagulopathy","hmb since menarche","bleeding disorder","vwf"],
  "coagulopathy hmb": ["von willebrand disease","vwd","inherited bleeding disorder","hmb","haematology"],
  "desmopressin": ["ddavp","von willebrand disease","vwd","coagulopathy hmb","intranasal desmopressin"],
  // Dysmenorrhoea
  "dysmenorrhoea": ["period pain","painful periods","menstrual cramps","adenomyosis","endometriosis","hmb pain"],
  "period pain": ["dysmenorrhoea","painful periods","menstrual cramps","mefenamic acid","ibuprofen","nsaid"],
  "painful periods": ["dysmenorrhoea","period pain","menstrual cramps","nsaid","adenomyosis","endometriosis"],
  // PCOS
  "pcos": ["polycystic ovary syndrome","anovulation","irregular periods","oligomenorrhoea","hmb","endometrial hyperplasia risk"],
  "polycystic ovary syndrome": ["pcos","anovulation","oligomenorrhoea","irregular periods","endometrial protection"],
  "anovulation": ["pcos","irregular periods","oligomenorrhoea","endometrial hyperplasia","progesterone"],
  // Perimenopause
  "perimenopause": ["perimenopausal","menopause transition","climacteric","irregular periods perimenopause","hmb perimenopause"],
  "perimenopausal hmb": ["perimenopause","menopause transition","irregular periods","endometrial biopsy","lng-ius perimenopause"],
  // Acute / ED HMB
  "acute heavy bleeding": ["hmb","menorrhagia","flooding","resuscitation","tranexamic acid","norethisterone","transfusion","ed","emergency"],
  "heavy bleeding ed": ["hmb","acute menorrhagia","flooding","resuscitation","major haemorrhage","tranexamic acid"],
  "acute menorrhagia": ["hmb","acute heavy bleeding","norethisterone","tranexamic acid","transfusion"],
  // General period terms
  "period problems": ["hmb","menorrhagia","heavy periods","dysmenorrhoea","amenorrhoea","irregular periods"],
  "irregular periods": ["oligomenorrhoea","anovulation","pcos","perimenopause","amenorrhoea"],
  "oligomenorrhoea": ["infrequent periods","irregular periods","anovulation","pcos","perimenopause"],
  "amenorrhoea": ["no periods","lng-ius","ablation","menopause","secondary amenorrhoea"],
  "no periods": ["amenorrhoea","lng-ius side effect","ablation","menopause","pregnancy"],
  "bulk symptoms": ["fibroid pressure","urinary frequency fibroid","bladder pressure fibroid","pelvic pressure","fibroid size"],
  "pbac": ["pictorial blood assessment chart","menstrual blood loss score","menstrual calendar","hmb scoring"],
  // Endometrial Hyperplasia / GTG67
  "gtg67": ["endometrial hyperplasia","rcog","bsge","gtg67","green top guideline 67"],
  "hyperplasia without atypia": ["benign hyperplasia","endometrial hyperplasia","progestogen","lng-ius","surveillance"],
  "endometrial intraepithelial neoplasia": ["ein","aeh","atypical hyperplasia","endometrial cancer","hysterectomy"],
  "endometrial cancer risk": ["endometrial hyperplasia","aeh","ein","obesity endometrial","pcos endometrial","tamoxifen endometrial"],
  "fertility sparing hyperplasia": ["conservative aeh","lng-ius aeh","progestogen aeh","endometrial hyperplasia fertility"],
  "conservative hyperplasia": ["fertility sparing","lng-ius aeh","progestogen aeh","mpa hyperplasia"],
  "mpa": ["medroxyprogesterone acetate","oral progestogen","hyperplasia treatment","endometrial hyperplasia"],
  "medroxyprogesterone acetate": ["mpa","oral progestogen","depo","endometrial hyperplasia"],
  "megestrol": ["megestrol acetate","oral progestogen","aeh treatment","fertility sparing"],
  "lynch syndrome": ["hnpcc","mismatch repair","mlh1","msh2","endometrial cancer risk","lynch endometrial"],
  "hnpcc": ["lynch syndrome","hereditary nonpolyposis colorectal cancer","mismatch repair","endometrial cancer"],
  "tamoxifen endometrial": ["tamoxifen uterus","tamoxifen hyperplasia","tamoxifen bleeding","endometrial cancer tamoxifen"],
  "endometrial surveillance": ["endometrial biopsy surveillance","hyperplasia follow-up","6 monthly biopsy","surveillance hyperplasia"],
  "progestogen endometrium": ["endometrial hyperplasia","progestogen treatment","norethisterone endometrium","mpa endometrium","lng-ius endometrium"],
  // Cervical Screening & Colposcopy — NHSCSP20
  "nhscsp20": ["cervical screening","colposcopy","nhscsp","nhscsp20","cin","hpv","cervical cancer"],
  "nhscsp": ["nhscsp20","cervical screening","nhs cervical screening programme","colposcopy management"],
  "cervical screening": ["smear test","cervical smear","pap smear","colposcopy","hpv test","cin","nhscsp"],
  "smear test": ["cervical screening","cervical smear","colposcopy","hpv test","nhscsp"],
  "cervical smear": ["smear test","cervical screening","liquid based cytology","lbc","pap smear"],
  "hpv test": ["human papillomavirus","hrhpv","hpv primary screening","cervical screening","hpv positive"],
  "hpv positive": ["hrhpv positive","colposcopy referral","cytology","cin","cervical screening"],
  "hrhpv": ["high risk hpv","human papillomavirus","hpv primary screening","hpv positive","colposcopy"],
  "high risk hpv": ["hrhpv","hpv 16","hpv 18","colposcopy","cervical screening","cin"],
  "hpv primary screening": ["nhscsp","hrhpv","cervical screening","liquid based cytology","hpv test"],
  "liquid based cytology": ["lbc","cytology","thinprep","cervical smear","dyskaryosis"],
  "lbc": ["liquid based cytology","cytology","cervical smear","dyskaryosis","borderline"],
  "dyskaryosis": ["dysplasia","cin","colposcopy","cytology","borderline","mild dyskaryosis","moderate dyskaryosis","severe dyskaryosis"],
  "borderline changes": ["borderline nuclear changes","bnc","dyskaryosis","colposcopy referral","hpv triage"],
  "mild dyskaryosis": ["low grade dyskaryosis","cin1","colposcopy","borderline","hpv positive cytology"],
  "moderate dyskaryosis": ["high grade dyskaryosis","cin2","colposcopy","lletz","see and treat"],
  "severe dyskaryosis": ["high grade dyskaryosis","cin3","colposcopy","lletz","urgent colposcopy"],
  "colposcopy": ["cervical screening","cin","lletz","biopsy","transformation zone","acetowhite","nhscsp20"],
  "cin": ["cervical intraepithelial neoplasia","cin1","cin2","cin3","colposcopy","dysplasia","cervical screening"],
  "cin1": ["mild dysplasia","cin 1","cervical intraepithelial neoplasia grade 1","watch and wait","surveillance cin","hpv positive cin"],
  "cin2": ["moderate dysplasia","cin 2","cervical intraepithelial neoplasia grade 2","lletz cin2","conservative cin2","watch and wait cin2"],
  "cin3": ["severe dysplasia","cin 3","cervical intraepithelial neoplasia grade 3","carcinoma in situ","cis","lletz cin3","mandatory treatment cin"],
  "cervical intraepithelial neoplasia": ["cin","cin1","cin2","cin3","dysplasia","colposcopy","lletz"],
  "cgin": ["cervical glandular intraepithelial neoplasia","adenocarcinoma in situ","ais","glandular lesion cervix","high grade cgin","cone biopsy cgin"],
  "glandular neoplasia cervix": ["cgin","adenocarcinoma in situ","ais","glandular dysplasia","cone biopsy"],
  "lletz": ["large loop excision transformation zone","loop excision","leep","cin treatment","lletz cin","excision cervix"],
  "large loop excision": ["lletz","loop excision","transformation zone","cin treatment","cone biopsy"],
  "ckc": ["cold knife cone","cone biopsy","cin treatment","cgin treatment","complex cin","ckc cervix"],
  "cold knife cone": ["ckc","cone biopsy","cgin","large lesion cin","theatre cin"],
  "cone biopsy": ["ckc","cold knife cone","cin treatment","cgin","excision cervix"],
  "see and treat": ["see and treat colposcopy","lletz","high grade dyskaryosis","colposcopy treatment","no biopsy first"],
  "transformation zone": ["tz","lletz","type 1 transformation zone","type 3 transformation zone","acetowhite"],
  "acetowhite": ["acetic acid","colposcopy finding","cin","transformation zone","grade 1 colposcopy","grade 2 colposcopy"],
  "test of cure": ["toc","post treatment hpv","6 month hpv test","post lletz","surveillance cin"],
  "toc": ["test of cure","post treatment hpv test","cin follow-up","6 months post treatment"],
  "post treatment hpv": ["test of cure","toc","hpv after lletz","surveillance","cin follow-up"],
  "positive margins": ["incomplete excision","endocervical margin","ectocervical margin","re-excision cin","repeat lletz"],
  "incomplete excision": ["positive margins","endocervical margin positive","residual cin","re-excision"],
  "cervical screening pregnancy": ["colposcopy pregnancy","cin in pregnancy","smear test pregnancy","deferred treatment cin","cin postpartum"],
  "colposcopy pregnancy": ["cin pregnancy","lletz deferred","treatment deferred","pregnancy cervix","cin management pregnancy"],
  "cin pregnancy": ["colposcopy pregnancy","treatment deferred","3 monthly colposcopy","postpartum lletz"],
  "hpv vaccination": ["gardasil","hpv vaccine","cervical cancer prevention","hpv 16 18","nhscsp vaccination"],
  "gardasil": ["hpv vaccination","gardasil 9","hpv vaccine","cervical cancer prevention"],
  "immunosuppressed cervical": ["hiv cervical screening","transplant screening","annual smear","immunocompromised hpv"],
  "hiv cervical": ["hiv positive screening","annual smear hiv","colposcopy hiv","hpv hiv"],
  "annual screening cervical": ["hiv screening","immunosuppressed screening","annual smear","cervical hiv"],

  "maternal collapse": ["cardiac arrest","cardiac arrest pregnancy","obstetric cardiac arrest","collapse in pregnancy","gtg56"],
  "cardiac arrest": ["maternal collapse","obstetric cardiac arrest","cardiac arrest pregnancy","cpr pregnancy","perimortem caesarean"],
  "obstetric cardiac arrest": ["maternal collapse","cardiac arrest pregnancy","cpr pregnancy","4hs 4ts","perimortem caesarean"],
  "collapse": ["maternal collapse","cardiac arrest pregnancy","obstetric emergency","loss of consciousness pregnancy"],
  "perimortem caesarean": ["pmcs","emergency hysterotomy","resuscitative hysterotomy","perimortem caesarean section","4 minute rule"],
  "pmcs": ["perimortem caesarean section","emergency hysterotomy","resuscitative hysterotomy","maternal collapse"],
  "resuscitative hysterotomy": ["pmcs","perimortem caesarean section","emergency hysterotomy"],
  "amniotic fluid embolism": ["afe","collapse in labour","sudden collapse birth","maternal collapse"],
  "afe": ["amniotic fluid embolism","maternal collapse","collapse in labour"],
  "aortocaval compression": ["left lateral tilt","manual uterine displacement","supine hypotension","maternal collapse"],
  "manual uterine displacement": ["aortocaval compression","left lateral tilt","up off and over","cpr pregnancy"],
  "local anaesthetic toxicity": ["la toxicity","intralipid","lipid rescue","local anaesthetic overdose"],
  "lipid rescue": ["intralipid","local anaesthetic toxicity","la toxicity"],
  "intralipid": ["lipid rescue","local anaesthetic toxicity","la toxicity"],

  "shoulder dystocia": ["impacted shoulders","turtle sign","mcroberts","gtg42","brachial plexus injury"],
  "mcroberts": ["mcroberts manoeuvre","shoulder dystocia","suprapubic pressure"],
  "mcroberts manoeuvre": ["mcroberts","shoulder dystocia","suprapubic pressure"],
  "suprapubic pressure": ["mcroberts","shoulder dystocia","rubin manoeuvre"],
  "turtle sign": ["shoulder dystocia","impacted shoulders"],
  "rubin manoeuvre": ["woods screw","shoulder dystocia","internal rotation shoulder"],
  "woods screw": ["rubin manoeuvre","shoulder dystocia","internal rotation shoulder"],
  "all fours position": ["gaskin manoeuvre","shoulder dystocia","all-fours"],
  "gaskin manoeuvre": ["all fours position","shoulder dystocia"],
  "posterior arm delivery": ["shoulder dystocia","internal rotation shoulder"],
  "erbs palsy": ["brachial plexus injury","shoulder dystocia","obstetric brachial plexus injury"],
  "brachial plexus injury": ["erbs palsy","shoulder dystocia","obstetric brachial plexus injury"],
  "zavanelli manoeuvre": ["cephalic replacement","shoulder dystocia","symphysiotomy"],
  "cleidotomy": ["shoulder dystocia","zavanelli manoeuvre","symphysiotomy"],
  "magnesium toxicity": ["mgso4 toxicity","calcium gluconate","calcium chloride","magnesium overdose","loss of reflexes"],
  "adrenaline": ["epinephrine","anaphylaxis treatment","cardiac arrest drug","1 in 1000","1 in 10000"],
  "anaphylaxis": ["adrenaline","anaphylactic reaction","mast cell tryptase","allergic collapse"],
  "maternal sepsis": ["septic shock pregnancy","surviving sepsis","sepsis six","sepsis in pregnancy","gtg64"],
  "sepsis six": ["sepsis bundle","maternal sepsis","sepsis in pregnancy","hour 1 bundle"],
  "puerperal sepsis": ["maternal sepsis","postpartum sepsis","endometritis","sepsis following pregnancy"],
  "postpartum sepsis": ["puerperal sepsis","maternal sepsis","endometritis"],
  "endometritis": ["puerperal sepsis","maternal sepsis","postpartum infection","offensive lochia"],
  "necrotising fasciitis": ["maternal sepsis","surgical emergency infection","necrotizing fasciitis"],
  "group a strep": ["gas sepsis","group a streptococcus","maternal sepsis","invasive gas"],
  "gas sepsis": ["group a strep","group a streptococcus","maternal sepsis"],
  "meows": ["maternal early obstetric warning score","early warning score pregnancy","track and trigger","maternal sepsis"],

  "perinatal mental health": ["postnatal depression","antenatal depression","epds","mental health pregnancy","postpartum psychosis"],
  "postnatal depression": ["perinatal mental health","epds","postpartum depression","antidepressants pregnancy","sertraline"],
  "antenatal depression": ["perinatal mental health","epds","depression pregnancy","antidepressants pregnancy"],
  "epds": ["edinburgh postnatal depression scale","perinatal mental health","postnatal depression score"],
  "postpartum psychosis": ["perinatal mental health","puerperal psychosis","postnatal psychosis","lithium"],
  "antidepressants pregnancy": ["sertraline","fluoxetine","ssri pregnancy","perinatal mental health"],
  "ssri pregnancy": ["sertraline","fluoxetine","antidepressants pregnancy","perinatal mental health"],
  "sertraline": ["ssri","antidepressant","perinatal mental health","postnatal depression"],
  "fluoxetine": ["ssri","antidepressant","perinatal mental health","postnatal depression"],
  "lithium": ["mood stabiliser","bipolar pregnancy","perinatal mental health","postpartum psychosis"],
  "bipolar pregnancy": ["lithium","mood stabiliser","perinatal mental health","sodium valproate"],
  "sodium valproate": ["valproate contraindicated","teratogenic","bipolar pregnancy","lamotrigine"],
};
